Repository bareos/bareos, pull requests merged in 2021-08, with the labels that each got.

#903 webui: fix pool module router constraints
  CHANGELOG.md
  webui/module/Pool/config/module.config.php
Labels: requires backport to 20, requires backport to 19.2, requires backport to 18.2

#904 webui: fix pool module router constraints
  CHANGELOG.md
  webui/module/Pool/config/module.config.php
Labels: is a backport to 20

#905 webui: fix pool module router constraints
  webui/module/Pool/config/module.config.php
Labels: is a backport to 19.2

#906 webui: fix pool module router constraints
  webui/module/Pool/config/module.config.php
Labels: is a backport to 18.2

#902 webui: add missing symlinks for polish localization
  webui/public/js/locale/pl_PL/LC_MESSAGES/pl_PL.mo
  webui/public/js/locale/pl_PL/LC_MESSAGES/pl_PL.po
Labels: is a backport to 19.2

#901 webui: add missing symlinks for polish localization
  CHANGELOG.md
  webui/public/js/locale/pl_PL/LC_MESSAGES/pl_PL.mo
  webui/public/js/locale/pl_PL/LC_MESSAGES/pl_PL.po
Labels: is a backport to 20

#900 webui: add missing symlinks for polish localization
  CHANGELOG.md
  webui/public/js/locale/pl_PL/LC_MESSAGES/pl_PL.mo
  webui/public/js/locale/pl_PL/LC_MESSAGES/pl_PL.po
Labels: requires backport to 20, requires backport to 19.2

#898 webui: fix issue 0001235
  CHANGELOG.md
  webui/module/Dashboard/view/dashboard/dashboard/index.phtml
  webui/module/Job/view/job/job/details.phtml
  webui/module/Job/view/job/job/index.phtml
  webui/module/Media/view/media/media/details.phtml
  webui/module/Pool/view/pool/pool/details.phtml
Labels: is a backport to 20

#899 webui: fix issue 0001235
  webui/module/Dashboard/view/dashboard/dashboard/index.phtml
  webui/module/Job/view/job/job/details.phtml
  webui/module/Job/view/job/job/index.phtml
  webui/module/Media/view/media/media/details.phtml
  webui/module/Pool/view/pool/pool/details.phtml
Labels: is a backport to 19.2

#897 core: improve mtx-changer debug output
  core/scripts/mtx-changer.in
Labels: enhancement

#909 webui: typo fix in RestoreController.php
  webui/module/Restore/src/Restore/Controller/RestoreController.php
Labels: nobuild
