Repository bareos/bareos, pull requests merged in 2021-11, with the labels that each got.

#956 Log LDAP info error (e.g. expired SSL cert error)
  CHANGELOG.md
  core/src/plugins/filed/python/ldap/BareosFdPluginLDAP.py
Labels: requires backport to 20

#970 Log LDAP info error (e.g. expired SSL cert error)
  CHANGELOG.md
  core/src/plugins/filed/python/ldap/BareosFdPluginLDAP.py
Labels: is a backport to 20

#976 backport adaptions for fedora 35
  CHANGELOG.md
  core/platforms/win32/winbareos-nsi.spec
  core/platforms/win32/winbareos.nsi
  docs/pkglists/Fedora_35.x86_64
  python-bareos/packaging/python-bareos.spec
  webui/vendor/zendframework/zend-i18n/src/Translator/Loader/Gettext.php
  webui/vendor/zendframework/zend-i18n/src/Translator/Loader/PhpArray.php
  webui/vendor/zendframework/zend-i18n/src/Translator/Loader/PhpMemoryArray.php
Labels: is a backport to 20

#977 backport adaptions for fedora 35
  core/platforms/win32/winbareos-nsi.spec
  core/platforms/win32/winbareos.nsi
  docs/pkglists/Fedora_35.x86_64
  python-bareos/packaging/python-bareos.spec
  webui/vendor/zendframework/zend-i18n/src/Translator/Loader/Gettext.php
  webui/vendor/zendframework/zend-i18n/src/Translator/Loader/PhpArray.php
  webui/vendor/zendframework/zend-i18n/src/Translator/Loader/PhpMemoryArray.php
Labels: is a backport to 19.2

#973 stored: don't unload tapes from blocked devices
  CHANGELOG.md
  core/src/stored/autochanger.cc
Labels: requires backport to 20

#975 stored: don't unload tapes from blocked devices
  CHANGELOG.md
  core/src/stored/autochanger.cc
Labels: is a backport to 20

#963 BareosCheckFunctions: check for chflags()
  CHANGELOG.md
  cmake/BareosCheckChflags.cmake
  core/cmake/BareosCheckFunctions.cmake
  core/cmake/BareosCheckSymbols.cmake
  systemtests/tests/CMakeLists.txt
  systemtests/tests/chflags/CMakeLists.txt
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/console/bareos-mon.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/job/BackupCatalog.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-fd.d/director/bareos-mon.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/chflags/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/chflags/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-sd.d/director/bareos-mon.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/chflags/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/chflags/etc/bareos/bconsole.conf.in
  systemtests/tests/chflags/testrunner
Labels: requires backport to 20

#981 Fix PostgreSQL create database script and client_min_message level
  CHANGELOG.md
  core/src/cats/create_bareos_database.in
  core/src/cats/ddl/updates/postgresql.11_12.sql
  core/src/cats/ddl/updates/postgresql.12_14.sql
  core/src/cats/ddl/updates/postgresql.14_2001.sql
  core/src/cats/ddl/updates/postgresql.2001_2002.sql
  core/src/cats/ddl/updates/postgresql.2002_2003.sql
  core/src/cats/ddl/updates/postgresql.2003_2004.sql
  core/src/cats/ddl/updates/postgresql.2004_2171.sql
  core/src/cats/ddl/updates/postgresql.2171_2192.sql
  core/src/cats/ddl/updates/postgresql.2192_2210.sql
  core/src/cats/ddl/updates/postgresql.bee.1017_2004.sql
Labels: requires backport to 20

#974 BareosCheckFunctions: check for chflags()
  CHANGELOG.md
  cmake/BareosCheckChflags.cmake
  core/cmake/BareosCheckFunctions.cmake
  core/cmake/BareosCheckSymbols.cmake
  systemtests/CMakeLists.txt
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/console/bareos-mon.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/job/BackupCatalog.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/chflags/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-fd.d/director/bareos-mon.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/chflags/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/chflags/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-sd.d/director/bareos-mon.conf.in
  systemtests/tests/chflags/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/chflags/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/chflags/etc/bareos/bconsole.conf.in
  systemtests/tests/chflags/testrunner
Labels: is a backport to 20

#983 Fix PostgreSQL create database script and client_min_message level
  CHANGELOG.md
  core/src/cats/create_bareos_database.in
  core/src/cats/ddl/updates/postgresql.11_12.sql
  core/src/cats/ddl/updates/postgresql.12_14.sql
  core/src/cats/ddl/updates/postgresql.14_2001.sql
  core/src/cats/ddl/updates/postgresql.2001_2002.sql
  core/src/cats/ddl/updates/postgresql.2002_2003.sql
  core/src/cats/ddl/updates/postgresql.2003_2004.sql
  core/src/cats/ddl/updates/postgresql.2004_2171.sql
  core/src/cats/ddl/updates/postgresql.2171_2192.sql
  core/src/cats/ddl/updates/postgresql.bee.1017_2004.sql
Labels: is a backport to 20

#991 droplet: fix droplet xattr.h include (backport to bareos-20)
  CHANGELOG.md
  core/src/droplet/libdroplet/src/backend/posix/reqbuilder.c
  core/src/droplet/libdroplet/src/utils.c
Labels: is a backport to 20

#984 Replace non-existent "latest" by 20 in Windows downloads links
  docs/manuals/source/TasksAndConcepts/TheWindowsVersionOfBareos.rst
Labels: is a backport to 20

#995 Include zero-file incremental backups in always-incremental consolidation
  CHANGELOG.md
  core/src/cats/sql_get.cc
  docs/manuals/source/TasksAndConcepts/AlwaysIncrementalBackupScheme.rst
  systemtests/tests/ai-consolidate-ignore-duplicate-job/testrunner
Labels: requires backport to 20

#1000 Include zero-file incremental backups in always-incremental consolidation
  CHANGELOG.md
  core/src/cats/sql_get.cc
Labels: is a backport to 20

#1001 director: fix crash in status scheduler when client is not set
  CHANGELOG.md
  core/src/dird/ua_status.cc
Labels: is a backport to 20

#965 director: fix crash in status scheduler when client is not set
  CHANGELOG.md
  core/src/dird/ua_status.cc
  systemtests/tests/scheduler-backup/etc/bareos/bareos-dir.d/job/copy.conf
  systemtests/tests/scheduler-backup/test-setup
  systemtests/tests/scheduler-backup/testrunner-scheduler-backup
  systemtests/tests/scheduler-backup/testrunner-scheduler-status-copy-job
Labels: requires backport to 20, requires backport to 19.2
