Repository bareos/bareos, pull requests merged in 2021-09, with the labels that each got.

#919 `update slots` command crashes director when device or autochanger disappears
  CHANGELOG.md
  core/src/dird/sd_cmds.cc
Labels: requires backport to 20, requires backport to 19.2, requires backport to 18.2

#918 scripts: Fix logrotate by adding su instruction
  CHANGELOG.md
  core/scripts/logrotate.in
Labels: requires backport to 20, requires backport to 19.2, requires backport to 18.2

#916 missing job name in `End Job Session` in non-verbose output of bls
  CHANGELOG.md
  core/src/stored/label.cc
Labels: requires backport to 20

#920 webui: set some options on chromedriver
  CHANGELOG.md
  webui/tests/selenium/webui-selenium-test.py
Labels: requires backport to 20, requires backport to 19.2, requires backport to 18.2

#930 core: avoid nullptr dereference
  core/src/lib/output_formatter.cc
Labels: is a backport to 18.2

#931 core: avoid nullptr dereference
  core/src/lib/output_formatter.cc
Labels: is a backport to 19.2

#932 docs: Avoid duplicate label warnings
  docs/manuals/source/Appendix/BareosPrograms.rst
  docs/manuals/source/Appendix/OperatingSystems.rst
  docs/manuals/source/DeveloperGuide/jobexec.rst
  docs/manuals/source/DeveloperGuide/netprotocol.rst
  docs/manuals/source/DocumentationStyleGuide/BareosSpecificFormatting/Release.rst
  docs/manuals/source/DocumentationStyleGuide/example/nwdiag.rst.inc
  docs/manuals/source/IntroductionAndTutorial/InstallingBareosWebui.rst
  docs/manuals/source/IntroductionAndTutorial/Tutorial.rst
  docs/manuals/source/TasksAndConcepts/CatalogMaintenance.rst
  docs/manuals/source/TasksAndConcepts/Plugins.rst
  docs/manuals/source/TasksAndConcepts/TransportEncryption.rst
  docs/manuals/source/TasksAndConcepts/UsingTapeDrivesWithoutAutochanger.rst
  docs/manuals/source/man/bareos-dbcopy.rst
Labels: requires backport to 20, requires backport to 19.2, requires backport to 18.2

#939 Backport PR #932 to bareos-20
  docs/manuals/source/Appendix/BareosPrograms.rst
  docs/manuals/source/Appendix/OperatingSystems.rst
  docs/manuals/source/DeveloperGuide/jobexec.rst
  docs/manuals/source/DeveloperGuide/netprotocol.rst
  docs/manuals/source/DocumentationStyleGuide/BareosSpecificFormatting/Release.rst
  docs/manuals/source/DocumentationStyleGuide/example/nwdiag.rst.inc
  docs/manuals/source/IntroductionAndTutorial/InstallingBareosWebui.rst
  docs/manuals/source/IntroductionAndTutorial/Tutorial.rst
  docs/manuals/source/TasksAndConcepts/CatalogMaintenance.rst
  docs/manuals/source/TasksAndConcepts/Plugins.rst
  docs/manuals/source/TasksAndConcepts/TransportEncryption.rst
  docs/manuals/source/TasksAndConcepts/UsingTapeDrivesWithoutAutochanger.rst
  docs/manuals/source/man/bareos-dbcopy.rst
Labels: is a backport to 20

#941 Backport of PR #932 to bareos-18.2
  docs/manuals/source/Appendix/OperatingSystems.rst
  docs/manuals/source/DeveloperGuide/jobexec.rst
  docs/manuals/source/DocumentationStyleGuide/BareosSpecificFormatting/Release.rst
  docs/manuals/source/DocumentationStyleGuide/example/nwdiag.rst.inc
  docs/manuals/source/IntroductionAndTutorial/InstallingBareosWebui.rst
  docs/manuals/source/IntroductionAndTutorial/Tutorial.rst
  docs/manuals/source/TasksAndConcepts/CatalogMaintenance.rst
  docs/manuals/source/TasksAndConcepts/Plugins.rst
  docs/manuals/source/TasksAndConcepts/TransportEncryption.rst
  docs/manuals/source/TasksAndConcepts/UsingTapeDrivesWithoutAutochanger.rst
Labels: is a backport to 18.2

#940 Backport PR#932 to bareos-19.2
  docs/manuals/source/Appendix/BareosPrograms.rst
  docs/manuals/source/Appendix/Howtos.rst
  docs/manuals/source/Appendix/OperatingSystems.rst
  docs/manuals/source/Appendix/ReleaseNotes.rst
  docs/manuals/source/DeveloperGuide/AutomaticVersionGeneration.rst
  docs/manuals/source/DeveloperGuide/jobexec.rst
  docs/manuals/source/DeveloperGuide/netprotocol.rst
  docs/manuals/source/DocumentationStyleGuide/BareosSpecificFormatting/Release.rst
  docs/manuals/source/DocumentationStyleGuide/example/nwdiag.rst.inc
  docs/manuals/source/IntroductionAndTutorial/InstallingBareosWebui.rst
  docs/manuals/source/IntroductionAndTutorial/Tutorial.rst
  docs/manuals/source/TasksAndConcepts/CatalogMaintenance.rst
  docs/manuals/source/TasksAndConcepts/Plugins.rst
  docs/manuals/source/TasksAndConcepts/TransportEncryption.rst
  docs/manuals/source/TasksAndConcepts/UsingTapeDrivesWithoutAutochanger.rst
  docs/manuals/source/man/bareos-dbcopy.rst
Labels: is a backport to 19.2
