Repository bareos/bareos, pull requests merged in 2021-04, with the labels that each got.

#763 Fix CommandACL bug that prevents messages to be seen
  CHANGELOG.md
  core/src/dird/ua_output.cc
  systemtests/tests/bareos-acl/etc/bareos/bareos-dir.d/console/bareos-acl-none.conf.in
  systemtests/tests/bareos-acl/etc/bareos/bareos-dir.d/console/bareos-acl-restricted.conf.in
  systemtests/tests/bareos-acl/etc/bareos/bareos-dir.d/console/bareos-acl-status-conf.conf.in
  systemtests/tests/bareos-acl/etc/bareos/bareos-dir.d/console/bareos-acl-status.conf.in
  systemtests/tests/bareos-acl/etc/bareos/bareos-dir.d/console/bareos-acl.conf.in
  systemtests/tests/bareos-acl/etc/bareos/bareos-dir.d/console/bareos-mon.conf.in
  systemtests/tests/bareos-acl/etc/bareos/bconsole-acl-restricted.conf.in
Labels: bug, requires backport to 20

#795 Fix CommandACL bug that prevents messages to be seen
  CHANGELOG.md
  core/src/dird/ua_output.cc
  systemtests/tests/bareos-acl/etc/bareos/bareos-dir.d/console/bareos-acl-none.conf.in
  systemtests/tests/bareos-acl/etc/bareos/bareos-dir.d/console/bareos-acl-restricted.conf.in
  systemtests/tests/bareos-acl/etc/bareos/bareos-dir.d/console/bareos-acl-status-conf.conf.in
  systemtests/tests/bareos-acl/etc/bareos/bareos-dir.d/console/bareos-acl-status.conf.in
  systemtests/tests/bareos-acl/etc/bareos/bareos-dir.d/console/bareos-acl.conf.in
  systemtests/tests/bareos-acl/etc/bareos/bareos-dir.d/console/bareos-mon.conf.in
  systemtests/tests/bareos-acl/etc/bareos/bconsole-acl-restricted.conf.in
Labels: bug, is a backport to 20

#792 gfapi-fd: Fix possible crash on second glfs_close()
  CHANGELOG.md
  core/src/plugins/filed/gfapi/gfapi-fd.cc
Labels: bug, requires backport to 18.2, requires backport to 19.2, requires backport to 20

#805 docs: change code-block language value on install scripts (backport bareos-20)
  CHANGELOG.md
  docs/manuals/source/IntroductionAndTutorial/InstallingBareos.rst
  docs/manuals/source/conf.py
Labels: is a backport to 20

#806 docs: corrected some wording
  docs/manuals/source/TasksAndConcepts/AlwaysIncrementalBackupScheme.rst
Labels: requires backport to 20

#800 docs: corrected some wording
  docs/manuals/source/TasksAndConcepts/AlwaysIncrementalBackupScheme.rst
Labels: is a backport to 20
