Repository bareos/bareos, pull requests merged in 2021-12, with the labels that each got.

#1018 webui: update localization
  CHANGELOG.md
  webui/module/Application/language/cn_CN.po
  webui/module/Application/language/cs_CZ.po
  webui/module/Application/language/de_DE.mo
  webui/module/Application/language/de_DE.po
  webui/module/Application/language/en_EN.po
  webui/module/Application/language/es_ES.mo
  webui/module/Application/language/es_ES.po
  webui/module/Application/language/fr_FR.po
  webui/module/Application/language/hu_HU.po
  webui/module/Application/language/it_IT.mo
  webui/module/Application/language/it_IT.po
  webui/module/Application/language/nl_BE.po
  webui/module/Application/language/pl_PL.mo
  webui/module/Application/language/pl_PL.po
  webui/module/Application/language/pt_BR.po
  webui/module/Application/language/ru_RU.mo
  webui/module/Application/language/ru_RU.po
  webui/module/Application/language/sk_SK.po
  webui/module/Application/language/tr_TR.mo
  webui/module/Application/language/tr_TR.po
  webui/module/Application/language/uk_UA.mo
  webui/module/Application/language/uk_UA.po
  webui/module/Application/language/webui.pot
Labels: release critical 21.0.0

#992 build EL_8 for RHEL 8 derivatives (Alma, Rocky, CentOS) on rocky linux 8 image
  .matrix.yml
  CHANGELOG.md
  docs/pkglists/EL_8.x86_64
Labels: release critical 21.0.0

#966 console: prune command gained support to prune multiple volumes at once
  CHANGELOG.md
  core/src/cats/cats.h
  core/src/cats/sql_get.cc
  core/src/dird/ua.cc
  core/src/dird/ua.h
  core/src/dird/ua_cmds.cc
  core/src/dird/ua_output.cc
  core/src/dird/ua_prune.cc
  core/src/dird/ua_purge.cc
  core/src/dird/ua_select.cc
  core/src/dird/ua_select.h
  docs/manuals/source/TasksAndConcepts/BareosConsole.rst
  systemtests/tests/volume-pruning/testrunner
Labels: release critical 21.0.0

#1023 webui: client details now can be displayed for client names containing dots
  CHANGELOG.md
  webui/module/Client/src/Client/Controller/ClientController.php
  webui/public/js/bootstrap-table-formatter.js
Labels: release critical 21.0.0

#989 dird: `status subscriptions` shows more details about subscription units
  .bareos-check-sources-ignore
  CHANGELOG.md
  core/src/cats/bdb_query_enum_class.h
  core/src/cats/bdb_query_names.inc
  core/src/cats/ddl/creates/postgresql.sql
  core/src/cats/ddl/grants/postgresql-readonly.sql
  core/src/cats/ddl/grants/postgresql.sql
  core/src/cats/ddl/updates/postgresql.2192_2210.sql
  core/src/cats/dml/0080_subscription_select_backup_unit_overview_0
  core/src/cats/dml/0081_subscription_select_backup_unit_total_1
  core/src/cats/dml/0082_subscription_select_unclassified_client_fileset_0
  core/src/cats/dml/0083_subscription_select_unclassified_amount_data_0
  core/src/cats/mysql_queries.inc
  core/src/cats/postgresql_queries.inc
  core/src/cats/sqlite_queries.inc
  core/src/dird/dird.cc
  core/src/dird/dird_conf.h
  core/src/dird/job.cc
  core/src/dird/ua_cmds.cc
  core/src/dird/ua_status.cc
  docs/manuals/source/TasksAndConcepts/BareosConsole.rst
  systemtests/tests/bareos/CMakeLists.txt
  systemtests/tests/bareos/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/bareos/expected/status-subscriptions-detail.txt
  systemtests/tests/bareos/expected/status-subscriptions-unknown.txt
  systemtests/tests/bareos/expected/status-subscriptions.txt
  systemtests/tests/bareos/testrunner-simple-backup-and-restore
  systemtests/tests/bareos/testrunner-simple-list-jobs
  systemtests/tests/bareos/testrunner-status-subscriptions
Labels: release critical 21.0.0

#1026 dird: avoid crash in job listing when "current" and "count" are both specified at the same time
  CHANGELOG.md
  core/src/dird/ua_output.cc
Labels: release critical 21.0.0

#1025 dird: fix `llist jobs current` not displaying correct data
  CHANGELOG.md
  core/src/cats/dml/0006_list_jobs
  core/src/cats/dml/0007_list_jobs_long
  core/src/cats/dml/0009_list_jobs_last
  core/src/cats/dml/0010_list_jobs_long_last
  core/src/cats/mysql_queries.inc
  core/src/cats/postgresql_queries.inc
  core/src/cats/sqlite_queries.inc
  core/src/dird/ua_output.cc
  systemtests/tests/bareos/CMakeLists.txt
  systemtests/tests/bareos/testrunner-simple-list-jobs
  systemtests/tests/python-bareos/test_list_jobs.py
Labels: release critical 21.0.0

#1024 systemtests: add a test for the jobs last status table in webui
  CHANGELOG.md
  systemtests/CMakeLists.txt
  webui/tests/selenium/webui-selenium-test.py
Labels: release critical 21.0.0

#1028 docs: add documentation about Unified Linux Client
  .gitignore
  CHANGELOG.md
  docs/manuals/source/Appendix/OperatingSystems.rst
  docs/manuals/source/IntroductionAndTutorial/InstallingBareos.rst
  docs/manuals/source/IntroductionAndTutorial/WhatIsBareos.rst
  docs/manuals/source/TasksAndConcepts/StorageBackends.rst
Labels: release critical 21.0.0

#1029 debian: don't start daemons on install or upgrade
  .gitignore
  CHANGELOG.md
  debian/control
  debian/control.bareos-universal-client
  debian/rules
Labels: release critical 21.0.0

#1033 Use correct packages_dir when releasing restapi to pypi
  .github/workflows/publish_restapi_to_pypi.yml
  CHANGELOG.md
Labels: requires backport to 21

#1031 debian: set postgres db parameter
  CHANGELOG.md
  core/README.dbconfig
  debian/bareos-database-common.postinst.in
Labels: requires backport to 21

#1036 debian: set postgres db parameter
  CHANGELOG.md
  core/README.dbconfig
  debian/bareos-database-common.postinst.in
Labels: is a backport to 21
