Repository bareos/bareos, pull requests merged in 2021-06, with the labels that each got.

#831 vmware: Fix bareos_vadp_dumper VMDK File creation (backport of PR 826)
  vmware/vadp_dumper/bareos_vadp_dumper.cc
Labels: is a backport to 19.2

#832 vmware: Fix bareos_vadp_dumper VMDK File creation (backport of PR 826)
  vmware/vadp_dumper/bareos_vadp_dumper.cpp
Labels: is a backport to 18.2

#830 vmware: Fix bareos_vadp_dumper VMDK File creation (backport of PR 826)
  CHANGELOG.md
  core/src/vmware/vadp_dumper/bareos_vadp_dumper.cc
Labels: is a backport to 20

#835 webui: set default extras as empty array to prevent compact() errors
  webui/vendor/zendframework/zend-view/src/Helper/HeadLink.php
Labels: is a backport to 18.2

#834 webui: set default extras as empty array to prevent compact() errors
  webui/vendor/zendframework/zend-view/src/Helper/HeadLink.php
Labels: is a backport to 19.2

#833 webui: set default extras as empty array to prevent compact() errors
  CHANGELOG.md
  webui/vendor/zendframework/zend-view/src/Helper/HeadLink.php
Labels: is a backport to 20

#829 webui: set default extras as empty array to prevent compact() errors
  CHANGELOG.md
  webui/vendor/zendframework/zend-view/src/Helper/HeadLink.php
Labels: requires backport to 18.2, requires backport to 19.2, requires backport to 20

#823 drive selection in truncate command
  CHANGELOG.md
  core/src/dird/ua_cmds.cc
  core/src/stored/dir_cmd.cc
  docs/manuals/source/TasksAndConcepts/BareosConsole.rst
  systemtests/tests/multiplied-device/testrunner
Labels: requires backport to 20

#837 drive selection in truncate command (backport of PR 823)
  AUTHORS
  CHANGELOG.md
  core/src/dird/ua_cmds.cc
  docs/manuals/source/TasksAndConcepts/BareosConsole.rst
Labels: is a backport to 20

#828 Fix acquire deadlock on migrate/copy
  CHANGELOG.md
  core/src/stored/mac.cc
Labels: requires backport to 20

#838 Fix acquire deadlock on migrate/copy
  .gitignore
  CHANGELOG.md
  core/src/stored/mac.cc
Labels: is a backport to 20

#839 Fix acquire deadlock on migrate/copy
  core/src/stored/mac.cc
Labels: is a backport to 19.2

#844 docs: update VMware plugin documentation
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/Plugins.rst
Labels: requires backport to 18.2, requires backport to 19.2, requires backport to 20

#845 docs: update VMware plugin documentation (backport of PR 844)
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/Plugins.rst
Labels: is a backport to 20

#846 docs: update VMware plugin documentation (backport of PR 844)
  docs/manuals/source/TasksAndConcepts/Plugins.rst
Labels: is a backport to 19.2

#847 docs: update VMware plugin documentation (backport of PR 845)
  docs/manuals/source/TasksAndConcepts/Plugins.rst
Labels: is a backport to 18.2

#848 Fix some typos
  docs/manuals/source/DeveloperGuide/api.rst
Labels: is a backport to 20

#850 use correct type for drive-parameter in stored/dir_cmd.cc
  CHANGELOG.md
  core/src/stored/dir_cmd.cc
  systemtests/CMakeLists.txt
Labels: requires backport to 19.2, requires backport to 20

#840 webui: Fix infinite loop when trying to log in with invalid account
  CHANGELOG.md
  webui/vendor/Bareos/library/Bareos/BSock/BareosBSock.php
Labels: requires backport to 18.2, requires backport to 19.2, requires backport to 20

#864 webui: Fix infinite loop when trying to log in with invalid account
  CHANGELOG.md
  webui/vendor/Bareos/library/Bareos/BSock/BareosBSock.php
Labels: is a backport to 20

#865 webui: Fix infinite loop when trying to log in with invalid account
  webui/vendor/Bareos/library/Bareos/BSock/BareosBSock.php
Labels: is a backport to 19.2

#866 webui: Fix infinite loop when trying to log in with invalid account
  webui/vendor/Bareos/library/Bareos/BSock/BareosBSock.php
Labels: is a backport to 18.2

#871 webui: enable connect to the director via ipv6
  CHANGELOG.md
  docs/manuals/source/IntroductionAndTutorial/InstallingBareosWebui.rst
  webui/install/directors.ini.in
  webui/vendor/Bareos/library/Bareos/BSock/BareosBSock.php
Labels: is a backport to 20

#872 webui: enable connect to the director via ipv6
  docs/manuals/source/IntroductionAndTutorial/InstallingBareosWebui.rst
  webui/install/directors.ini.in
  webui/vendor/Bareos/library/Bareos/BSock/BareosBSock.php
Labels: is a backport to 19.2

#873 webui: enable connect to the director via ipv6
  docs/manuals/source/IntroductionAndTutorial/InstallingBareosWebui.rst
  webui/install/directors.ini.in
  webui/vendor/Bareos/library/Bareos/BSock/BareosBSock.php
Labels: is a backport to 18.2
