Repository bareos/bareos, pull requests merged in 2021-02, with the labels that each got.

#621 Fix LSN reading for incremental backups of MySQL 8.0 servers
  core/src/plugins/filed/python/percona-xtrabackup/BareosFdPluginPerconaXtraBackup.py
Labels: nobuild

#722 docs: add a pull request template file
  pull_request_template.md
Labels: nobuild

#730 python-{dir,fd,sd} plugins: do not load python2 and 3 versions in parallel
  CHANGELOG.md
  core/src/filed/fd_plugins.cc
  core/src/plugins/dird/python/python-dir.cc
  core/src/plugins/filed/python/python-fd.cc
  core/src/plugins/stored/python/python-sd.cc
  docs/manuals/source/TasksAndConcepts/Plugins.rst
  docs/manuals/source/manually_added_config_directive_descriptions/fd-client-PluginNames.rst.inc
Labels: requires backport

#733 python-{dir,fd,sd} plugins: do not load python2 and 3 versions in parallel (backport of PR #730)
  CHANGELOG.md
  core/src/filed/fd_plugins.cc
  core/src/plugins/dird/python/python-dir.cc
  core/src/plugins/filed/python/python-fd.cc
  core/src/plugins/stored/python/python-sd.cc
  docs/manuals/source/TasksAndConcepts/Plugins.rst
  docs/manuals/source/manually_added_config_directive_descriptions/fd-client-PluginNames.rst.inc
Labels: backport

#729 python plugins: fix problems with parallel jobs
  CHANGELOG.md
  core/src/plugins/dird/python/module/bareosdir.h
  core/src/plugins/filed/python/module/bareosfd.h
  core/src/plugins/filed/python/ovirt/BareosFdPluginOvirt.py
  core/src/plugins/stored/python/module/bareossd.h
  systemtests/tests/py2plug-fd-ovirt/etc/bareos/bareos-dir.d/fileset/OvirtTest.conf.in
  systemtests/tests/py2plug-fd-ovirt/etc/bareos/ovirt-plugin.ini.in
Labels: requires backport

#732 python plugins: fix problems with parallel jobs ( backport of PR #729)
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/BareosCommonMakefile
  core/src/plugins/dird/python/module/bareosdir.h
  core/src/plugins/filed/python/module/bareosfd.h
  core/src/plugins/filed/python/ovirt/BareosFdPluginOvirt.py
  core/src/plugins/stored/python/module/bareossd.h
  systemtests/tests/py2plug-fd-ovirt/etc/bareos/bareos-dir.d/fileset/OvirtTest.conf.in
  systemtests/tests/py2plug-fd-ovirt/etc/bareos/ovirt-plugin.ini.in
Labels: backport

#697 cmake: fix gentoo release detection
  core/cmake/distname.sh
Labels: nobuild

#726 Revert "webui: change updateBvfsCache trigger condition in restore controller"
  webui/module/Restore/src/Restore/Controller/RestoreController.php
Labels: requires backport

#727 Revert "webui: change updateBvfsCache trigger condition in restore controller"
  webui/module/Restore/src/Restore/Controller/RestoreController.php
Labels: backport

#740 storage: meaningful message for backend error
  CHANGELOG.md
  core/src/stored/dev.cc
  core/src/stored/sd_backends.cc
  core/src/stored/sd_backends.h
Labels: requires backport

#746 storage: meaningful message for backend error
  CHANGELOG.md
  core/src/stored/dev.cc
  core/src/stored/sd_backends.cc
  core/src/stored/sd_backends.h
Labels: backport

#739 stored: fix spooling sideffect bug
  CHANGELOG.md
  core/src/stored/dev.cc
  core/src/stored/vol_mgr.cc
Labels: requires backport

#734 stored: fix spooling sideffect bug
  CHANGELOG.md
  core/src/stored/dev.cc
  core/src/stored/vol_mgr.cc
Labels: backport

#723 plugins: add Debian packaging for PostgreSQL plugin
  CHANGELOG.md
  core/platforms/packaging/bareos.spec
  core/src/plugins/filed/python/postgres/BareosFdPluginPostgres.py
  debian/bareos-filedaemon-postgresql-python-plugin.install.in
  debian/bareos-filedaemon-python-plugins-common.install.in
  debian/control
  debian/control.bareos-filedaemon-python-plugins-common
  debian/control.bareos-filedaemon-python2-plugin
  debian/control.bareos-filedaemon-python3-plugin
  docs/manuals/source/Appendix/Howtos.rst
  docs/manuals/source/Configuration/Monitor.rst
  docs/manuals/source/DocumentationStyleGuide/SpecificFormatting.rst
  docs/manuals/source/DocumentationStyleGuide/example/code-block-cfg-mysql.rst.inc
  docs/manuals/source/TasksAndConcepts.rst
  docs/manuals/source/TasksAndConcepts/Plugins.rst
  docs/pkglists/Debian_10.x86_64
  docs/pkglists/Debian_9.0.i586
  docs/pkglists/Debian_9.0.x86_64
  docs/pkglists/Univention_4.3.x86_64
  docs/pkglists/Univention_4.4.x86_64
  docs/pkglists/xUbuntu_16.04.i586
  docs/pkglists/xUbuntu_16.04.x86_64
  docs/pkglists/xUbuntu_18.04.x86_64
  docs/pkglists/xUbuntu_20.04.x86_64
  systemtests/tests/py2plug-fd-postgres/database/setup_local_db.sh
  systemtests/tests/py2plug-fd-postgres/etc/bareos/bareos-dir.d/fileset/PluginTest.conf.in
  systemtests/tests/py2plug-fd-postgres/testrunner
Labels: requires backport

#745 plugins: add Debian packaging for PostgreSQL plugin (bareos-20)
  CHANGELOG.md
  core/platforms/packaging/bareos.spec
  core/src/plugins/filed/python/postgres/BareosFdPluginPostgres.py
  debian/bareos-filedaemon-postgresql-python-plugin.install.in
  debian/bareos-filedaemon-python-plugins-common.install.in
  debian/control
  debian/control.bareos-filedaemon-python-plugins-common
  debian/control.bareos-filedaemon-python2-plugin
  debian/control.bareos-filedaemon-python3-plugin
  docs/manuals/source/Appendix/Howtos.rst
  docs/manuals/source/Configuration/Monitor.rst
  docs/manuals/source/DocumentationStyleGuide/SpecificFormatting.rst
  docs/manuals/source/DocumentationStyleGuide/example/code-block-cfg-mysql.rst.inc
  docs/manuals/source/TasksAndConcepts.rst
  docs/manuals/source/TasksAndConcepts/Plugins.rst
  docs/pkglists/Debian_10.x86_64
  docs/pkglists/Debian_9.0.i586
  docs/pkglists/Debian_9.0.x86_64
  docs/pkglists/Univention_4.3.x86_64
  docs/pkglists/Univention_4.4.x86_64
  docs/pkglists/xUbuntu_16.04.i586
  docs/pkglists/xUbuntu_16.04.x86_64
  docs/pkglists/xUbuntu_18.04.x86_64
  docs/pkglists/xUbuntu_20.04.x86_64
  systemtests/tests/py2plug-fd-postgres/database/setup_local_db.sh
  systemtests/tests/py2plug-fd-postgres/etc/bareos/bareos-dir.d/fileset/PluginTest.conf.in
  systemtests/tests/py2plug-fd-postgres/testrunner
Labels: backport

#737 update SECURITY.md to show current support status
  SECURITY.md
Labels: nobuild

#742 ctest: run ctest in scripted mode
  CHANGELOG.md
  core/CMakeLists.txt
  core/CTestScript.cmake.in
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/Makefile
  core/platforms/packaging/bareos.spec
  core/src/plugins/filed/python/CMakeLists.txt
  debian/rules
Labels: requires backport

#749 Update StorageDaemon.rst
  docs/manuals/source/Configuration/StorageDaemon.rst
Labels: requires backport

#747 Fix broken link in the documentation
  AUTHORS
  CHANGELOG.md
  docs/manuals/source/IntroductionAndTutorial/WhatIsBareos.rst
Labels: requires backport

#751 ctest: run ctest in scripted mode (Backport of PR 742)
  CHANGELOG.md
  core/CMakeLists.txt
  core/CTestScript.cmake.in
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/Makefile
  core/platforms/packaging/bareos.spec
  core/src/plugins/filed/python/CMakeLists.txt
  debian/rules
Labels: backport

#748 python-bareos: fallback to ssl.PROTOCOL_SSLv23
  CHANGELOG.md
  python-bareos/bareos/bsock/lowlevel.py
Labels: requires backport

#753 Backport: python-bareos: fallback to ssl.PROTOCOL_SSLv23
  CHANGELOG.md
  python-bareos/bareos/bsock/lowlevel.py
Labels: backport
