Repository bareos/bareos, pull requests merged in 2021-05, with the labels that each got.

#797 gfapi-fd: Fix possible crash on second glfs_close()
  CHANGELOG.md
  core/src/plugins/filed/gfapi/gfapi-fd.cc
Labels: is a backport to 20

#798 gfapi-fd: Fix possible crash on second glfs_close()
  core/src/plugins/filed/gfapi-fd.cc
Labels: is a backport to 19.2

#799 gfapi-fd: Fix possible crash on second glfs_close()
  core/src/plugins/filed/gfapi-fd.cc
Labels: is a backport to 18.2

#807 sd_reservation.cc: add thread header
  core/src/tests/sd_reservation.cc
Labels: requires backport to 19.2, requires backport to 20

#811 updated pip-tools README file
  devtools/pip-tools/README.md
Labels: nobuild

#812 docs: fix broken hyperlink
  docs/manuals/source/TasksAndConcepts/PAM.rst
Labels: requires backport to 18.2, requires backport to 19.2

#813 docs: fix broken hyperlink
  docs/manuals/source/TasksAndConcepts/PAM.rst
Labels: is a backport to 19.2

#818 dev.cc: do not call virtual functions in destructor (backport to 20)
  .gitignore
  CHANGELOG.md
  core/src/stored/acquire.h
  core/src/stored/backends/cephfs_device.cc
  core/src/stored/backends/chunked_device.cc
  core/src/stored/backends/generic_tape_device.cc
  core/src/stored/backends/generic_tape_device.h
  core/src/stored/backends/gfapi_device.cc
  core/src/stored/backends/rados_device.cc
  core/src/stored/backends/unix_fifo_device.cc
  core/src/stored/backends/unix_fifo_device.h
  core/src/stored/backends/unix_file_device.h
  core/src/stored/backends/unix_tape_device.h
  core/src/stored/butil.cc
  core/src/stored/butil.h
  core/src/stored/dev.cc
  core/src/stored/dev.h
  core/src/tests/CMakeLists.txt
  core/src/tests/configs/sd_backend/bareos-sd.d/device/tape1.conf
  core/src/tests/configs/sd_backend/bareos-sd.d/storage/myself.conf.in
  core/src/tests/sd_backend.cc
  core/src/win32/stored/backends/win32_fifo_device.cc
  core/src/win32/stored/backends/win32_fifo_device.h
  core/src/win32/stored/backends/win32_file_device.cc
  core/src/win32/stored/backends/win32_file_device.h
  core/src/win32/stored/backends/win32_tape_device.cc
  core/src/win32/stored/backends/win32_tape_device.h
  systemtests/tests/config-dump/testrunner
Labels: is a backport to 20

#784 fix py save packet memleak
  core/platforms/packaging/bareos.spec
  core/src/lib/message.cc
  core/src/lib/message_queue_item.h
  core/src/plugins/filed/python/module/bareosfd.cc
Labels: requires backport to 20

#826 vmware: Fix bareos_vadp_dumper VMDK File creation
  CHANGELOG.md
  core/src/vmware/vadp_dumper/bareos_vadp_dumper.cc
Labels: requires backport to 18.2, requires backport to 19.2, requires backport to 20
