Repository bareos/bareos, pull requests merged in 2021-03, with the labels that each got.

#754 Backport: python-bareos: fallback to ssl.PROTOCOL_SSLv23
  docs/manuals/source/Appendix/ReleaseNotes.rst
  python-bareos/bareos/bsock/lowlevel.py
Labels: is a backport to 19.2

#756 docs: Adapt HTML template to new matomo
  docs/manuals/source/_templates/layout.html
Labels: requires backport to 18.2, requires backport to 19.2, requires backport to 20

#759 docs: added hard link restore error documentation
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/TheRestoreCommand.rst
Labels: requires backport to 20

#769 Python > 3.7 error with libcloud and postgresql fd plugin
  CHANGELOG.md
  core/cmake/BareosFindAllLibraries.cmake
  core/src/plugins/filed/python/libcloud/BareosFdPluginLibcloud.py
  core/src/plugins/filed/python/postgres/BareosFdPluginPostgres.py
  core/src/plugins/filed/python/postgres/bareos-fd-postgres.py
  systemtests/CMakeLists.txt
  systemtests/tests/py2plug-fd-postgres/database/setup_local_db.sh
Labels: requires backport to 20

#775 Python > 3.7 error with libcloud and postgresql fd plugin
  CHANGELOG.md
  core/cmake/BareosFindAllLibraries.cmake
  core/src/plugins/filed/python/libcloud/BareosFdPluginLibcloud.py
  core/src/plugins/filed/python/postgres/BareosFdPluginPostgres.py
  core/src/plugins/filed/python/postgres/bareos-fd-postgres.py
  systemtests/CMakeLists.txt
  systemtests/tests/py2plug-fd-postgres/database/setup_local_db.sh
Labels: is a backport to 20

#778 python modules: fix memleak in module constants
  CHANGELOG.md
  core/src/plugins/dird/python/python-dir.cc
  core/src/plugins/filed/python/python-fd.cc
  core/src/plugins/filed/python/test/python-fd-module-tester.cc
  core/src/plugins/include/python_plugins_common.h
  core/src/plugins/stored/python/python-sd.cc
Labels: requires backport to 20

#781 python modules: fix memleak in module constants
  CHANGELOG.md
  core/src/plugins/dird/python/python-dir.cc
  core/src/plugins/filed/python/python-fd.cc
  core/src/plugins/filed/python/test/python-fd-module-tester.cc
  core/src/plugins/include/python_plugins_common.h
  core/src/plugins/stored/python/python-sd.cc
Labels: is a backport to 20
