Repository bareos/bareos, pull requests merged in 2022-06, with the labels that each got.

#1179 Add support for Ubuntu 22.04, Fedora 36, EL 9, openSUSE 15.4
  .matrix.yml
  CHANGELOG.md
  core/cmake/BareosFindAllLibraries.cmake
  core/platforms/packaging/bareos.spec
  core/src/droplet/libdroplet/CMakeLists.txt
  core/src/droplet/libdroplet/include/droplet/cdmi/crcmodel.h
  core/src/lib/CMakeLists.txt
  debian/control
  debian/control.src
  docs/pkglists/EL_9.x86_64
  docs/pkglists/Fedora_36.x86_64
  docs/pkglists/openSUSE_Leap_15.4.x86_64
  docs/pkglists/xUbuntu_22.04.x86_64
  python-bareos/debian/control
  python-bareos/packaging/python-bareos.spec
  systemtests/tests/py2plug-fd-contrib-bareos_tasks_mysql/mysqldefaults.in
  systemtests/tests/py3plug-fd-contrib-mysql_dump/mysqldefaults.in
  systemtests/tests/reload/reload_test_functions
Labels: requires backport to 21

#1180 doc: clarifies checkfilechanges option use case (not intended for plugin)
  CHANGELOG.md
  docs/manuals/source/Configuration/Director.rst
Labels: requires backport to 20, requires backport to 19.2, requires backport to 21, documentation

#1191 Add support for Ubuntu 22.04, Fedora 36, EL 9, openSUSE 15.4
  .matrix.yml
  CHANGELOG.md
  core/cmake/BareosFindAllLibraries.cmake
  core/platforms/packaging/bareos.spec
  core/src/droplet/libdroplet/CMakeLists.txt
  core/src/droplet/libdroplet/include/droplet/cdmi/crcmodel.h
  core/src/lib/CMakeLists.txt
  core/src/lib/timer_thread.cc
  debian/control
  debian/control.src
  devtools/pip-tools/check_sources.egg-info/PKG-INFO
  devtools/pip-tools/check_sources.egg-info/SOURCES.txt
  devtools/pip-tools/check_sources.egg-info/entry_points.txt
  docs/pkglists/EL_9.x86_64
  docs/pkglists/Fedora_36.x86_64
  docs/pkglists/openSUSE_Leap_15.4.x86_64
  docs/pkglists/xUbuntu_22.04.x86_64
  python-bareos/debian/control
  python-bareos/packaging/python-bareos.spec
  systemtests/tests/reload/reload_test_functions
Labels: is a backport to 21

#1196 Backport 1180 to bareos-20 doc checkfilechange
  CHANGELOG.md
  docs/manuals/source/Configuration/Director.rst
Labels: is a backport to 20, documentation
