Repository bareos/bareos, pull requests merged in 2022-12, with the labels that each got.

#1323 ndmp_tape.cc: do not log current rctx->rec in joblog
  CHANGELOG.md
  core/src/stored/ndmp_tape.cc
Labels: is a backport to 21

#1324 ndmp_tape.cc: do not log current rctx->rec in joblog
  CHANGELOG.md
  core/src/stored/ndmp_tape.cc
Labels: requires backport to 21

#1320 dird: stored: set statistics collection as deprecated
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/stored/stored_conf.cc
  core/src/tests/CMakeLists.txt
  docs/manuals/source/DeveloperGuide/gitworkflow.rst
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-sd-config-schema.json
  systemtests/tests/config-dump/etc/bareos/bareos-dir-19.2.7-show-verbose.conf.in
  systemtests/tests/config-dump/etc/bareos/bareos-dir-full.conf.in
Labels: Release critical 22

#1287 webui: switch from mod_php to php-fpm
  CHANGELOG.md
  core/platforms/packaging/bareos.spec
  debian/bareos-webui.postinst
  debian/control
  debian/control.bareos-webui
  docs/manuals/source/IntroductionAndTutorial/InstallingBareosWebui.rst
Labels: Release critical 22

#1276 webui: extend restore to handle plugin options
  CHANGELOG.md
  docs/manuals/source/IntroductionAndTutorial/BareosWebui.rst
  docs/manuals/source/include/images/bareos-webui-restore-0.png
  webui/install/bareos/bareos-dir.d/profile/webui-admin.conf
  webui/module/Client/src/Client/Model/ClientModel.php
  webui/module/Restore/src/Restore/Controller/RestoreController.php
  webui/module/Restore/src/Restore/Form/RestoreForm.php
  webui/module/Restore/src/Restore/Model/Restore.php
  webui/module/Restore/src/Restore/Model/RestoreModel.php
  webui/module/Restore/view/restore/restore/index.phtml
  webui/module/Restore/view/restore/restore/versions.phtml
  webui/vendor/Bareos/library/Bareos/BSock/BareosBSock.php
Labels: Release critical 22

#1326 bareos-fd-postgres: properly close database connection
  CHANGELOG.md
  core/src/plugins/filed/python/postgres/BareosFdPluginPostgres.py
Labels: requires backport to 21

#1312 status subscription: extend output
  CHANGELOG.md
  core/src/cats/cats.h
  core/src/cats/sql_list.cc
  core/src/dird/ua_status.cc
  core/src/lib/crypto.h
  core/src/lib/crypto_openssl.cc
  systemtests/tests/bareos/testrunner-status-subscriptions
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/python-bareos/test_acl.py
Labels: jenkins_repotest_nodebug, Release critical 22

#1327 dird: fix for crash when starting rescheduled jobs
  CHANGELOG.md
  core/src/dird/msgchan.cc
  systemtests/tests/CMakeLists.txt
  systemtests/tests/checkpoints/testrunner-checkpoints-on-cancel
  systemtests/tests/checkpoints/testrunner-checkpoints-on-kill
  systemtests/tests/checkpoints/testrunner-checkpoints-on-stop
  systemtests/tests/checkpoints/testrunner-checkpoints-regular-backup
  systemtests/tests/scheduler/CMakeLists.txt
  systemtests/tests/scheduler/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/scheduler/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/scheduler/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/scheduler/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/scheduler/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/scheduler/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/scheduler/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/scheduler/etc/bareos/bareos-dir.d/job/copy.conf
  systemtests/tests/scheduler/etc/bareos/bareos-dir.d/job/reschedulejob.conf
  systemtests/tests/scheduler/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/scheduler/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/scheduler/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/scheduler/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/scheduler/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/scheduler/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/scheduler/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/scheduler/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/scheduler/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/scheduler/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/scheduler/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/scheduler/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/scheduler/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/scheduler/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/scheduler/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/scheduler/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/scheduler/etc/bareos/bconsole.conf.in
  systemtests/tests/scheduler/test-setup
  systemtests/tests/scheduler/testrunner-reschedule
  systemtests/tests/scheduler/testrunner-scheduler-backup
  systemtests/tests/scheduler/testrunner-scheduler-status-copy-job
Labels: Release critical 22

#1309 unify and merge builds where possible
  .matrix.yml
  CHANGELOG.md
  core/platforms/packaging/bareos.spec
  docs/pkglists/EL_7.x86_64
  docs/pkglists/Fedora_37.x86_64
  docs/pkglists/RHEL_7.x86_64
  docs/pkglists/SUSE_15.x86_64
Labels: Release critical 22

#1328 bareos-fd-postgres: properly close database connection
  CHANGELOG.md
  core/src/plugins/filed/python/postgres/BareosFdPluginPostgres.py
Labels: is a backport to 21

#1280 webui: introduce subscription backup unit report
  CHANGELOG.md
  webui/module/Application/view/layout/layout.phtml.in
  webui/module/Director/src/Director/Controller/DirectorController.php
  webui/module/Director/src/Director/Model/Director.php
  webui/module/Director/src/Director/Model/DirectorModel.php
  webui/module/Director/view/director/director/index.phtml
  webui/module/Director/view/director/director/messages.phtml
  webui/module/Director/view/director/director/subscription.phtml
  webui/module/Job/src/Job/Controller/JobController.php
Labels: Release critical 22

#1332 python plugins: give python3 plugins priority over python2 plugins in packages
  CHANGELOG.md
  core/platforms/packaging/bareos.spec
  debian/control.bareos-director-python-plugins-common
  debian/control.bareos-director-python2-plugin
  debian/control.bareos-director-python3-plugin
  debian/control.bareos-filedaemon-python-plugins-common
  debian/control.bareos-filedaemon-python2-plugin
  debian/control.bareos-filedaemon-python3-plugin
  debian/control.bareos-storage-python2-plugin
  debian/control.bareos-storage-python3-plugin
  debian/control.vmware
Labels: Release critical 22

#1330 fix file count mismatch on restores that use recycled volumes
  CHANGELOG.md
  core/src/cats/sql_create.cc
  core/src/dird/restore.cc
  systemtests/scripts/functions
  systemtests/tests/bareos/etc/bareos/bareos-dir.d/job/recyclejob.conf
  systemtests/tests/bareos/etc/bareos/bareos-dir.d/pool/quickrecycle.conf
  systemtests/tests/bareos/testrunner-volume-recycling
Labels: Release critical 22

#1329 doc: update installation and renew update chapters
  CHANGELOG.md
  core/src/include/bareos.h
  docs/manuals/source/Appendix/OperatingSystems.rst
  docs/manuals/source/DocumentationStyleGuide/BareosSpecificFormatting/Links.rst
  docs/manuals/source/DocumentationStyleGuide/example/releasenotes-template.rst.inc
  docs/manuals/source/IntroductionAndTutorial/InstallingBareos.rst
  docs/manuals/source/IntroductionAndTutorial/InstallingBareosClient.rst
  docs/manuals/source/IntroductionAndTutorial/UpdatingBareos.rst
  docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
  docs/manuals/source/TasksAndConcepts/TheWindowsVersionOfBareos.rst
  docs/manuals/source/_extensions/bareos_urls.py
Labels: documentation, jenkins_repotest_nodebug, Release critical 22

#1333 docs: comparision between community and subscription repositories
  CHANGELOG.md
  docs/manuals/source/DocumentationStyleGuide/CommonNames.rst
  docs/manuals/source/IntroductionAndTutorial/InstallingBareos.rst
  docs/manuals/source/IntroductionAndTutorial/InstallingBareosWebui.rst
  docs/manuals/source/IntroductionAndTutorial/WhatIsBareos.rst
Labels: documentation, jenkins_repotest_nodebug

#1337 VMware Plugin: fix restore of backups taken before version 22
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/BareosFdPluginVMware.py
Labels: Release critical 22
