Repository bareos/bareos, pull requests merged in 2022-11, with the labels that each got.

#1279 lib: make foreach_res() reload-safe
  CHANGELOG.md
  core/src/dird/dird_conf.h
  core/src/dird/job.cc
  core/src/filed/dir_cmd.cc
  core/src/filed/filed.cc
  core/src/findlib/attribs.cc
  core/src/include/config.h.in
  core/src/lib/alist.h
  core/src/lib/attribs.cc
  core/src/lib/bareos_resource.cc
  core/src/lib/bareos_resource.h
  core/src/lib/dlist.h
  core/src/lib/htable.h
  core/src/lib/output_formatter_resource.cc
  core/src/lib/output_formatter_resource.h
  core/src/lib/parse_conf.h
  core/src/lib/plugins.cc
  core/src/lib/rblist.h
  core/src/lib/runscript.cc
  core/src/stored/reserve.cc
  core/src/stored/reserve.h
  core/src/tests/alist_test.cc
  core/src/tests/test_config_parser_dir.cc
Labels: requires backport to 21

#1301 lib: make foreach_res() reload-safe
  CHANGELOG.md
  core/src/lib/parse_conf.h
  core/src/lib/rblist.h
  core/src/tests/test_config_parser_dir.cc
Labels: is a backport to 21

#1302 webui: fix pool link in job details formatter
  CHANGELOG.md
  webui/module/Job/view/job/job/details.phtml
  webui/module/Job/view/job/job/index.phtml
Labels: requires backport to 20, requires backport to 21

#1303 webui: fix pool link in job details formatter
  CHANGELOG.md
  webui/module/Job/view/job/job/details.phtml
  webui/module/Job/view/job/job/index.phtml
Labels: is a backport to 21

#1304 webui: fix pool link in job details formatter
  CHANGELOG.md
  webui/module/Job/view/job/job/details.phtml
  webui/module/Job/view/job/job/index.phtml
Labels: is a backport to 20

#1313 systemtests: improve webui testing
  CHANGELOG.md
  core/platforms/win32/winbareos.nsi
  systemtests/CMakeLists.txt
  systemtests/cmake/BareosSystemtestFunctions.cmake
  systemtests/environment.in
  systemtests/scripts/webui.sh
  systemtests/tests/webui-common/bin/webui
  systemtests/tests/webui-common/etc/bareos-webui/directors.ini.in
  systemtests/tests/webui-common/testrunner.in
  webui/config/autoload/global.php.in
  webui/tests/selenium/README.md
  webui/tests/selenium/webui-selenium-test.py
Labels: jenkins_repotest_nodebug

#1317 doc: add new VSS troubleshooting instruction to Windows chapter.
  CHANGELOG.md
  docs/manuals/source/Appendix/Debugging.rst
  docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
  docs/manuals/source/TasksAndConcepts/TheWindowsVersionOfBareos.rst
Labels: documentation

#1315 dird: fix director resource not showing when using `show director` or the `--xc director` cli option
  CHANGELOG.md
  core/src/dird/show_cmd_available_resources.h
  core/src/dird/ua_output.cc
  core/src/dird/ua_output.h
  core/src/lib/parse_conf.cc
  core/src/tests/show_cmd_available_resources_equals_config_resources.cc
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/counter/random-counter.conf
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/schedule/random-schedule.conf
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/user/random-user.conf
  systemtests/tests/python-bareos/test_list_command.py
  systemtests/tests/python-bareos/test_show.py
Labels: requires backport to 21

#1322 dird: fix director resource not showing when using `show director`
  CHANGELOG.md
  core/src/dird/show_cmd_available_resources.h
  core/src/dird/ua_output.cc
  core/src/dird/ua_output.h
  core/src/tests/show_cmd_available_resources_equals_config_resources.cc
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/counter/random-counter.conf
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/schedule/random-schedule.conf
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/user/random-user.conf
  systemtests/tests/python-bareos/test_show.py
Labels: is a backport to 21
