Repository bareos/bareos, pull requests merged in 2022-03, with the labels that each got.

#1090 NDMP_BAREOS AutoXFlate support (backport PR #1013)
  CHANGELOG.md
  core/src/console/console.cc
  core/src/lib/compression.cc
  core/src/plugins/stored/autoxflate/autoxflate-sd.cc
  core/src/stored/ndmp_tape.cc
  core/src/stored/read_record.cc
  core/src/tools/bsmtp.cc
  systemtests/tests/ndmp/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/ndmp/etc/bareos/bareos-sd.d/device/FileStorage2.conf
  systemtests/tests/ndmp/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
Labels: is a backport to 21

#1085 webui: update jquery from v3.2.0 to v3.6.0
  CHANGELOG.md
  webui/public/js/jquery.js
  webui/public/js/jquery.min.js
Labels: is a backport to 20

#1083 webui: update jquery from v3.2.0 to v3.6.0
  CHANGELOG.md
  webui/public/js/jquery.js
  webui/public/js/jquery.min.js
Labels: requires backport to 20, requires backport to 19.2, requires backport to 21

#1086 webui: update jquery from v3.2.0 to v3.6.0
  .matrix.yml
  CHANGELOG.md
  webui/public/js/jquery.js
  webui/public/js/jquery.min.js
Labels: is a backport to 19.2

#1084 webui: update jquery from v3.2.0 to v3.6.0
  CHANGELOG.md
  webui/public/js/jquery.js
  webui/public/js/jquery.min.js
Labels: is a backport to 21

#1076 Fix context issue in bareos-dir python plugin
  CHANGELOG.md
  core/src/plugins/dird/python/module/bareosdir.h
  core/src/plugins/dird/python/python-dir.cc
  systemtests/tests/py2plug-dir/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/py2plug-dir/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf.in
  systemtests/tests/py2plug-dir/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/py2plug-dir/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/py2plug-dir/python-modules/BareosDirTest.py
  systemtests/tests/py2plug-dir/testrunner
Labels: is a backport to 21

#1103 webui: fix undefined array key warning
  CHANGELOG.md
  webui/module/Pool/src/Pool/Model/PoolModel.php
Labels: is a backport to 20

#1098 webui: fix undefined array key warning
  CHANGELOG.md
  webui/module/Pool/src/Pool/Model/PoolModel.php
Labels: requires backport to 20, requires backport to 21

#1097 webui: fix deprecated notice required param follows optional param
  CHANGELOG.md
  webui/module/Fileset/src/Fileset/Model/FilesetModel.php
Labels: requires backport to 20, requires backport to 21

#1100 webui: fix deprecated notice required param follows optional param
  CHANGELOG.md
  webui/module/Fileset/src/Fileset/Model/FilesetModel.php
Labels: is a backport to 21

#1101 webui: fix deprecated notice required param follows optional param
  CHANGELOG.md
  webui/module/Fileset/src/Fileset/Model/FilesetModel.php
Labels: is a backport to 20

#1102 webui: fix undefined array key warning
  CHANGELOG.md
  webui/module/Pool/src/Pool/Model/PoolModel.php
Labels: is a backport to 21

#1096 webui: fix uncaught TypeError if node.data is null
  CHANGELOG.md
  webui/module/Restore/view/restore/restore/index.phtml
  webui/module/Restore/view/restore/restore/versions.phtml
Labels: is a backport to 21

#1087 webui: fix uncaught TypeError if node.data is null
  CHANGELOG.md
  webui/module/Restore/view/restore/restore/index.phtml
  webui/module/Restore/view/restore/restore/versions.phtml
Labels: requires backport to 21

#1107 consolidate: purge jobids without files before starting the consolidation
  CHANGELOG.md
  core/src/cats/cats.h
  core/src/cats/postgresql.cc
  core/src/cats/sql_delete.cc
  core/src/cats/sql_get.cc
  core/src/cats/sql_update.cc
  core/src/dird/consolidate.cc
  core/src/dird/ua_purge.cc
  core/src/dird/vbackup.cc
  core/src/lib/bstringlist.h
  core/src/stored/append.cc
  systemtests/tests/ai-consolidate-ignore-duplicate-job/testrunner
Labels: is a backport to 21

#1108 cancel virtual backups if none of the jobids contains files
  .gitattributes
  CHANGELOG.md
  core/src/cats/sql.h
  core/src/dird/vbackup.cc
  core/src/lib/mem_pool.cc
  core/src/lib/mem_pool.h
  core/src/lib/util.cc
  core/src/lib/util.h
  systemtests/tests/virtualfull/testrunner
Labels: is a backport to 21

#1092 core cats: fix drop tables ddl
  CHANGELOG.md
  core/src/cats/ddl/drops/postgresql.sql
Labels: requires backport to 21

#1056 consolidate: purge jobids without files before starting the consolidation
  CHANGELOG.md
  core/src/cats/cats.h
  core/src/cats/postgresql.cc
  core/src/cats/sql_delete.cc
  core/src/cats/sql_get.cc
  core/src/cats/sql_update.cc
  core/src/dird/consolidate.cc
  core/src/dird/ua_purge.cc
  core/src/dird/vbackup.cc
  core/src/lib/bstringlist.h
  core/src/stored/append.cc
  systemtests/tests/ai-consolidate-ignore-duplicate-job/testrunner
Labels: requires backport to 21

#1113 Fix stale volumes/devices in bareos-sd after failure to acquire a read device on MAC jobs
  CHANGELOG.md
  core/src/dird/migrate.cc
  core/src/stored/mac.cc
  systemtests/tests/CMakeLists.txt
  systemtests/tests/copy-bscan/testrunner
  systemtests/tests/copy/CMakeLists.txt
  systemtests/tests/copy/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/copy/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/copy/etc/bareos/bareos-dir.d/console/bareos-mon.conf.in
  systemtests/tests/copy/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/copy/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/copy/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/copy/etc/bareos/bareos-dir.d/job/BackupCatalog.conf.in
  systemtests/tests/copy/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/copy/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/copy/etc/bareos/bareos-dir.d/job/copy.conf
  systemtests/tests/copy/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/copy/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/copy/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/copy/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/copy/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/copy/etc/bareos/bareos-dir.d/pool/FullCopy.conf
  systemtests/tests/copy/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/copy/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/copy/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/copy/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/copy/etc/bareos/bareos-dir.d/storage/NoSuchStorage.conf
  systemtests/tests/copy/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/copy/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/copy/etc/bareos/bareos-fd.d/director/bareos-mon.conf.in
  systemtests/tests/copy/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/copy/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/copy/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/copy/etc/bareos/bareos-sd.d/director/bareos-mon.conf.in
  systemtests/tests/copy/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/copy/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/copy/etc/bareos/bconsole.conf.in
  systemtests/tests/copy/testrunner-01-backup
  systemtests/tests/copy/testrunner-02-copy
  systemtests/tests/copy/testrunner-03-impossible-copy
  systemtests/tests/copy/testrunner-04-bscan
Labels: is a backport to 21

#1114 Fix stale volumes/devices in bareos-sd after failure to acquire a read device on MAC jobs
  CHANGELOG.md
  core/src/dird/migrate.cc
  core/src/stored/mac.cc
Labels: is a backport to 20

#1110 webui: show DIR message if ACL prevents a job rerun
  CHANGELOG.md
  webui/module/Job/src/Job/Controller/JobController.php
Labels: requires backport to 20, requires backport to 21

#1082 webui: analytics module: show stored data per jobname in treemap
  CHANGELOG.md
  docs/manuals/source/IntroductionAndTutorial/BareosWebui.rst
  webui/config/application.config.php
  webui/module/Analytics/Module.php
  webui/module/Analytics/autoload_classmap.php
  webui/module/Analytics/config/module.config.php
  webui/module/Analytics/src/Analytics/Controller/AnalyticsController.php
  webui/module/Analytics/src/Analytics/Model/Analytics.php
  webui/module/Analytics/src/Analytics/Model/AnalyticsModel.php
  webui/module/Analytics/view/analytics/analytics/index.phtml
  webui/module/Application/config/commands.csv
  webui/module/Application/config/module.config.php
  webui/public/js/d3/d3.js
  webui/public/js/d3/d3.min.js
Labels: requires backport to 21

#1115 dird: Add PAM authorization
  CHANGELOG.md
  contrib/misc/bareos_pam_integration/README.rst
  core/src/dird/auth_pam.cc
  docs/manuals/source/TasksAndConcepts/PAM.rst
  systemtests/cmake/BareosSystemtestFunctions.cmake
  systemtests/tests/bconsole-pam/bin/pam_exec_check.sh
  systemtests/tests/bconsole-pam/etc/bareos/bareos-dir.d/user/user4locked.conf
  systemtests/tests/bconsole-pam/etc/pam.d/bareos.in
  systemtests/tests/bconsole-pam/etc/user4locked.cred
  systemtests/tests/bconsole-pam/testrunner
  systemtests/tests/python-pam/etc/pam.d/bareos.in
  systemtests/tests/python-pam/testrunner
Labels: requires backport to 20, requires backport to 19.2, requires backport to 21

#1116 webui: analytics module: show stored data per jobname in treemap
  CHANGELOG.md
  docs/manuals/source/IntroductionAndTutorial/BareosWebui.rst
  webui/config/application.config.php
  webui/module/Analytics/Module.php
  webui/module/Analytics/autoload_classmap.php
  webui/module/Analytics/config/module.config.php
  webui/module/Analytics/src/Analytics/Controller/AnalyticsController.php
  webui/module/Analytics/src/Analytics/Model/Analytics.php
  webui/module/Analytics/src/Analytics/Model/AnalyticsModel.php
  webui/module/Analytics/view/analytics/analytics/index.phtml
  webui/module/Application/config/commands.csv
  webui/module/Application/config/module.config.php
  webui/public/js/d3/d3.js
  webui/public/js/d3/d3.min.js
Labels: is a backport to 21

#1118 Add PAM authorization
  CHANGELOG.md
  core/src/dird/auth_pam.cc
  docs/manuals/source/TasksAndConcepts/PAM.rst
  systemtests/cmake/BareosSystemtestFunctions.cmake
  systemtests/tests/bconsole-pam/bin/pam_exec_check.sh
  systemtests/tests/bconsole-pam/etc/bareos/bareos-dir.d/user/user4locked.conf
  systemtests/tests/bconsole-pam/etc/pam.d/bareos.in
  systemtests/tests/bconsole-pam/etc/user4locked.cred
  systemtests/tests/bconsole-pam/testrunner
  systemtests/tests/python-pam/etc/pam.d/bareos.in
  systemtests/tests/python-pam/testrunner
Labels: is a backport to 21

#1119 Add PAM authorization
  CHANGELOG.md
  core/src/dird/auth_pam.cc
  docs/manuals/source/TasksAndConcepts/PAM.rst
  systemtests/tests/bconsole-pam/bin/pam_exec_check.sh
  systemtests/tests/bconsole-pam/etc/bareos/bareos-dir.d/user/user4locked.conf
  systemtests/tests/bconsole-pam/etc/pam.d/bareos.in
  systemtests/tests/bconsole-pam/etc/user4locked.cred
  systemtests/tests/bconsole-pam/testrunner
  systemtests/tests/python-pam/etc/pam.d/bareos.in
Labels: is a backport to 20

#1121 Add PAM authorization
  CHANGELOG.md
  core/src/dird/auth_pam.cc
  docs/manuals/source/TasksAndConcepts/PAM.rst
  systemtests/tests/bconsole-pam/etc/pam.d/bareos.in
  systemtests/tests/python-pam/etc/pam.d/bareos.in
Labels: is a backport to 19.2

#1111 webui: show DIR message if ACL prevents a job rerun
  CHANGELOG.md
  webui/module/Job/src/Job/Controller/JobController.php
Labels: is a backport to 21

#1117 webui: introduce support Ukraine theme
  CHANGELOG.md
  webui/module/Application/view/layout/login.phtml.in
  webui/module/Auth/view/auth/auth/login.phtml
  webui/public/img/bareos-logo-small.png
  webui/public/img/bareos-logo.png
  webui/public/img/bareos.png
  webui/public/img/favicon.ico
Labels: requires backport to 20, requires backport to 19.2, requires backport to 21

#1112 webui: show DIR message if ACL prevents a job rerun
  CHANGELOG.md
  webui/module/Job/src/Job/Controller/JobController.php
Labels: is a backport to 20

#1124 webui: introduce support Ukraine theme
  CHANGELOG.md
  webui/module/Application/view/layout/login.phtml.in
  webui/module/Auth/view/auth/auth/login.phtml
  webui/public/img/bareos-logo-small.png
  webui/public/img/bareos-logo.png
  webui/public/img/bareos.png
  webui/public/img/favicon.ico
Labels: is a backport to 19.2

#1123 webui: introduce support Ukraine theme
  CHANGELOG.md
  webui/module/Application/view/layout/login.phtml.in
  webui/module/Auth/view/auth/auth/login.phtml
  webui/public/img/bareos-logo-small.png
  webui/public/img/bareos-logo.png
  webui/public/img/bareos.png
  webui/public/img/favicon.ico
Labels: is a backport to 20

#1122 webui: introduce support Ukraine theme
  CHANGELOG.md
  webui/module/Application/view/layout/login.phtml.in
  webui/module/Auth/view/auth/auth/login.phtml
  webui/public/img/bareos-logo-small.png
  webui/public/img/bareos-logo.png
  webui/public/img/bareos.png
  webui/public/img/favicon.ico
Labels: is a backport to 21

#1125 webui: add pool column to volume lists
  CHANGELOG.md
  webui/module/Media/view/media/media/details.phtml
  webui/module/Media/view/media/media/index.phtml
Labels: is a backport to 21

#1127 webui: fix restore file tree rendering
  CHANGELOG.md
  webui/module/Restore/view/restore/restore/index.phtml
  webui/module/Restore/view/restore/restore/versions.phtml
Labels: requires backport to 21

#1128 webui: fix restore file tree rendering
  CHANGELOG.md
  webui/module/Restore/view/restore/restore/index.phtml
  webui/module/Restore/view/restore/restore/versions.phtml
Labels: is a backport to 21

#1093 docs howto improve dbcopy migration
  CHANGELOG.md
  docs/manuals/source/Appendix/Howtos/MigrateABareosCatalogFromMySqlToPostgresql.rst.inc
Labels: requires backport to 21

#1131 fix director crash when there are no jobs to consolidate
  CHANGELOG.md
  core/src/cats/sql_get.cc
Labels: requires backport to 21

#1094 docs howto improve dbcopy migration
  CHANGELOG.md
  docs/manuals/source/Appendix/Howtos/MigrateABareosCatalogFromMySqlToPostgresql.rst.inc
Labels: is a backport to 21

#1072 console: multicolumn output: fill columns first
  CHANGELOG.md
  core/src/dird/ua_select.cc
  core/src/dird/ua_select.h
  core/src/tests/multicolumn_prompts.cc
  pull_request_template.md
Labels: requires backport to 21

#1133 console: multicolumn output: fill columns first
  CHANGELOG.md
  core/src/dird/ua_select.cc
  core/src/dird/ua_select.h
  core/src/tests/multicolumn_prompts.cc
  pull_request_template.md
Labels: is a backport to 21

#1136 cats: include only jobtypes in `list jobtotals` that write data to volumes
  CHANGELOG.md
  core/src/cats/sql_list.cc
Labels: is a backport to 21

#1142 jstreegrid: remove handling of IE < 8 using navigator interface to avoid warnings in chrome
  CHANGELOG.md
  webui/public/js/jstreegrid.js
Labels: is a backport to 20

#1143 jstreegrid: remove handling of IE < 8 using navigator interface to avoid warnings in chrome
  CHANGELOG.md
  webui/public/js/jstreegrid.js
Labels: is a backport to 19.2

#1141 jstreegrid: remove handling of IE < 8 using navigator interface to avoid warnings in chrome
  CHANGELOG.md
  webui/public/js/jstreegrid.js
Labels: is a backport to 21

#1140 jstreegrid: remove handling of IE < 8 using navigator interface to avoid warnings in chrome
  CHANGELOG.md
  webui/public/js/jstreegrid.js
Labels: requires backport to 20, requires backport to 19.2, requires backport to 21

#1139 webui: get volume and pool params from query instead of route
  CHANGELOG.md
  webui/module/Media/src/Media/Controller/MediaController.php
  webui/module/Pool/src/Pool/Controller/PoolController.php
  webui/public/js/bootstrap-table-formatter.js
Labels: requires backport to 20, requires backport to 21

#1144 webui: get volume and pool params from query instead of route
  CHANGELOG.md
  webui/module/Media/src/Media/Controller/MediaController.php
  webui/module/Pool/src/Pool/Controller/PoolController.php
  webui/public/js/bootstrap-table-formatter.js
Labels: is a backport to 21

#1145 webui: get volume and pool params from query instead of route
  CHANGELOG.md
  webui/module/Media/src/Media/Controller/MediaController.php
  webui/module/Pool/src/Pool/Controller/PoolController.php
  webui/public/js/bootstrap-table-formatter.js
Labels: is a backport to 20

#1137 docs: clarifies Sphinx bareos-extensions parallel_read_safe status
  CHANGELOG.md
  docs/manuals/source/_extensions/bareos-ext.py
  docs/manuals/source/_extensions/limitation.py
Labels: documentation
