Repository bareos/bareos, pull requests merged in 2022-02, with the labels that each got.

#1045 debian: add missing python plugin dependencies
  CHANGELOG.md
  debian/control.bareos-director-python2-plugin
  debian/control.bareos-director-python3-plugin
  debian/control.bareos-filedaemon-python2-plugin
  debian/control.bareos-filedaemon-python3-plugin
  debian/control.bareos-storage-python2-plugin
  debian/control.bareos-storage-python3-plugin
Labels: requires backport to 20, requires backport to 21

#1062 git: set merge strategy for `CHANGELOG.md` to `union`
  .gitattributes
  CHANGELOG.md
Labels: nobuild

#1043 ndmp: introduce workaround for isilon 9.1.0.0 'Invalid nlist.tape_offset -1' error
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/dird/dird_conf.h
  core/src/dird/ndmp_dma_restore_NDMP_BAREOS.cc
  core/src/dird/ndmp_dma_restore_common.cc
  core/src/dird/ndmp_dma_restore_common.h
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  docs/manuals/source/manually_added_config_directive_descriptions/dir-director-NdmpNamelistFhinfoSetZeroForInvalidUquad.rst.inc
  systemtests/tests/config-dump/etc/bareos/bareos-dir-full.conf.in
Labels: requires backport to 20, requires backport to 21

#1049 ndmp: introduce workaround for isilon 9.1.0.0 'Invalid nlist.tape_offset -1' error
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/dird/dird_conf.h
  core/src/dird/ndmp_dma_restore_NDMP_BAREOS.cc
  core/src/dird/ndmp_dma_restore_common.cc
  core/src/dird/ndmp_dma_restore_common.h
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  docs/manuals/source/manually_added_config_directive_descriptions/dir-director-NdmpNamelistFhinfoSetZeroForInvalidUquad.rst.inc
  systemtests/tests/config-dump/etc/bareos/bareos-dir-full.conf.in
Labels: is a backport to 21

#1058 ndmp: introduce workaround for isilon 9.1.0.0 'Invalid nlist.tape_offset -1' error
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/dird/dird_conf.h
  core/src/dird/ndmp_dma_restore_NDMP_BAREOS.cc
  core/src/dird/ndmp_dma_restore_common.cc
  core/src/dird/ndmp_dma_restore_common.h
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  docs/manuals/source/manually_added_config_directive_descriptions/dir-director-NdmpNamelistFhinfoSetZeroForInvalidUquad.rst.inc
  systemtests/tests/config-dump/etc/bareos/bareos-dir-full.conf.in
Labels: is a backport to 20

#1061 debian: add missing python plugin dependencies
  CHANGELOG.md
  debian/control.bareos-director-python2-plugin
  debian/control.bareos-director-python3-plugin
  debian/control.bareos-filedaemon-python2-plugin
  debian/control.bareos-filedaemon-python3-plugin
  debian/control.bareos-storage-python2-plugin
  debian/control.bareos-storage-python3-plugin
Labels: is a backport to 20

#1064 stored: enable labeling of tapes in devices even when `autoselect = no`
  CHANGELOG.md
  core/src/stored/dir_cmd.cc
Labels: is a backport to 20

#1071 PR template: require Backport information on top
  pull_request_template.md
Labels: nobuild

#1047 Fix context issue in bareos-dir python plugin
  CHANGELOG.md
  core/src/plugins/dird/python/module/bareosdir.h
  core/src/plugins/dird/python/python-dir.cc
  systemtests/tests/py2plug-dir/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/py2plug-dir/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf.in
  systemtests/tests/py2plug-dir/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/py2plug-dir/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/py2plug-dir/python-modules/BareosDirTest.py
  systemtests/tests/py2plug-dir/testrunner
Labels: requires backport to 20, requires backport to 21

#1079 doc improve python action plugin example removing File = in Fileset
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/PythonFdPlugin.rst.inc
Labels: requires backport to 21

#1080 doc improve python action plugin example removing File = in Fileset
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/PythonFdPlugin.rst.inc
Labels: is a backport to 21

#1077 Fix context issue in bareos-dir python plugin
  CHANGELOG.md
  core/src/plugins/dird/python/module/bareosdir.h
  core/src/plugins/dird/python/python-dir.cc
  systemtests/tests/py2plug-dir/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/py2plug-dir/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf.in
  systemtests/tests/py2plug-dir/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/py2plug-dir/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/py2plug-dir/python-modules/BareosDirTest.py
  systemtests/tests/py2plug-dir/testrunner
Labels: is a backport to 20
