Repository bareos/bareos, pull requests merged in 2022-07, with the labels that each got.

#1192 Build MacOS packages via Github Actions
  .github/workflows/build-macos.yml
  CHANGELOG.md
Labels: nobuild

#1200 docs: Fix broken links with sphinx linkchecker
  CHANGELOG.md
  docs/manuals/CMakeLists.txt
  docs/manuals/source/Appendix/OperatingSystems.rst
  docs/manuals/source/Appendix/ReleaseNotes.rst
  docs/manuals/source/DeveloperGuide/BuildAndTestBareos/HintsForBuildingBareos.rst
  docs/manuals/source/DeveloperGuide/PythonBareos.rst
  docs/manuals/source/DeveloperGuide/api.rst
  docs/manuals/source/DeveloperGuide/generaldevel.rst
  docs/manuals/source/DeveloperGuide/gitworkflow.rst
  docs/manuals/source/DeveloperGuide/tests.rst
  docs/manuals/source/DocumentationStyleGuide/BareosSpecificFormatting/Issue.rst
  docs/manuals/source/DocumentationStyleGuide/Gotchas.rst
  docs/manuals/source/DocumentationStyleGuide/RestOverview.rst
  docs/manuals/source/IntroductionAndTutorial/InstallingBareos.rst
  docs/manuals/source/IntroductionAndTutorial/WhatIsBareos.rst
  docs/manuals/source/TasksAndConcepts/AutochangerSupport.rst
  docs/manuals/source/TasksAndConcepts/CatalogMaintenance.rst
  docs/manuals/source/TasksAndConcepts/NdmpBackupsWithBareos.rst
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/OVirtPlugin.rst.inc
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/PerconaXtraBackupPlugin.rst.inc
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
  docs/manuals/source/TasksAndConcepts/StorageBackends.rst
  docs/manuals/source/TasksAndConcepts/TheWindowsVersionOfBareos.rst
  docs/manuals/source/TasksAndConcepts/TransportEncryption.rst
  docs/manuals/source/conf.py
Labels: documentation

#1201 SQL: queries: fix to handle negative job duration value (backport 1198)
  CHANGELOG.md
  core/src/cats/dml/0006_list_jobs
  core/src/cats/dml/0007_list_jobs_long
  core/src/cats/dml/0009_list_jobs_last
  core/src/cats/dml/0010_list_jobs_long_last
  core/src/cats/mysql_queries.inc
  core/src/cats/postgresql_queries.inc
  core/src/cats/sqlite_queries.inc
Labels: is a backport to 21

#1205 build: add support for SLE15SP4
  .matrix.yml
  CHANGELOG.md
  core/platforms/packaging/bareos.spec
  debian/control
  debian/control.src
  docs/pkglists/SLE_15_SP4.x86_64
Labels: requires backport to 21

#1207 build: Add support for SLE_15_SP4 [PR #1205]
  .matrix.yml
  CHANGELOG.md
  core/platforms/packaging/bareos.spec
  debian/control
  debian/control.src
  docs/pkglists/SLE_15_SP4.x86_64
Labels: is a backport to 21

#1204 dird: fix tls psk connection failure with long job names
  CHANGELOG.md
  core/src/dird/job.cc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-job-Name.rst.inc
  systemtests/tests/bareos/etc/bareos/bareos-dir.d/job/long-name-backup.conf
  systemtests/tests/bareos/testrunner-very-long-job-names
Labels: requires backport to 21

#1208 backport #1204 dird fix tls psk crendential not found
  CHANGELOG.md
  core/src/dird/job.cc
  systemtests/tests/bareos/etc/bareos/bareos-dir.d/job/long-name-backup.conf
  systemtests/tests/bareos/testrunner-very-long-job-names
Labels: is a backport to 21
