Repository bareos/bareos, pull requests merged in 2022-10, with the labels that each got.

#1263 dird: fix tls reload crash
  CHANGELOG.md
  core/src/dird/dird.cc
  core/src/lib/parse_conf.cc
  core/src/lib/parse_conf.h
  core/src/lib/tls_openssl.cc
  core/src/lib/tls_openssl.h
  core/src/lib/tls_openssl_private.cc
  core/src/lib/tls_openssl_private.h
  core/src/tests/test_config_parser_dir.cc
Labels: is a backport to 21

#1278 dird: fix crash in .jobstatus
  CHANGELOG.md
  core/src/dird/ua_dotcmds.cc
  systemtests/tests/bconsole/testrunner-dotjobstatus
Labels: requires backport to 21

#1286 dird: fix crash in .jobstatus
  CHANGELOG.md
  core/src/dird/ua_dotcmds.cc
  systemtests/tests/bconsole/testrunner-dotjobstatus
Labels: is a backport to 21

#1291 Adapt VMware plugin documentation for update to VDDK 8
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: is a backport to 21, documentation

#1292 Adapt VMware plugin documentation for update to VDDK 8
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/Plugins.rst
Labels: is a backport to 20, documentation

#1288 winbareos.nsi: fix working directory in configure.sed
  CHANGELOG.md
  core/platforms/win32/winbareos.nsi
Labels: requires backport to 20, requires backport to 21

#1289 winbareos.nsi: fix working directory in configure.sed
  CHANGELOG.md
  core/platforms/win32/winbareos.nsi
Labels: is a backport to 21

#1290 winbareos.nsi: fix working directory in configure.sed
  .matrix.yml
  CHANGELOG.md
  core/platforms/win32/winbareos.nsi
Labels: is a backport to 20
