Repository bareos/bareos, pull requests merged in 2022-08, with the labels that each got.

#1181 doc: Add Security FIPS section
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
Labels: requires backport to 21, documentation

#1212 doc add section fips mode in security
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
Labels: is a backport to 21, documentation

#1214 Refactor config reloading by using shared pointers instead of callbacks
  CHANGELOG.md
  core/src/console/console_conf.cc
  core/src/console/console_conf.h
  core/src/dird/dird.cc
  core/src/dird/dird_conf.cc
  core/src/dird/dird_conf.h
  core/src/dird/jcr_private.h
  core/src/dird/job.cc
  core/src/dird/ua_output.cc
  core/src/dird/ua_server.cc
  core/src/dird/ua_status.cc
  core/src/filed/filed_conf.cc
  core/src/filed/filed_conf.h
  core/src/lib/parse_conf.cc
  core/src/lib/parse_conf.h
  core/src/lib/parse_conf_init_resource.cc
  core/src/lib/parse_conf_state_machine.cc
  core/src/lib/res.cc
  core/src/lib/util.cc
  core/src/lib/util.h
  core/src/qt-tray-monitor/tray_conf.cc
  core/src/qt-tray-monitor/tray_conf.h
  core/src/stored/stored_conf.cc
  core/src/stored/stored_conf.h
  core/src/tests/setdevice.cc
  core/src/tests/show_cmd_available_resources_equals_config_resources.cc
  core/src/tests/test_config_parser_dir.cc
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-fd-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-sd-config-schema.json
  systemtests/tests/always-incremental-consolidate/testrunner
  systemtests/tests/reload/reload_test_functions
Labels: is a backport to 21

#1151 Refactor config reloading by using shared pointers instead of callbacks
  CHANGELOG.md
  core/src/console/console_conf.cc
  core/src/console/console_conf.h
  core/src/dird/dird.cc
  core/src/dird/dird_conf.cc
  core/src/dird/dird_conf.h
  core/src/dird/jcr_private.h
  core/src/dird/job.cc
  core/src/dird/ua_output.cc
  core/src/dird/ua_server.cc
  core/src/dird/ua_status.cc
  core/src/filed/filed_conf.cc
  core/src/filed/filed_conf.h
  core/src/lib/parse_conf.cc
  core/src/lib/parse_conf.h
  core/src/lib/parse_conf_init_resource.cc
  core/src/lib/parse_conf_state_machine.cc
  core/src/lib/res.cc
  core/src/lib/util.cc
  core/src/lib/util.h
  core/src/qt-tray-monitor/tray_conf.cc
  core/src/qt-tray-monitor/tray_conf.h
  core/src/stored/stored_conf.cc
  core/src/stored/stored_conf.h
  core/src/tests/setdevice.cc
  core/src/tests/show_cmd_available_resources_equals_config_resources.cc
  core/src/tests/test_config_parser_dir.cc
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-fd-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-sd-config-schema.json
  systemtests/tests/always-incremental-consolidate/testrunner
  systemtests/tests/commandline-options/testrunner
  systemtests/tests/reload/reload_test_functions
Labels: requires backport to 21

#1221 devtools/dist-tarball.sh: create correct source name
  CHANGELOG.md
  devtools/dist-tarball.sh
Labels: is forward port to master

#1222 Fix output of show command for RunScripts
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/dird/ua_cmds.cc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-job-RunScript.rst.inc
  systemtests/python-modules/bareos_unittest/json.py
  systemtests/tests/config-dump/etc/bareos/bareos-dir-full.conf.in
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/job/admin-runscript-console-server-defaults.conf
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/job/admin-runscript-console-server-invalid.conf
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/job/admin-runscript-console-server.conf
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/job/backup-bareos-fd-runscript-console-client.conf.in
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/job/backup-bareos-fd-runscript-console-server.conf
  systemtests/tests/python-bareos/list_unittests.py
  systemtests/tests/python-bareos/run_unittests.sh
  systemtests/tests/python-bareos/test_runscript.py
Labels: is a backport to 21

#1210 dird: fix odd-even weeks parsing bug in schedule
  CHANGELOG.md
  core/src/dird/run_conf.cc
  core/src/tests/configs/bareos-configparser-tests/bareos-dir.d/schedule/EvenWeeks.conf
  core/src/tests/configs/bareos-configparser-tests/bareos-dir.d/schedule/OddWeeks.conf
  core/src/tests/test_config_parser_dir.cc
Labels: requires backport to 21

#1227 docs: FreeBSD create dir before use
  CHANGELOG.md
  docs/manuals/source/IntroductionAndTutorial/InstallingBareos.rst
Labels: requires backport to 21, documentation

#1223 Build MacOS packages via Github Actions
  .github/workflows/build-macos.yml
  CHANGELOG.md
Labels: is a backport to 21

#1229 docs: add example to selection type = sql query
  CHANGELOG.md
  docs/manuals/source/include/config/DirSelectionPatterns-sql1.conf
  docs/manuals/source/manually_added_config_directive_descriptions/dir-job-SelectionPattern.rst.inc
Labels: requires backport to 21, documentation

#1225 docs: fix default dir job reschedule times
  CHANGELOG.md
  docs/manuals/source/manually_added_config_directive_descriptions/dir-job-RescheduleTimes.rst.inc
Labels: requires backport to 21, documentation

#1232 dird: fix odd even weeks parsing bug in schedule [Backport 1210]
  CHANGELOG.md
  core/src/dird/run_conf.cc
  core/src/tests/configs/bareos-configparser-tests/bareos-dir.d/schedule/EvenWeeks.conf
  core/src/tests/configs/bareos-configparser-tests/bareos-dir.d/schedule/OddWeeks.conf
  core/src/tests/test_config_parser_dir.cc
Labels: is a backport to 21

#1241 github actions: remove build MacOS package
  .github/workflows/build-macos.yml
  CHANGELOG.md
Labels: is a backport to 21

#1237 core:platform Add Bareos firewalld services
  CHANGELOG.md
  core/platforms/firewalld/README.md
  core/platforms/firewalld/bareos-director.xml
  core/platforms/firewalld/bareos-filedaemon.xml
  core/platforms/firewalld/bareos-storage.xml
Labels: nobuild

#1231 docs: update appendix hardware db sizing
  CHANGELOG.md
  docs/manuals/source/Appendix/HardwareSizing.rst
Labels: requires backport to 21, documentation

#1230 docs: add description to fileset signature sha256 and sha512
  CHANGELOG.md
  docs/manuals/source/Configuration/Director.rst
  docs/manuals/source/IntroductionAndTutorial/WhatIsBareos.rst
Labels: requires backport to 21, documentation

#1233 docs: troubleshooting & debugging chapter improvements
  CHANGELOG.md
  docs/manuals/source/Appendix/Debugging.rst
  docs/manuals/source/Appendix/Troubleshooting.rst
Labels: requires backport to 21, documentation

#1235 docs: mssql: after PITR restore, a full backup is required
  CHANGELOG.md
  docs/manuals/source/Appendix/Howtos/BackupOfThirdPartyDatabases.rst.inc
Labels: requires backport to 21, documentation

#1242 docs: replace UCS chapter
  .gitignore
  CHANGELOG.md
  core/platforms/univention/AppCenter/LICENSE_AGREEMENT
  core/platforms/univention/AppCenter/README
  core/platforms/univention/AppCenter/README_DE
  core/platforms/univention/AppCenter/bareos-webui_screenshot.png
  core/platforms/univention/AppCenter/univention-bareos.ini.in
  core/platforms/univention/CMakeLists.txt
  debian/univention-bareos.docs
  docs/manuals/source/Appendix/OperatingSystems.rst
  docs/manuals/source/include/images/univention-client-job-activation.png
  docs/manuals/source/include/images/univention-configuration-registry-settings.png
  docs/manuals/source/include/images/univention-ucs-overview-administration.png
  webui/tests/selenium/webui-selenium-test.py
Labels: requires backport to 21
