Repository bareos/bareos, pull requests merged in 2022-04, with the labels that each got.

#1148 FreeBSD fix missing ddl update files backport
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.database-postgresql
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/plist
  core/platforms/freebsd/bareos-freebsd/bareos.com-director/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-filedaemon/Makefile.orig
Labels: is a backport to 21

#1147 FreeBSD fix missing ddl update files for 2171_2192 and 2192_2210 database migration.
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.database-postgresql
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/plist
  core/platforms/freebsd/bareos-freebsd/bareos.com-director/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-filedaemon/Makefile.orig
Labels: requires backport to 21

#1138 fix caching during bvfs_update
  CHANGELOG.md
  core/src/cats/bvfs.cc
Labels: requires backport to 21

#1146 fix caching during bvfs_update
  CHANGELOG.md
  core/src/cats/bvfs.cc
Labels: is a backport to 21

#1134 Qmsg: in case of syslog logging use adapted log priority instead of always LOG_ERR
  CHANGELOG.md
  core/src/lib/message.cc
Labels: requires backport to 21

#1150 Qmsg: in case of syslog logging use adapted log priority instead of always LOG_ERR
  CHANGELOG.md
  core/src/lib/message.cc
Labels: is a backport to 21

#1155 webui: update moment.js to version 2.29.2
  CHANGELOG.md
  webui/public/js/moment-timezone-with-data.js
  webui/public/js/moment-timezone-with-data.min.js
  webui/public/js/moment-with-locales.js
  webui/public/js/moment-with-locales.min.js
  webui/public/js/moment.js
  webui/public/js/moment.min.js
Labels: requires backport to 20, requires backport to 19.2, requires backport to 21

#1156 webui: update moment.js to version 2.29.2
  CHANGELOG.md
  webui/public/js/moment-timezone-with-data.js
  webui/public/js/moment-timezone-with-data.min.js
  webui/public/js/moment-with-locales.js
  webui/public/js/moment-with-locales.min.js
  webui/public/js/moment.js
  webui/public/js/moment.min.js
Labels: is a backport to 21

#1157 webui: update moment.js to version 2.29.2
  CHANGELOG.md
  webui/public/js/moment-timezone-with-data.js
  webui/public/js/moment-timezone-with-data.min.js
  webui/public/js/moment-with-locales.js
  webui/public/js/moment-with-locales.min.js
  webui/public/js/moment.js
  webui/public/js/moment.min.js
Labels: is a backport to 20

#1158 webui: update moment.js to version 2.29.2
  CHANGELOG.md
  webui/public/js/moment-timezone-with-data.js
  webui/public/js/moment-timezone-with-data.min.js
  webui/public/js/moment-with-locales.js
  webui/public/js/moment-with-locales.min.js
  webui/public/js/moment.js
  webui/public/js/moment.min.js
Labels: is a backport to 19.2

#1165 doc: fix PythonPlugin gh link (bug1450)
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/PythonFdPlugin.rst.inc
Labels: documentation

#1164 Cats: make bvfs_update take archive jobs into consideration
  CHANGELOG.md
  core/src/cats/bvfs.cc
Labels: is a backport to 21

#1167 doc: bug 1450 fix python plugin gh link
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/PythonFdPlugin.rst.inc
Labels: is a backport to 21, documentation

#1172 cats: BareosDb: FilterZeroFileJobs returned list now is sorted
  CHANGELOG.md
  core/src/cats/sql_get.cc
Labels: requires backport to 21

#1173 dird: missing quotes around name when using configure export
  CHANGELOG.md
  core/src/dird/ua_configure.cc
Labels: is a backport to 21

#1159 fix miscalculation when using Always Incremental Keep Number
  CHANGELOG.md
  core/src/cats/cats.h
  core/src/dird/consolidate.cc
Labels: requires backport to 21

#1175 cats: BareosDb: FilterZeroFileJobs returned list now is sorted
  CHANGELOG.md
  core/src/cats/sql_get.cc
  systemtests/scripts/functions
  systemtests/tests/CMakeLists.txt
  systemtests/tests/always-incremental-consolidate/CMakeLists.txt
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/console/bareos-mon.conf.in
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/job/BackupCatalog.conf.in
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/job/Consolidate.conf
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf.in
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/job/virtualfull.conf.in
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/pool/AI-Consolidated.conf
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/pool/AI-Incremental.conf
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/pool/AI-Longterm.conf
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-fd.d/director/bareos-mon.conf.in
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-sd.d/director/bareos-mon.conf.in
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/always-incremental-consolidate/etc/bareos/bconsole.conf.in
  systemtests/tests/always-incremental-consolidate/testrunner
Labels: is a backport to 21
