Repository bareos/bareos, pull requests merged in 2022-09, with the labels that each got.

#1202 Docs: Added Developer FAQ section with first question.
  CHANGELOG.md
  docs/manuals/source/DeveloperGuide.rst
  docs/manuals/source/DeveloperGuide/developerFAQ.rst
  docs/manuals/source/DeveloperGuide/generaldevel.rst
  docs/manuals/source/conf.py
Labels: documentation

#1243 Update Pull Request template: handling CHANGELOG.md
  CHANGELOG.md
  SECURITY.md
  docs/manuals/source/DeveloperGuide/ReleasingBareos.rst
  docs/manuals/source/DeveloperGuide/generaldevel.rst
  docs/manuals/source/DeveloperGuide/gitworkflow.rst
  pull_request_template.md
Labels: requires backport to 21, documentation

#1254 docs: improve operating system table
  CHANGELOG.md
  docs/manuals/source/Appendix/OperatingSystems.rst
Labels: requires backport to 21, documentation

#1253 build: switch from FreeBSD 13.0 to 13.1
  .matrix.yml
  CHANGELOG.md
  core/CMakeLists.txt
  core/src/dird/CMakeLists.txt
  core/src/ndmp/CMakeLists.txt
Labels: requires backport to 20, requires backport to 19.2, requires backport to 21

#1257 build: switch from FreeBSD 13.0 to 13.1
  .matrix.yml
  CHANGELOG.md
  core/CMakeLists.txt
  core/src/dird/CMakeLists.txt
  core/src/ndmp/CMakeLists.txt
Labels: is a backport to 19.2

#1256 build: switch from FreeBSD 13.0 to 13.1
  .matrix.yml
  CHANGELOG.md
  core/CMakeLists.txt
  core/src/dird/CMakeLists.txt
  core/src/ndmp/CMakeLists.txt
Labels: is a backport to 21

#1258 build: switch from FreeBSD 13.0 to 13.1
  .matrix.yml
  .quality-gates.yml
  CHANGELOG.md
  core/CMakeLists.txt
  core/src/dird/CMakeLists.txt
  core/src/ndmp/CMakeLists.txt
Labels: is a backport to 20

#1259 Documentation: update PR handling hints
  CHANGELOG.md
  SECURITY.md
  docs/manuals/source/DeveloperGuide/ReleasingBareos.rst
  docs/manuals/source/DeveloperGuide/generaldevel.rst
  docs/manuals/source/DeveloperGuide/gitworkflow.rst
  pull_request_template.md
Labels: is a backport to 21

#1260 docs: add FAQ entry about howto upgrade from Bareos < 20 with Bareos Python packages installed
  CHANGELOG.md
  docs/manuals/source/Appendix/FAQ.rst
Labels: documentation

#1248 docs: usage of the add_bareos_repositories.sh script
  CHANGELOG.md
  docs/manuals/source/Appendix/OperatingSystems.rst
  docs/manuals/source/DocumentationStyleGuide/CommonNames.rst
  docs/manuals/source/IntroductionAndTutorial.rst
  docs/manuals/source/IntroductionAndTutorial/InstallingBareos.rst
  docs/manuals/source/IntroductionAndTutorial/InstallingBareosClient.rst
  docs/manuals/source/TasksAndConcepts/CatalogMaintenance.rst
  docs/manuals/source/TasksAndConcepts/TheWindowsVersionOfBareos.rst
Labels: documentation, jenkins_repotest_nodebug

#1255 docs: Appendix/Bareos Programs improvements
  CHANGELOG.md
  docs/manuals/CMakeLists.txt
  docs/manuals/source/Appendix/BareosPrograms.rst
  docs/manuals/source/DeveloperGuide/mediaformat.rst
  docs/manuals/source/include/autogenerated/usage/bsmtp.txt
  docs/manuals/source/man/bareos-dbcopy.rst
Labels: documentation

#1268 docs: obsolete comments removed
  CHANGELOG.md
  docs/manuals/source/Appendix/OperatingSystems.rst
  docs/manuals/source/IntroductionAndTutorial/InstallingBareosClient.rst
Labels: documentation
