Repository bareos/bareos, pull requests merged in 2023-08, with the labels that each got.

#1503 stored: fix blocksize warning
  CHANGELOG.md
  core/src/console/console_conf.cc
  core/src/dird/dird_conf.cc
  core/src/dird/inc_conf.cc
  core/src/dird/run_conf.cc
  core/src/filed/filed_conf.cc
  core/src/lib/bareos_resource.cc
  core/src/lib/bareos_resource.h
  core/src/lib/jcr.cc
  core/src/lib/res.cc
  core/src/lib/resource_item.h
  core/src/qt-tray-monitor/tray_conf.cc
  core/src/stored/dev.cc
  core/src/stored/device_resource.cc
  core/src/stored/device_resource.h
  core/src/stored/stored_conf.cc
Labels: bugfix

#1476 status storage: fix wrong data displayed about waiting jobs
  CHANGELOG.md
  core/src/dird/backup.cc
  core/src/dird/migrate.cc
  core/src/dird/restore.cc
  core/src/dird/verify.cc
  core/src/include/jcr.h
  core/src/lib/jcr.cc
  core/src/lib/util.cc
  core/src/lib/util.h
  core/src/stored/ansi_label.cc
  core/src/stored/reserve.cc
  core/src/stored/status.cc
Labels: bugfix

#1487 dird: show current and allowed console connections
  CHANGELOG.md
  core/src/dird/CMakeLists.txt
  core/src/dird/authenticate_console.cc
  core/src/dird/console_connection_lease.cc
  core/src/dird/console_connection_lease.h
  core/src/dird/ua_server.cc
Labels: requires backport to 22

#1499 dird: add prev and new jobid variables
  AUTHORS
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/dird/dird_conf.h
  core/src/filed/dir_cmd.cc
  core/src/filed/fileset.cc
  core/src/filed/fileset.h
  core/src/lib/message.h
  core/src/lib/util.cc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-job-RunScript.rst.inc
  systemtests/tests/copy-migrate/etc/bareos/bareos-dir.d/job/copy.conf
  systemtests/tests/copy-migrate/etc/bareos/bareos-dir.d/job/migrate.conf
  systemtests/tests/copy-migrate/testrunner-02-copy
  systemtests/tests/copy-migrate/testrunner-05-migrate
Labels: enhancement, requires backport to 22

#1517 dird: show current and allowed console connections
  CHANGELOG.md
  core/src/dird/CMakeLists.txt
  core/src/dird/authenticate_console.cc
  core/src/dird/console_connection_lease.cc
  core/src/dird/console_connection_lease.h
  core/src/dird/ua_server.cc
Labels: is a backport to 22

#1514 stored: fix incoherent meta data when concurrently writing to the same volume
  CHANGELOG.md
  core/src/cats/cats.h
  core/src/cats/sql_delete.cc
  core/src/dird/catreq.cc
  core/src/stored/acquire.cc
  core/src/stored/append.cc
  core/src/stored/askdir.cc
  core/src/stored/askdir.h
  core/src/stored/block.cc
  core/src/stored/label.cc
  systemtests/scripts/diff.pl.in
  systemtests/tests/block-size/testrunner
  systemtests/tests/parallel-jobs/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/parallel-jobs/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/parallel-jobs/etc/bareos/bareos-sd.d/device/FileStorage2.conf
  systemtests/tests/parallel-jobs/testrunner-parallel-jobs
Labels: bugfix, is a backport to 22

#1519 backport fixes fastlz: remove unaligned memory accesses
  CHANGELOG.md
  core/src/fastlz/src/lz4.c
  core/src/lib/compression.cc
  systemtests/tests/bareos-basic/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/bareos-basic/etc/bareos/bareos-sd.d/device/FileStorage2.conf
  systemtests/tests/parallel-jobs/testrunner-parallel-jobs
Labels: is a backport to 22

#1511 dird: fix expected file count error during bsr build
  CHANGELOG.md
  core/src/dird/bsr.cc
  core/src/dird/bsr.h
  core/src/dird/ua_restore.cc
  core/src/dird/ua_tree.cc
  core/src/tests/test_fileindex_list.cc
  systemtests/tests/CMakeLists.txt
  systemtests/tests/file-count-regression/CMakeLists.txt
  systemtests/tests/file-count-regression/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/file-count-regression/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/file-count-regression/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/file-count-regression/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/file-count-regression/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/file-count-regression/etc/bareos/bareos-dir.d/job/BackupCatalog.conf.in
  systemtests/tests/file-count-regression/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/file-count-regression/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/file-count-regression/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/file-count-regression/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/file-count-regression/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/file-count-regression/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/file-count-regression/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/file-count-regression/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/file-count-regression/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/file-count-regression/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/file-count-regression/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/file-count-regression/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/file-count-regression/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/file-count-regression/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/file-count-regression/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/file-count-regression/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/file-count-regression/etc/bareos/bconsole.conf.in
  systemtests/tests/file-count-regression/functions
  systemtests/tests/file-count-regression/test-setup
  systemtests/tests/file-count-regression/testrunner-check-regression
Labels: bugfix

#1464 stored: add AccessMode SD->Device directive to reserve devices exclusively for reading or writing
  CHANGELOG.md
  core/src/plugins/stored/autoxflate/autoxflate-sd.cc
  core/src/stored/dev.cc
  core/src/stored/dev.h
  core/src/stored/device_control_record.h
  core/src/stored/device_resource.cc
  core/src/stored/device_resource.h
  core/src/stored/io_direction.h
  core/src/stored/mac.cc
  core/src/stored/reserve.cc
  core/src/stored/stored_conf.cc
  core/src/tests/configs/sd_reservation/bareos-sd.d/device/readonly1.conf
  core/src/tests/configs/sd_reservation/bareos-sd.d/device/readonly2.conf
  core/src/tests/configs/sd_reservation/bareos-sd.d/device/writeonly1.conf
  core/src/tests/configs/sd_reservation/bareos-sd.d/device/writeonly2.conf
  core/src/tests/sd_reservation.cc
  docs/manuals/source/Configuration/CustomizingTheConfiguration.rst
  docs/manuals/source/include/autogenerated/bareos-sd-config-schema.json
  docs/manuals/source/manually_added_config_directive_descriptions/sd-device-AccessMode.rst.inc
Labels: enhancement

#1518 dird: add prev and new jobid variables
  AUTHORS
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/dird/dird_conf.h
  core/src/filed/dir_cmd.cc
  core/src/filed/fileset.cc
  core/src/filed/fileset.h
  core/src/lib/message.h
  core/src/lib/util.cc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-job-RunScript.rst.inc
  systemtests/tests/copy-migrate/etc/bareos/bareos-dir.d/job/copy.conf
  systemtests/tests/copy-migrate/etc/bareos/bareos-dir.d/job/migrate.conf
  systemtests/tests/copy-migrate/testrunner-02-copy
  systemtests/tests/copy-migrate/testrunner-05-migrate
Labels: enhancement, is a backport to 22

#1524 build: switch from FreeBSD 13.1 to 13.2
  .matrix.yml
  CHANGELOG.md
  systemtests/tests/bconsole-basic/testrunner-autocompletion
Labels: requires backport to 20, requires backport to 21, requires backport to 22

#1525 build: switch from FreeBSD 13.1 to 13.2
  .matrix.yml
  CHANGELOG.md
  systemtests/tests/bconsole-basic/testrunner-autocompletion
Labels: is a backport to 22

#1528 build: switch from FreeBSD 13.1 to 13.2
  .matrix.yml
  CHANGELOG.md
  systemtests/tests/bconsole-basic/testrunner-autocompletion
Labels: is a backport to 21

#1527 build: switch from FreeBSD 13.1 to 13.2
  .matrix.yml
  CHANGELOG.md
Labels: is a backport to 20

#1496 stored: automatically increment tape block size in case the buffer is too small
  CHANGELOG.md
  core/src/stored/backends/unix_tape_device.cc
  core/src/stored/backends/unix_tape_device.h
  core/src/stored/block.cc
  devtools/dist-tarball.sh
Labels: enhancement
