Repository bareos/bareos, pull requests merged in 2023-02, with the labels that each got.

#1348 stored: fix crashes of storage tools when autoxflate plugin is loaded
  CHANGELOG.md
  core/src/plugins/stored/autoxflate/autoxflate-sd.cc
  core/src/stored/bcopy.cc
  core/src/stored/bextract.cc
  core/src/stored/bls.cc
  core/src/stored/bscan.cc
  core/src/stored/btape.cc
  core/src/stored/read_record.cc
  systemtests/scripts/cleanup
  systemtests/tests/bareos-basic/CMakeLists.txt
  systemtests/tests/bareos-basic/etc/bareos/bareos-sd.d/device/FileStorage2.conf
  systemtests/tests/bareos-basic/testrunner-bcopy-autoxflate
  systemtests/tests/bareos-basic/testrunner-bextract-autoxflate
  systemtests/tests/bareos-basic/testrunner-bls-autoxflate
  systemtests/tests/bareos-basic/testrunner-bscan-autoxflate
  systemtests/tests/bareos-basic/testrunner-simple-backup-and-restore
Labels: bugfix, requires backport to 21, requires backport to 22

#1368 webui: enable sorting on version column
  CHANGELOG.md
  webui/module/Client/src/Client/Controller/ClientController.php
  webui/module/Client/view/client/client/index.phtml
  webui/public/js/bootstrap-table-formatter.js
  webui/public/js/bootstrap-table-sort.js
Labels: is a backport to 22

#1365 webui: enable sorting on version column
  CHANGELOG.md
  webui/module/Client/src/Client/Controller/ClientController.php
  webui/module/Client/view/client/client/index.phtml
  webui/public/js/bootstrap-table-formatter.js
  webui/public/js/bootstrap-table-sort.js
Labels: requires backport to 22

#1369 stored: fix crashes of storage tools when autoxflate plugin is loaded
  CHANGELOG.md
  core/src/plugins/stored/autoxflate/autoxflate-sd.cc
  core/src/stored/bcopy.cc
  core/src/stored/bextract.cc
  core/src/stored/bls.cc
  core/src/stored/bscan.cc
  core/src/stored/btape.cc
  core/src/stored/read_record.cc
  systemtests/scripts/cleanup
  systemtests/tests/bareos-basic/CMakeLists.txt
  systemtests/tests/bareos-basic/etc/bareos/bareos-sd.d/device/FileStorage2.conf
  systemtests/tests/bareos-basic/testrunner-bcopy-autoxflate
  systemtests/tests/bareos-basic/testrunner-bextract-autoxflate
  systemtests/tests/bareos-basic/testrunner-bls-autoxflate
  systemtests/tests/bareos-basic/testrunner-bscan-autoxflate
  systemtests/tests/bareos-basic/testrunner-simple-backup-and-restore
Labels: bugfix, is a backport to 22

#1366 docs: improve bareos-webui documentation
  CHANGELOG.md
  docs/manuals/source/IntroductionAndTutorial.rst
  docs/manuals/source/IntroductionAndTutorial/BareosWebui.rst
  docs/manuals/source/IntroductionAndTutorial/InstallingBareosWebui.rst
  docs/manuals/source/IntroductionAndTutorial/WhatIsBareos.rst
  docs/manuals/source/TasksAndConcepts/TransportEncryption.rst
Labels: documentation, requires backport to 22

#1316 bsmtp: fix and update code, and change CLI parsing to CLI11
  CHANGELOG.md
  core/src/tools/CMakeLists.txt
  core/src/tools/bsmtp.cc
  docs/manuals/CMakeLists.txt
  docs/manuals/source/include/autogenerated/usage/bsmtp.txt
Labels: requires backport to 22

#1376 bsmtp: fix and update code change cli parsing to cli11
  CHANGELOG.md
  core/src/tools/CMakeLists.txt
  core/src/tools/bsmtp.cc
  docs/manuals/CMakeLists.txt
  docs/manuals/source/include/autogenerated/usage/bsmtp.txt
Labels: is a backport to 22

#1373 filed: avoid reading from ephemeral buffer
  CHANGELOG.md
  core/src/filed/dir_cmd.cc
  core/src/plugins/filed/python/pyfiles/BareosFdWrapper.py
  systemtests/tests/CMakeLists.txt
  systemtests/tests/py3plug-fd-basic/CMakeLists.txt
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/PluginTest.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bconsole.conf.in
  systemtests/tests/py3plug-fd-basic/jobmsg-backup.txt
  systemtests/tests/py3plug-fd-basic/jobmsg-restore.txt
  systemtests/tests/py3plug-fd-basic/python-modules/jobmsg-module.py
  systemtests/tests/py3plug-fd-basic/test-setup
  systemtests/tests/py3plug-fd-basic/testrunner-jobmsg
Labels: bugfix, requires backport to 21, requires backport to 22

#1387 restore: fix failed restores showing Restore ok with warning
  CHANGELOG.md
  core/src/dird/restore.cc
Labels: requires backport to 22

#1388 restore: fix failed restores showing `Restore ok with warning`
  CHANGELOG.md
  core/src/dird/restore.cc
Labels: is a backport to 22

#1336 FreeBSD: build cleanup
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-bconsole/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/BareosCommonMakefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/BareosPackageOnlyMakefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-database-common/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-database-postgresql/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-database-tools/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-director/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-filedaemon-python-plugins-common/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-filedaemon-python3-plugin/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-filedaemon/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-storage-tape/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-storage/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-tools/Makefile
  systemtests/tests/notls/testrunner
Labels: requires backport to 20, requires backport to 21, jenkins_repotest_nodebug, requires backport to 22

#1380 FreeBSD: build cleanup
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-bconsole/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/BareosCommonMakefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/BareosPackageOnlyMakefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-database-common/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-database-postgresql/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-database-tools/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-director/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-filedaemon-python-plugins-common/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-filedaemon-python3-plugin/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-filedaemon/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-storage-tape/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-storage/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-tools/Makefile
  systemtests/tests/notls/testrunner
Labels: jenkins_repotest_nodebug, is a backport to 22

#1381 FreeBSD: build cleanup
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-bconsole/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/BareosCommonMakefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/BareosPackageOnlyMakefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-database-common/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-database-postgresql/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-database-tools/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-director/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-filedaemon-python-plugins-common/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-filedaemon-python3-plugin/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-filedaemon/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-storage-tape/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-storage/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-tools/Makefile
  systemtests/tests/notls/testrunner
Labels: is a backport to 21, jenkins_repotest_nodebug

#1382 FreeBSD: build cleanup
  .matrix.yml
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-bconsole/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/BareosCommonMakefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/BareosPackageOnlyMakefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-database-common/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-database-postgresql/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-database-tools/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-director/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-filedaemon-python-plugins-common/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-filedaemon-python3-plugin/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-filedaemon/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-storage-tape/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-storage/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-tools/Makefile
  systemtests/tests/notls/testrunner
Labels: is a backport to 20, jenkins_repotest_nodebug

#1378 core: remove deprecated make_catalog_backup.pl
  .gitignore
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.director
  core/platforms/packaging/bareos.spec
  core/platforms/win32/winbareos.nsi
  core/src/cats/CMakeLists.txt
  core/src/cats/make_catalog_backup.pl.in
  core/src/tests/configs/bareos-configparser-tests/bareos-dir.d/job/BackupCatalog.conf
  core/src/tests/configs/catalog/bareos-dir.d/job/BackupCatalog.conf
  debian/bareos-director.install.in
  systemtests/tests/checkpoints/etc/bareos/bareos-dir.d/job/BackupCatalog.conf.in
  systemtests/tests/py2plug-fd-contrib-bareos_tasks_mysql/etc/bareos/bareos-dir.d/job/BackupCatalog.conf.in
  systemtests/tests/py3plug-fd-contrib-mysql_dump/etc/bareos/bareos-dir.d/job/BackupCatalog.conf.in
  systemtests/tests/stresstest/etc/bareos/bareos-dir.d/job/BackupCatalog.conf.in
Labels: removal

#1384 filed: avoid reading from ephemeral buffer
  CHANGELOG.md
  core/src/filed/dir_cmd.cc
  core/src/plugins/filed/python/pyfiles/BareosFdWrapper.py
  systemtests/tests/CMakeLists.txt
  systemtests/tests/py3plug-fd-basic/CMakeLists.txt
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/PluginTest.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bconsole.conf.in
  systemtests/tests/py3plug-fd-basic/jobmsg-backup.txt
  systemtests/tests/py3plug-fd-basic/jobmsg-restore.txt
  systemtests/tests/py3plug-fd-basic/python-modules/jobmsg-module.py
  systemtests/tests/py3plug-fd-basic/test-setup
  systemtests/tests/py3plug-fd-basic/testrunner-jobmsg
Labels: is a backport to 22

#1385 filed: avoid reading from ephemeral buffer
  CHANGELOG.md
  core/src/filed/dir_cmd.cc
  core/src/plugins/filed/python/pyfiles/BareosFdWrapper.py
  systemtests/tests/CMakeLists.txt
  systemtests/tests/py3plug-fd-basic/CMakeLists.txt
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/PluginTest.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bconsole.conf.in
  systemtests/tests/py3plug-fd-basic/jobmsg-backup.txt
  systemtests/tests/py3plug-fd-basic/jobmsg-restore.txt
  systemtests/tests/py3plug-fd-basic/python-modules/jobmsg-module.py
  systemtests/tests/py3plug-fd-basic/test-setup
  systemtests/tests/py3plug-fd-basic/testrunner-jobmsg
Labels: is a backport to 21
