Repository bareos/bareos, pull requests merged in 2023-03, with the labels that each got.

#1390 VMware Plugin: fix restore to different vmname
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/BareosFdPluginVMware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
  docs/manuals/source/include/images/bareos-webui-restore-with-pluginoptions.png
Labels: bugfix, requires backport to 22

#1386 vmware_cbt_tool.py: pyVmomi 8.x compatibility
  CHANGELOG.md
  core/src/vmware/vmware_cbt_tool/vmware_cbt_tool.py
Labels: bugfix, requires backport to 22

#1375 stored: remove warning for maximum block size for tapes
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/lib/bnet.cc
  core/src/stored/device_resource.cc
  core/src/stored/stored_conf.cc
  core/src/tests/addresses_and_ports.cc
  core/src/tests/configs/sd_backend/bareos-sd.d/device/tape1.conf
  core/src/tests/configs/sd_reservation/bareos-sd.d/device/auto1.conf
  core/src/tests/configs/sd_reservation/bareos-sd.d/device/single2.conf
  core/src/tests/configs/statistics_thread/sd_statistics_thread/default_config/bareos-sd.d/device/tape1.conf
  core/src/tests/configs/statistics_thread/sd_statistics_thread/only_collect_set/bareos-sd.d/device/tape1.conf
  core/src/tests/configs/statistics_thread/sd_statistics_thread/only_interval_set/bareos-sd.d/device/tape1.conf
  systemtests/tests/autochanger/create_autochanger_configs.sh.in
  systemtests/tests/block-size/create_autochanger_configs.sh.in
Labels: requires backport to 22

#1379 docs: catalog maintenance improvements
  CHANGELOG.md
  core/src/cats/create_bareos_database.in
  docs/manuals/source/TasksAndConcepts/CatalogMaintenance.rst
Labels: documentation, requires backport to 22

#1397 VMware Plugin: fix restore to different vmname
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/BareosFdPluginVMware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
  docs/manuals/source/include/images/bareos-webui-restore-with-pluginoptions.png
Labels: bugfix, is a backport to 22

#1399 docs: catalog maintenance improvements
  CHANGELOG.md
  core/src/cats/create_bareos_database.in
  docs/manuals/source/TasksAndConcepts/CatalogMaintenance.rst
Labels: documentation, is a backport to 22

#1340 dird: filed: stored: remove deprecated `maxconnections` option from configuration
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/dird/dird_conf.h
  core/src/filed/filed_conf.cc
  core/src/filed/filed_conf.h
  core/src/lib/bnet_server_tcp.cc
  core/src/lib/bnet_server_tcp.h
  core/src/stored/ndmp_tape.cc
  core/src/stored/stored_conf.cc
  core/src/stored/stored_conf.h
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-fd-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-sd-config-schema.json
  systemtests/tests/config-dump/etc/bareos/bareos-dir-19.2.7-show-verbose.conf.in
  systemtests/tests/config-dump/etc/bareos/bareos-dir-full.conf.in
  systemtests/tests/config-dump/etc/orig/bareos-dir-19.2.7-show-verbose.conf
Labels: removal

#1407 berrno_test.cc: accept both 271E and 273E
  CHANGELOG.md
  core/src/tests/berrno_test.cc
Labels: requires backport to 20, requires backport to 21, requires backport to 22

#1408 berrno_test.cc: accept both 271E and 273E
  CHANGELOG.md
  core/src/tests/berrno_test.cc
Labels: is a backport to 22

#1410 Sanitizers: add ASAN options to avoid crashes
  CHANGELOG.md
  devtools/build-and-test-with-sanitize.sh
Labels: requires backport to 20, requires backport to 21, requires backport to 22

#1411 Sanitizers: add ASAN options to avoid crashes
  CHANGELOG.md
  devtools/build-and-test-with-sanitize.sh
Labels: is a backport to 22

#1417 dird: Fix problem with reoccuring files in always incremental
  CHANGELOG.md
  core/src/dird/vbackup.cc
  systemtests/cmake/BareosSystemtestFunctions.cmake
  systemtests/tests/CMakeLists.txt
  systemtests/tests/virtualfull-deletedfiles/CMakeLists.txt
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-dir.d/pool/VirtualFull.conf
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/virtualfull-deletedfiles/etc/bareos/bconsole.conf.in
  systemtests/tests/virtualfull-deletedfiles/test-setup
  systemtests/tests/virtualfull-deletedfiles/testrunner-01-full-backup
  systemtests/tests/virtualfull-deletedfiles/testrunner-02-incremental-backup
  systemtests/tests/virtualfull-deletedfiles/testrunner-03-incremental-backup
  systemtests/tests/virtualfull-deletedfiles/testrunner-04-incremental-backup
  systemtests/tests/virtualfull-deletedfiles/testrunner-05-consolidate
Labels: bugfix, is a backport to 21

#1401 doc: improve plugin, webui, virtualfull chapters
  CHANGELOG.md
  docs/manuals/source/Appendix/Howtos/BackupOfThirdPartyDatabases.rst.inc
  docs/manuals/source/IntroductionAndTutorial/BareosWebui.rst
  docs/manuals/source/TasksAndConcepts/AlwaysIncrementalBackupScheme.rst
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/MariaDBmariabackupPlugin.rst.inc
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/PerconaXtraBackupPlugin.rst.inc
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-job-Level.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-job-VirtualFullBackupPool.rst.inc
Labels: documentation, requires backport to 22

#1415 docs: move and update localization documentation
  CHANGELOG.md
  docs/manuals/source/DeveloperGuide/Webui.rst
  webui/doc/README-INSTALLATION.md
  webui/doc/README-TRANSLATION.md
Labels: documentation

#1398 dird: allow to disable TLS-PSK downgrades
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/dird/fd_cmds.cc
  core/src/dird/fd_cmds.h
  core/src/dird/job.cc
  core/src/qt-tray-monitor/tray_conf.cc
  core/src/tests/configs/dir_fd_connection/dir_fd_allow_tls_downgrade/bareos-dir.d/client/fd-no-downgrade.conf
  core/src/tests/configs/dir_fd_connection/dir_fd_allow_tls_downgrade/bareos-dir.d/director/bareos-dir.conf
  core/src/tests/configs/dir_fd_connection/dir_fd_no_tls_downgrade/bareos-dir.d/client/fd-no-downgrade.conf
  core/src/tests/configs/dir_fd_connection/dir_fd_no_tls_downgrade/bareos-dir.d/director/bareos-dir.conf
  core/src/tests/dir_fd_connection.cc
  systemtests/tests/testfind/testrunner
Labels: requires backport to 22
