Repository bareos/bareos, pull requests merged in 2023-12, with the labels that each got.

#1611 docs: improvements for droplet, jobdefs, concurrents jobs for restore
  CHANGELOG.md
  core/src/defaultconfigs/bareos-dir.d/job/RestoreFiles.conf.in
  docs/manuals/source/Configuration/Director.rst
  docs/manuals/source/TasksAndConcepts/MigrationAndCopy.rst
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/LDAPPlugin.rst.inc
  docs/manuals/source/TasksAndConcepts/StorageBackends.rst
  docs/manuals/source/manually_added_config_directive_descriptions/console-client-EnableKtls.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/console-client-TlsCipherSuites.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/console-console-EnableKtls.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/console-console-TlsCipherSuites.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/console-director-EnableKtls.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/console-director-TlsCipherSuites.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/console-monitor-EnableKtls.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/console-monitor-TlsCipherSuites.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/console-storage-EnableKtls.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/console-storage-TlsCipherSuites.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-client-EnableKtls.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-client-TlsCipherSuites.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-console-EnableKtls.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-console-TlsCipherSuites.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-director-EnableKtls.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-director-TlsCipherSuites.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-job-JobDefs.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-storage-EnableKtls.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-storage-TlsCipherSuites.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/fd-client-EnableKtls.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/fd-client-MaximumWorkersPerJob.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/fd-client-TlsCipherSuites.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/fd-director-EnableKtls.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/fd-director-TlsCipherSuites.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/fd-filedaemon-EnableKtls.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/fd-filedaemon-MaximumWorkersPerJob.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/fd-filedaemon-TlsCipherSuites.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/sd-director-EnableKtls.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/sd-director-TlsCipherSuites.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/sd-storage-EnableKtls.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/sd-storage-TlsCipherSuites.rst.inc
Labels: documentation, is a backport to 23

#1587 restore: add fileregex parameter
  CHANGELOG.md
  core/src/dird/ua_cmds.cc
  core/src/dird/ua_restore.cc
  docs/manuals/source/TasksAndConcepts/TheRestoreCommand.rst
  systemtests/environment.in
  systemtests/scripts/functions
  systemtests/tests/restore/CMakeLists.txt
  systemtests/tests/restore/testrunner-restore-fileregex
Labels: requires backport to 23

#1596 autoxflate: fix autoxflate on replication
  CHANGELOG.md
  core/src/plugins/stored/autoxflate/autoxflate-sd.cc
  core/src/stored/device_resource.cc
  core/src/stored/mac.cc
  systemtests/scripts/functions
  systemtests/tests/CMakeLists.txt
  systemtests/tests/autoxflate/CMakeLists.txt
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/job/copy.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/pool/Local.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/pool/Offsite.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/autoxflate/etc/bareos/bconsole.conf.in
  systemtests/tests/autoxflate/etc/sd-1/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/autoxflate/etc/sd-1/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/autoxflate/etc/sd-1/bareos-sd.d/messages/Standard.conf
  systemtests/tests/autoxflate/etc/sd-1/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/autoxflate/test-setup
  systemtests/tests/autoxflate/testrunner-copy-to-local
  systemtests/tests/autoxflate/testrunner-copy-to-offsite
  systemtests/tests/autoxflate/testrunner-create-backup
  systemtests/tests/autoxflate/testrunner-replication-local
  systemtests/tests/autoxflate/testrunner-replication-offsite
  systemtests/tests/copy-remote-bscan/testrunner
  systemtests/tests/restore/etc/bareos/bareos-dir.d/job/copy-full.conf.in
Labels: is a backport to 21

#1605 Improve python plugin configuration
  CHANGELOG.md
  core/CMakeLists.txt
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.filedaemon-python-plugins-common
  core/platforms/packaging/bareos.spec
  core/scripts/CMakeLists.txt
  core/scripts/bareos_encode_string.py
  core/src/filed/fd_plugins.cc
  core/src/filed/fd_plugins.h
  core/src/include/filetypes.h
  core/src/plugins/filed/python/module/bareosfd.cc
  core/src/plugins/filed/python/module/bareosfd.h
  core/src/plugins/filed/python/pyfiles/BareosFdPluginBaseclass.py
  core/src/tests/CMakeLists.txt
  core/src/tests/test_fd_plugins.cc
  debian/bareos-filedaemon-python-plugins-common.install.in
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/PythonFdPlugin.rst.inc
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/PluginConfigTestBothFiles.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/PluginConfigTestDefaultsFile.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/PluginConfigTestNoFile.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/PluginConfigTestOverridesFile.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-fd.d/plugin_defaults.ini
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-fd.d/plugin_overrides.ini
  systemtests/tests/py3plug-fd-basic/python-modules/config-test-module.py
  systemtests/tests/py3plug-fd-basic/testrunner-config
Labels: enhancement, requires backport to 23

#1613 dird: remove optimize_for_size/optimize_for_speed
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/dird/ua_restore.cc
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  systemtests/tests/config-dump/etc/bareos/bareos-dir-full.conf.in
Labels: is a backport to 23

#1619 Improve python plugin configuration
  CHANGELOG.md
  core/CMakeLists.txt
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.filedaemon-python-plugins-common
  core/platforms/packaging/bareos.spec
  core/scripts/CMakeLists.txt
  core/scripts/bareos_encode_string.py
  core/src/filed/fd_plugins.cc
  core/src/filed/fd_plugins.h
  core/src/include/filetypes.h
  core/src/plugins/filed/python/module/bareosfd.cc
  core/src/plugins/filed/python/module/bareosfd.h
  core/src/plugins/filed/python/pyfiles/BareosFdPluginBaseclass.py
  core/src/tests/CMakeLists.txt
  core/src/tests/test_fd_plugins.cc
  debian/bareos-filedaemon-python-plugins-common.install.in
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/PythonFdPlugin.rst.inc
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/PluginConfigTestBothFiles.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/PluginConfigTestDefaultsFile.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/PluginConfigTestNoFile.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/PluginConfigTestOverridesFile.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-fd.d/plugin_defaults.ini
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-fd.d/plugin_overrides.ini
  systemtests/tests/py3plug-fd-basic/python-modules/config-test-module.py
  systemtests/tests/py3plug-fd-basic/testrunner-config
Labels: enhancement, is a backport to 23

#1618 restore: add fileregex parameter
  CHANGELOG.md
  core/src/dird/ua_cmds.cc
  core/src/dird/ua_restore.cc
  docs/manuals/source/TasksAndConcepts/TheRestoreCommand.rst
  systemtests/environment.in
  systemtests/scripts/functions
  systemtests/tests/restore/CMakeLists.txt
  systemtests/tests/restore/testrunner-restore-fileregex
Labels: enhancement, is a backport to 23

#1592 macOS: fix linking problem for macOS >= 14
  .github/workflows/build-macos.yml
  AUTHORS
  CHANGELOG.md
  cmake/BareosSetVariableDefaults.cmake
  core/CMakeLists.txt
  core/cmake/BareosFindAllLibraries.cmake
  core/cmake/BareosInstallConfigFiles.cmake
  core/cmake/FindReadline.cmake
  core/platforms/darwin/resources/ReadMe.html.in
  core/platforms/darwin/resources/uninstall-bareos.in
  core/src/console/CMakeLists.txt
  core/src/plugins/CMakeLists.txt
  core/src/plugins/filed/python/CMakeLists.txt
  docs/manuals/source/IntroductionAndTutorial/InstallingBareosClient.rst
Labels: requires backport to 21, requires backport to 22, requires backport to 23

#1621 macOS: fix linking problem for macOS >= 14
  AUTHORS
  CHANGELOG.md
  cmake/BareosSetVariableDefaults.cmake
  core/CMakeLists.txt
  core/cmake/BareosFindAllLibraries.cmake
  core/cmake/BareosInstallConfigFiles.cmake
  core/cmake/FindReadline.cmake
  core/platforms/darwin/resources/ReadMe.html.in
  core/platforms/darwin/resources/uninstall-bareos.in
  core/src/console/CMakeLists.txt
  core/src/plugins/CMakeLists.txt
  core/src/plugins/filed/python/CMakeLists.txt
  docs/manuals/source/IntroductionAndTutorial/InstallingBareosClient.rst
Labels: is a backport to 22

#1612 dird: remove optimize_for_size/optimize_for_speed
  CHANGELOG.md
  core/src/benchmarks/restore_browser_stress_test.cc
  core/src/dird/dird_conf.cc
  core/src/dird/dird_conf.h
  core/src/dird/reload.cc
  core/src/dird/ua_restore.cc
  core/src/dird/ua_tree.cc
  core/src/tests/globbing_test.cc
  docs/manuals/source/Configuration/Director.rst
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  docs/manuals/source/manually_added_config_directive_descriptions/dir-director-OptimizeForSize.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-director-OptimizeForSpeed.rst.inc
  systemtests/tests/config-dump/etc/bareos/bareos-dir-full.conf.in
Labels: requires backport to 23

#1620 macOS: fix linking problem for macOS >= 14
  .github/workflows/build-macos.yml
  AUTHORS
  CHANGELOG.md
  cmake/BareosSetVariableDefaults.cmake
  core/CMakeLists.txt
  core/cmake/BareosFindAllLibraries.cmake
  core/cmake/BareosInstallConfigFiles.cmake
  core/cmake/FindReadline.cmake
  core/platforms/darwin/resources/ReadMe.html.in
  core/platforms/darwin/resources/uninstall-bareos.in
  core/src/console/CMakeLists.txt
  core/src/plugins/CMakeLists.txt
  core/src/plugins/filed/python/CMakeLists.txt
  docs/manuals/source/IntroductionAndTutorial/InstallingBareosClient.rst
Labels: is a backport to 23

#1614 build: introduce Fedora 39
  .matrix.yml
  CHANGELOG.md
  docs/pkglists/Fedora_39.x86_64
Labels: requires backport to 23

#1615 build: introduce Fedora 39
  .matrix.yml
  CHANGELOG.md
  docs/pkglists/Fedora_39.x86_64
Labels: is a backport to 23

#1617 filedaemon: remove ovirt plugin
  CHANGELOG.md
  core/CMakeLists.txt
  core/platforms/packaging/bareos.spec
  core/src/plugins/filed/python/CMakeLists.txt
  core/src/plugins/filed/python/ovirt/BareosFdPluginOvirt.py
  core/src/plugins/filed/python/ovirt/bareos-fd-ovirt.py
  core/src/plugins/filed/python/ovirt/python-ovirt-conf.d/bareos-dir.d/fileset/plugin-ovirt.conf.example
  core/src/plugins/filed/python/ovirt/python-ovirt-conf.d/bareos-dir.d/job/backup-ovirt.conf.example
  docs/manuals/source/IntroductionAndTutorial/WhatIsBareos.rst
  docs/manuals/source/TasksAndConcepts/Plugins.rst
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins.rst.inc
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/OVirtPlugin.rst.inc
  docs/pkglists/EL_7.x86_64
  docs/pkglists/EL_8.x86_64
  docs/pkglists/EL_9.x86_64
  docs/pkglists/Fedora_38.x86_64
  docs/pkglists/Fedora_39.x86_64
  docs/pkglists/SLE_12_SP5.x86_64
  docs/pkglists/SUSE_15.x86_64
  systemtests/cmake/BareosSystemtestFunctions.cmake
  systemtests/environment.in
  systemtests/tests/CMakeLists.txt
  systemtests/tests/py3plug-fd-ovirt/CMakeLists.txt
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-dir.d/fileset/OvirtTest.conf.in
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/bconsole.conf.in
  systemtests/tests/py3plug-fd-ovirt/etc/bareos/ovirt-plugin.ini.in
  systemtests/tests/py3plug-fd-ovirt/testrunner.in
Labels: requires backport to 22, requires backport to 23

#1624 macOS: fix linking problem for macOS >= 14
  AUTHORS
  CHANGELOG.md
  core/CMakeLists.txt
  core/cmake/BareosFindAllLibraries.cmake
  core/cmake/BareosInstallConfigFiles.cmake
  core/cmake/BareosSetVariableDefaults.cmake
  core/cmake/FindReadline.cmake
  core/platforms/darwin/resources/ReadMe.html.in
  core/platforms/darwin/resources/uninstall-bareos.in
  core/src/console/CMakeLists.txt
  core/src/plugins/CMakeLists.txt
  core/src/plugins/filed/python/CMakeLists.txt
  docs/manuals/source/Appendix/OperatingSystems.rst
Labels: is a backport to 21

#1627 filedaemon: remove ovirt plugin
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/OVirtPlugin.rst.inc
Labels: documentation, is a backport to 22

#1628 dird: fix `purge oldest volume`
  CHANGELOG.md
  core/src/dird/ua_input.cc
  core/src/dird/ua_input.h
  core/src/dird/ua_purge.cc
  systemtests/tests/bareos-basic/etc/bareos/bareos-dir.d/job/purge-oldest-job.conf
  systemtests/tests/bareos-basic/etc/bareos/bareos-dir.d/pool/purgeoldest.conf
  systemtests/tests/bareos-basic/testrunner-purge-oldest
Labels: bugfix, requires backport to 23

#1629 dird: fix `purge oldest volume`
  CHANGELOG.md
  core/src/dird/ua_input.cc
  core/src/dird/ua_input.h
  core/src/dird/ua_purge.cc
  systemtests/tests/bareos-basic/etc/bareos/bareos-dir.d/job/purge-oldest-job.conf
  systemtests/tests/bareos-basic/etc/bareos/bareos-dir.d/pool/purgeoldest.conf
  systemtests/tests/bareos-basic/testrunner-purge-oldest
Labels: bugfix, is a backport to 23

#1593 vadp-dumper: fix multithreaded backup/restore issues
  CHANGELOG.md
  core/src/findlib/bfile.cc
  core/src/tests/CMakeLists.txt
  core/src/tests/ktls.cc
  core/src/vmware/vadp_dumper/bareos_vadp_dumper.cc
  core/src/vmware/vadp_dumper/cbuf.cc
  core/src/vmware/vadp_dumper/cbuf.h
  core/src/vmware/vadp_dumper/copy_thread.cc
  core/src/vmware/vadp_dumper/copy_thread.h
Labels: requires backport to 23

#1623 vadp-dumper: fix multithreaded backup/restore issues
  CHANGELOG.md
  core/src/findlib/bfile.cc
  core/src/tests/CMakeLists.txt
  core/src/tests/ktls.cc
  core/src/vmware/vadp_dumper/bareos_vadp_dumper.cc
  core/src/vmware/vadp_dumper/cbuf.cc
  core/src/vmware/vadp_dumper/cbuf.h
  core/src/vmware/vadp_dumper/copy_thread.cc
  core/src/vmware/vadp_dumper/copy_thread.h
Labels: is a backport to 23

#1630 VMware Plugin: Run bareos_vadp_dumper with optimized parameters to increase backup performance
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/bareos-fd-vmware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: requires backport to 23

#1631 VMware Plugin: Run bareos_vadp_dumper with optimized parameters to increase backup performance
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/bareos-fd-vmware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: is a backport to 23

#1632 pkglists: update SUSE to have vmware packages
  CHANGELOG.md
  docs/pkglists/SLE_12_SP5.x86_64
  docs/pkglists/SUSE_15.x86_64
Labels: requires backport to 21, requires backport to 22, requires backport to 23

#1634 pkglists: update SUSE to have vmware packages
  CHANGELOG.md
  docs/pkglists/SLE_12_SP5.x86_64
  docs/pkglists/SUSE_15.x86_64
Labels: is a backport to 22

#1635 pkglists: update SUSE to have vmware packages
  CHANGELOG.md
  docs/pkglists/SLE_12_SP5.x86_64
  docs/pkglists/SLE_15_SP3.x86_64
  docs/pkglists/SLE_15_SP4.x86_64
Labels: is a backport to 21

#1633 pkglists: update SUSE to have vmware packages
  CHANGELOG.md
  docs/pkglists/SLE_12_SP5.x86_64
  docs/pkglists/SUSE_15.x86_64
Labels: is a backport to 23

#1637 Fix continuation on colons in plugin baseclass
  CHANGELOG.md
  core/src/plugins/filed/python/pyfiles/BareosFdPluginBaseclass.py
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/PluginConfigTestNoFile.conf.in
  systemtests/tests/py3plug-fd-basic/testrunner-config
Labels: bugfix, requires backport to 23

#1638 Fix continuation on colons in plugin baseclass
  CHANGELOG.md
  core/src/plugins/filed/python/pyfiles/BareosFdPluginBaseclass.py
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/PluginConfigTestNoFile.conf.in
  systemtests/tests/py3plug-fd-basic/testrunner-config
Labels: bugfix, is a backport to 23

#1595 plugins: fix cancel handling crash
  CHANGELOG.md
  core/scripts/btraceback.in
  core/src/filed/dir_cmd.cc
  core/src/include/jcr.h
  core/src/lib/address_conf.cc
  core/src/lib/jcr.cc
  core/src/plugins/filed/python/module/bareosfd.cc
  core/src/plugins/filed/python/plugin_private_context.h
  core/src/plugins/filed/python/python-fd.cc
  core/src/plugins/stored/python/python-sd.cc
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/CancelFileset.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/CancelNoWaitFileset.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/job/cancel-check.conf
  systemtests/tests/py3plug-fd-basic/python-modules/cancel-check-module.py
  systemtests/tests/py3plug-fd-basic/testrunner-cancel-check
  systemtests/tests/py3plug-fd-basic/testrunner-cancel-check-no-wait
Labels: bugfix, requires backport to 23
