Repository bareos/bareos, pull requests merged in 2023-06, with the labels that each got.

#1431 Improve handling of catalog requests that try to reduce VolFiles, VolBlocks and VolBytes
  CHANGELOG.md
  core/src/dird/catreq.cc
  core/src/stored/acquire.cc
  core/src/stored/askdir.cc
  core/src/stored/block.cc
  core/src/stored/device.cc
  core/src/stored/device_control_record.h
  core/src/stored/label.cc
  core/src/stored/mount.cc
  core/src/stored/sd_device_control_record.h
Labels: bugfix, requires backport to 22

#1434 pr-tool: handling POEditor commits and optional github ci tests
  CHANGELOG.md
  devtools/pip-tools/pr_tool/main.py
Labels: nobuild

#1473 VMware Plugin: Backup and Restore of VMs using multiple datastores
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/BareosFdPluginVMware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: requires backport to 22

#1479 filed: fix off-by-one error when resizing acl buffer
  CHANGELOG.md
  core/src/filed/fd_plugins.cc
Labels: bugfix, requires backport to 22

#1480 filed: fix off-by-one error when resizing acl buffer
  CHANGELOG.md
  core/src/filed/fd_plugins.cc
Labels: bugfix, is a backport to 22

#1371 webui: re-add show update status for clients
  CHANGELOG.md
  webui/module/Api/src/Api/Controller/ClientController.php
  webui/module/Auth/view/auth/auth/login.phtml
  webui/module/Client/view/client/client/index.phtml
  webui/public/js/bootstrap-table-formatter.js
Labels: jenkins_repotest_nodebug

#1475 Improve handling of catalog requests that try to reduce VolFiles, VolBlocks and VolBytes
  CHANGELOG.md
  core/src/dird/catreq.cc
  core/src/stored/acquire.cc
  core/src/stored/askdir.cc
  core/src/stored/block.cc
  core/src/stored/device.cc
  core/src/stored/device_control_record.h
  core/src/stored/label.cc
  core/src/stored/mount.cc
  core/src/stored/sd_device_control_record.h
Labels: bugfix, is a backport to 22

#1482 build: add Debian 12
  .matrix.yml
  CHANGELOG.md
  core/src/cats/ddl/grants/postgresql-change_owner.dbconfig-template.sql
  core/src/cats/ddl/grants/postgresql-readonly.sql
  core/src/cats/ddl/grants/postgresql.sql
  docs/pkglists/Debian_12.x86_64
Labels: is a backport to 22

#1474 Consolidate: fix for consolidate job's client name not being correctly shown
  CHANGELOG.md
  core/src/dird/consolidate.cc
  core/src/dird/job.cc
  docs/manuals/source/DeveloperGuide/generaldevel.rst
  pull_request_template.md
  systemtests/cmake/BareosSystemtestFunctions.cmake
  systemtests/tests/CMakeLists.txt
  systemtests/tests/multiple-clients/CMakeLists.txt
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/job/Consolidate.conf
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/pool/AI-Consolidated.conf
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/pool/AI-Incremental.conf
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/pool/AI-Longterm.conf
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/multiple-clients/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/multiple-clients/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/multiple-clients/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bconsole.conf.in
  systemtests/tests/multiple-clients/etc/secondclient/bareos-fd.d/client/myself.conf.in
  systemtests/tests/multiple-clients/etc/secondclient/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/multiple-clients/etc/secondclient/bareos-fd.d/messages/Standard.conf
  systemtests/tests/multiple-clients/test-setup
  systemtests/tests/multiple-clients/testrunner-consolidate-client
Labels: bugfix, requires backport to 22

#1481 Consolidate: fix for consolidate job's client name not being correctly shown
  CHANGELOG.md
  core/src/dird/consolidate.cc
  core/src/dird/job.cc
  docs/manuals/source/DeveloperGuide/generaldevel.rst
  pull_request_template.md
  systemtests/cmake/BareosSystemtestFunctions.cmake
  systemtests/tests/CMakeLists.txt
  systemtests/tests/multiple-clients/CMakeLists.txt
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/job/Consolidate.conf
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/pool/AI-Consolidated.conf
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/pool/AI-Incremental.conf
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/pool/AI-Longterm.conf
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/multiple-clients/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/multiple-clients/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/multiple-clients/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/multiple-clients/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/multiple-clients/etc/bareos/bconsole.conf.in
  systemtests/tests/multiple-clients/etc/secondclient/bareos-fd.d/client/myself.conf.in
  systemtests/tests/multiple-clients/etc/secondclient/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/multiple-clients/etc/secondclient/bareos-fd.d/messages/Standard.conf
  systemtests/tests/multiple-clients/test-setup
  systemtests/tests/multiple-clients/testrunner-consolidate-client
Labels: bugfix, is a backport to 22

#1448 scripts: config-lib improve setup_sd_user
  CHANGELOG.md
  core/scripts/bareos-config-lib.sh.in
Labels: bugfix, requires backport to 22

#1468 docs: Windows add Antivirus section
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/TheWindowsVersionOfBareos.rst
  docs/manuals/source/include/images/windows-defender-exclusion.png
Labels: documentation

#1485 docs: Windows add Antivirus section
  CHANGELOG.md
  docs/manuals/source/DeveloperGuide/Webui.rst
  docs/manuals/source/TasksAndConcepts/TheWindowsVersionOfBareos.rst
  docs/manuals/source/include/images/windows-defender-exclusion.png
Labels: documentation, is a backport to 22

#1484 VMware Plugin: improve snapshot cleanup
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/BareosFdPluginVMware.py
Labels: requires backport to 22

#1493 packaging: cleanup SUSE webui dependencies
  .matrix.yml
  CHANGELOG.md
  core/platforms/packaging/bareos.spec
Labels: requires backport to 22

#1494 packaging: cleanup SUSE webui dependencies
  .matrix.yml
  CHANGELOG.md
  core/platforms/packaging/bareos.spec
Labels: is a backport to 22

#1490 build: adapt matrix and pkglist for changes to CI
  .matrix.yml
  CHANGELOG.md
  docs/pkglists/Fedora_36.x86_64
  docs/pkglists/Fedora_37.x86_64
Labels: requires backport to 21, requires backport to 22

#1497 build: adapt matrix and pkglist for changes to CI
  .matrix.yml
  CHANGELOG.md
  docs/pkglists/Fedora_36.x86_64
  docs/pkglists/Fedora_37.x86_64
Labels: is a backport to 22

#1498 build: adapt matrix and pkglist for changes to CI
  .matrix.yml
  CHANGELOG.md
  docs/pkglists/Fedora_35.x86_64
  docs/pkglists/Fedora_36.x86_64
Labels: is a backport to 21
