Repository bareos/bareos, pull requests merged in 2023-04, with the labels that each got.

#1427 doc: improvements webui, plugins, virtualfull chapters
  CHANGELOG.md
  docs/manuals/source/Appendix/Howtos/BackupOfThirdPartyDatabases.rst.inc
  docs/manuals/source/IntroductionAndTutorial.rst
  docs/manuals/source/IntroductionAndTutorial/BareosWebui.rst
  docs/manuals/source/IntroductionAndTutorial/InstallingBareosWebui.rst
  docs/manuals/source/IntroductionAndTutorial/WhatIsBareos.rst
  docs/manuals/source/TasksAndConcepts/AlwaysIncrementalBackupScheme.rst
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/MariaDBmariabackupPlugin.rst.inc
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/PerconaXtraBackupPlugin.rst.inc
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
  docs/manuals/source/TasksAndConcepts/TransportEncryption.rst
  docs/manuals/source/manually_added_config_directive_descriptions/dir-job-Level.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-job-VirtualFullBackupPool.rst.inc
Labels: documentation, is a backport to 22

#1430 core: fixes for gcc-13 support
  CHANGELOG.md
  core/src/cats/cats.h
  core/src/console/console_conf.cc
  core/src/lib/thread_list.cc
  core/src/lib/thread_specific_data.cc
  core/src/lib/thread_specific_data.h
  core/src/lib/thread_specific_data_key.h
  pull_request_template.md
Labels: is a backport to 22

#1420 ua_restore: enable restore from archive
  CHANGELOG.md
  core/src/cats/bdb_query_enum_class.h
  core/src/cats/bdb_query_names.inc
  core/src/cats/dml/0016_uar_list_jobs
  core/src/cats/dml/0020_uar_last_full
  core/src/cats/dml/0021_uar_last_full_no_pool
  core/src/cats/dml/0022_uar_full
  core/src/cats/dml/0023_uar_dif
  core/src/cats/dml/0024_uar_inc
  core/src/cats/dml/0031_uar_jobid_fileindex
  core/src/cats/dml/0037_create_temp_accurate_jobids
  core/src/cats/mysql_queries.inc
  core/src/cats/postgresql_queries.inc
  core/src/cats/sql_get.cc
  core/src/cats/sqlite_queries.inc
  core/src/dird/dird_conf.cc
  core/src/dird/ua.cc
  core/src/dird/ua.h
  core/src/dird/ua_restore.cc
  systemtests/data/weird-files.tar.gz
  systemtests/tests/CMakeLists.txt
  systemtests/tests/restore/CMakeLists.txt
  systemtests/tests/restore/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/restore/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/restore/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/restore/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/restore/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/restore/etc/bareos/bareos-dir.d/job/BackupCatalog.conf.in
  systemtests/tests/restore/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/restore/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/restore/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/restore/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/restore/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/restore/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/restore/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/restore/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/restore/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/restore/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/restore/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/restore/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/restore/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/restore/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/restore/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/restore/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/restore/etc/bareos/bconsole.conf.in
  systemtests/tests/restore/functions
  systemtests/tests/restore/test-setup
  systemtests/tests/restore/testrunner-archive-full-restore
  systemtests/tests/restore/testrunner-archive-restore-dir
  systemtests/tests/restore/testrunner-archive-restore-file
  systemtests/tests/restore/testrunner-check-hints
  systemtests/tests/restore/testrunner-create-backup
  systemtests/tests/restore/testrunner-full-restore
  systemtests/tests/restore/testrunner-restore-dir
  systemtests/tests/restore/testrunner-restore-file
  systemtests/tests/restore/testrunner-restore-old-archive
Labels: is a backport to 22

#1436 dird: keep copy and migration control/administrative jobs
  CHANGELOG.md
  core/src/dird/migrate.cc
  docs/manuals/source/TasksAndConcepts/MigrationAndCopy.rst
  systemtests/tests/copy-migrate/testrunner-02-copy
  systemtests/tests/copy-migrate/testrunner-03-impossible-copy
  systemtests/tests/copy-migrate/testrunner-05-migrate
Labels: is a backport to 22

#1402 scripts: config-lib improve get_local_hostname fallback
  CHANGELOG.md
  core/platforms/packaging/bareos.spec
  core/scripts/bareos-config-lib.sh.in
  debian/control.bareos-common
Labels: requires backport to 22

#1439 check-sources: update check-sources ignores
  .bareos-check-sources-ignore
  CHANGELOG.md
Labels: documentation

#1438 scripts: config-lib improve get_local_hostname fallback
  CHANGELOG.md
  core/platforms/packaging/bareos.spec
  core/scripts/bareos-config-lib.sh.in
  debian/control.bareos-common
Labels: is a backport to 22

#1428 dird: allow to disable TLS-PSK downgrades
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/dird/fd_cmds.cc
  core/src/dird/fd_cmds.h
  core/src/dird/job.cc
  core/src/qt-tray-monitor/tray_conf.cc
  core/src/tests/configs/dir_fd_connection/dir_fd_allow_tls_downgrade/bareos-dir.d/client/fd-no-downgrade.conf
  core/src/tests/configs/dir_fd_connection/dir_fd_allow_tls_downgrade/bareos-dir.d/director/bareos-dir.conf
  core/src/tests/configs/dir_fd_connection/dir_fd_no_tls_downgrade/bareos-dir.d/client/fd-no-downgrade.conf
  core/src/tests/configs/dir_fd_connection/dir_fd_no_tls_downgrade/bareos-dir.d/director/bareos-dir.conf
  core/src/tests/dir_fd_connection.cc
Labels: is a backport to 22

#1440 build: switch to FreeBSD 12.4
  .matrix.yml
  CHANGELOG.md
  core/src/tests/bsock_mock.h
Labels: requires backport to 20, requires backport to 21, requires backport to 22

#1442 build: switch to FreeBSD 12.4
  .matrix.yml
  CHANGELOG.md
  core/src/tests/bsock_mock.h
Labels: is a backport to 22

#1444 build: switch to FreeBSD 12.4
  .matrix.yml
  CHANGELOG.md
  core/src/tests/bsock_mock.h
Labels: is a backport to 20

#1445 webui: make restore merge options configurable
  CHANGELOG.md
  docs/manuals/source/IntroductionAndTutorial/BareosWebui.rst
  webui/config/autoload/global.php.in
  webui/install/configuration.ini.in
  webui/module/Auth/src/Auth/Controller/AuthController.php
  webui/module/Restore/src/Restore/Controller/RestoreController.php
  webui/module/Restore/src/Restore/Form/RestoreForm.php
  webui/module/Restore/src/Restore/Model/RestoreModel.php
  webui/module/Restore/view/restore/restore/index.phtml
  webui/module/Restore/view/restore/restore/versions.phtml
  webui/public/js/bootstrap-table-formatter.js
Labels: requires backport to 22

#1423 stored: remove warning for maximum block size for tapes
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/lib/bnet.cc
  core/src/stored/device_resource.cc
  core/src/stored/stored_conf.cc
  core/src/tests/addresses_and_ports.cc
  core/src/tests/configs/sd_backend/bareos-sd.d/device/tape1.conf
  core/src/tests/configs/sd_reservation/bareos-sd.d/device/auto1.conf
  core/src/tests/configs/sd_reservation/bareos-sd.d/device/single2.conf
  core/src/tests/configs/statistics_thread/sd_statistics_thread/default_config/bareos-sd.d/device/tape1.conf
  core/src/tests/configs/statistics_thread/sd_statistics_thread/only_collect_set/bareos-sd.d/device/tape1.conf
  core/src/tests/configs/statistics_thread/sd_statistics_thread/only_interval_set/bareos-sd.d/device/tape1.conf
  systemtests/tests/autochanger/create_autochanger_configs.sh.in
  systemtests/tests/block-size/create_autochanger_configs.sh.in
Labels: is a backport to 22

#1446 webui: make restore merge options configurable
  CHANGELOG.md
  docs/manuals/source/IntroductionAndTutorial/BareosWebui.rst
  webui/config/autoload/global.php.in
  webui/install/configuration.ini.in
  webui/module/Auth/src/Auth/Controller/AuthController.php
  webui/module/Restore/src/Restore/Controller/RestoreController.php
  webui/module/Restore/src/Restore/Form/RestoreForm.php
  webui/module/Restore/src/Restore/Model/RestoreModel.php
  webui/module/Restore/view/restore/restore/index.phtml
  webui/module/Restore/view/restore/restore/versions.phtml
  webui/public/js/bootstrap-table-formatter.js
Labels: is a backport to 22
