Repository bareos/bareos, pull requests merged in 2023-10, with the labels that each got.

#1549 tools: fix tools not starting up on windows
  CHANGELOG.md
  core/src/dird/dird.cc
  core/src/filed/filed.cc
  core/src/lib/CMakeLists.txt
  core/src/lib/address_conf.cc
  core/src/lib/bareos_universal_initialiser.cc
  core/src/lib/bareos_universal_initialiser.h
  core/src/stored/bls.cc
  core/src/stored/stored.cc
Labels: requires backport to 22

#1548 dird: `list jobs`: add `level` keyword and accept a list of job levels
  CHANGELOG.md
  core/src/cats/cats.h
  core/src/cats/sql_list.cc
  core/src/dird/ua_output.cc
  core/src/dird/ua_select.cc
  core/src/dird/ua_select.h
  systemtests/tests/python-bareos/test_list_command.py
Labels: requires backport to 22

#1547 cats: fix for integer overflow issue when using `offset` in `llist`
  CHANGELOG.md
  core/src/cats/cats.h
  core/src/dird/ua_output.cc
  core/src/findlib/bfile.cc
  core/src/include/baconfig.h
  core/src/lib/btimers.cc
  core/src/lib/message.cc
  core/src/lib/message.h
  core/src/lib/output_formatter.cc
  core/src/lib/output_formatter.h
  systemtests/tests/python-bareos/test_list_command.py
Labels: bugfix, requires backport to 21, requires backport to 22

#1565 VMware Plugin: Fix backup and recreating VMs with PCI passthrough for GPU
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/BareosFdPluginVMware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: bugfix, requires backport to 22

#1567 VMware Plugin: Fix backup and recreating VMs with PCI passthrough for GPU
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/BareosFdPluginVMware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: is a backport to 22

#1573 packaging: debian fix dependencies
  CHANGELOG.md
  debian/control
  debian/control.bareos-webui
  debian/control.src
Labels: requires backport to 21, requires backport to 22

#1561 dird: list jobs: add level keyword and accept a list of job levels
  CHANGELOG.md
  core/src/cats/cats.h
  core/src/cats/sql_list.cc
  core/src/dird/ua_output.cc
  core/src/dird/ua_select.cc
  core/src/dird/ua_select.h
  systemtests/tests/python-bareos/test_list_command.py
Labels: is a backport to 22

#1574 packaging: debian fix dependencies
  CHANGELOG.md
  debian/control
  debian/control.bareos-webui
  debian/control.src
Labels: is a backport to 22

#1558 filed: fix possible data-loss when excluding hardlinks
  CHANGELOG.md
  core/src/dird/testfind.cc
  core/src/filed/backup.cc
  core/src/filed/fd_plugins.cc
  core/src/findlib/CMakeLists.txt
  core/src/findlib/find.h
  core/src/findlib/find_one.cc
  core/src/findlib/hardlink.cc
  core/src/findlib/hardlink.h
  core/src/lib/util.h
  systemtests/tests/bareos-basic/CMakeLists.txt
  systemtests/tests/bareos-basic/etc/bareos/bareos-dir.d/fileset/HardLinks.conf.in
  systemtests/tests/bareos-basic/etc/bareos/bareos-dir.d/job/backup-some-hardlinks.conf
  systemtests/tests/bareos-basic/test-setup
  systemtests/tests/bareos-basic/testrunner-hardlinks
Labels: is a backport to 22

#1559 filed: fix possible data loss when excluding hardlinks
  CHANGELOG.md
  core/src/dird/testfind.cc
  core/src/filed/backup.cc
  core/src/filed/fd_plugins.cc
  core/src/findlib/CMakeLists.txt
  core/src/findlib/find.h
  core/src/findlib/find_one.cc
  core/src/findlib/hardlink.cc
  core/src/findlib/hardlink.h
  core/src/lib/util.h
  systemtests/tests/bareos-basic/CMakeLists.txt
  systemtests/tests/bareos-basic/etc/bareos/bareos-dir.d/fileset/HardLinks.conf.in
  systemtests/tests/bareos-basic/etc/bareos/bareos-dir.d/job/backup-some-hardlinks.conf
  systemtests/tests/bareos-basic/test-setup
  systemtests/tests/bareos-basic/testrunner-hardlinks
Labels: is a backport to 21

#1568 cats: fix for integer overflow issue when using offset in llist
  CHANGELOG.md
  core/src/cats/cats.h
  core/src/cats/cats_backends.cc
  core/src/dird/ua_output.cc
  core/src/findlib/bfile.cc
  core/src/include/baconfig.h
  core/src/lib/btimers.cc
  core/src/lib/message.cc
  core/src/lib/message.h
  core/src/lib/output_formatter.cc
  core/src/lib/output_formatter.h
  systemtests/tests/python-bareos/test_list_command.py
Labels: bugfix, is a backport to 22
