Repository bareos/bareos, pull requests merged in 2023-09, with the labels that each got.

#1534 plugin-fd: allow fd plugins to (re-)set since-time and disable/re-enable timestamp/accurate checks
  CHANGELOG.md
  core/src/filed/fd_plugins.cc
  core/src/filed/fd_plugins.h
  core/src/plugins/filed/python/module/bareosfd.cc
  core/src/plugins/filed/python/module/bareosfd.h
  core/src/plugins/filed/python/test/python-fd-module-tester.cc
  core/src/stored/bextract.cc
  systemtests/tests/bscan-bextract-bls-bcopy/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/PluginCheckChanges.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/PluginSinceTime.conf.in
  systemtests/tests/py3plug-fd-basic/python-modules/force-backup-module.py
  systemtests/tests/py3plug-fd-basic/testrunner-forcebackup
Labels: enhancement, is a backport to 22

#1550 webui: upgrade bootstrap to version 3.4.1
  CHANGELOG.md
  webui/public/css/bootstrap-theme.css
  webui/public/css/bootstrap-theme.css.map
  webui/public/css/bootstrap-theme.min.css
  webui/public/css/bootstrap.css
  webui/public/css/bootstrap.css.map
  webui/public/css/bootstrap.min.css
  webui/public/css/bootstrap.min.css.map
  webui/public/js/bootstrap.js
  webui/public/js/bootstrap.min.js
Labels: requires backport to 20, requires backport to 21, requires backport to 22

#1551 webui: upgrade bootstrap to version 3.4.1
  CHANGELOG.md
  webui/public/css/bootstrap-theme.css
  webui/public/css/bootstrap-theme.css.map
  webui/public/css/bootstrap-theme.min.css
  webui/public/css/bootstrap.css
  webui/public/css/bootstrap.css.map
  webui/public/css/bootstrap.min.css
  webui/public/css/bootstrap.min.css.map
  webui/public/js/bootstrap.js
  webui/public/js/bootstrap.min.js
Labels: is a backport to 22

#1552 webui: upgrade bootstrap to version 3.4.1
  CHANGELOG.md
  webui/public/css/bootstrap-theme.css
  webui/public/css/bootstrap-theme.css.map
  webui/public/css/bootstrap-theme.min.css
  webui/public/css/bootstrap.css
  webui/public/css/bootstrap.css.map
  webui/public/css/bootstrap.min.css
  webui/public/css/bootstrap.min.css.map
  webui/public/js/bootstrap.js
  webui/public/js/bootstrap.min.js
Labels: is a backport to 21

#1532 VMware Plugin: Fix transformer issues
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/BareosFdPluginVMware.py
  core/src/vmware/vmware_cbt_tool/vmware_cbt_tool.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: bugfix, requires backport to 22

#1553 webui: upgrade bootstrap to version 3.4.1
  .bareos-check-sources-ignore
  .check-sources-ignore
  CHANGELOG.md
  webui/public/css/bootstrap-theme.css
  webui/public/css/bootstrap-theme.css.map
  webui/public/css/bootstrap-theme.min.css
  webui/public/css/bootstrap.css
  webui/public/css/bootstrap.css.map
  webui/public/css/bootstrap.min.css
  webui/public/css/bootstrap.min.css.map
  webui/public/js/bootstrap.js
  webui/public/js/bootstrap.min.js
Labels: is a backport to 20

#1555 VMware Plugin: Fix transformer issues
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/BareosFdPluginVMware.py
  core/src/vmware/vmware_cbt_tool/vmware_cbt_tool.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: is a backport to 22

#1515 daemons: set CLI11 error exit code to `41` and bareos config parsing error exit code to `42`
  CHANGELOG.md
  core/platforms/systemd/bareos-dir.service.in
  core/platforms/systemd/bareos-fd.service.in
  core/platforms/systemd/bareos-sd.service.in
  core/src/console/console.cc
  core/src/dird/dbcheck.cc
  core/src/dird/dbcheck_utils.cc
  core/src/dird/dird.cc
  core/src/filed/filed.cc
  core/src/include/exit_codes.h
  core/src/lib/cli.cc
  core/src/lib/cli.h
  core/src/lib/daemon.cc
  core/src/lib/message.cc
  core/src/lib/message_severity.h
  core/src/lib/parse_conf.cc
  core/src/lib/parse_conf.h
  core/src/lib/signal.cc
  core/src/qt-tray-monitor/tray-monitor.cc
  core/src/stored/bcopy.cc
  core/src/stored/bextract.cc
  core/src/stored/bls.cc
  core/src/stored/bscan.cc
  core/src/stored/btape.cc
  core/src/stored/stored.cc
  core/src/tests/dlist_test.cc
  core/src/tests/sd_backend_tests.h
  core/src/tests/sd_reservation.cc
  core/src/tests/test_config_parser_sd.cc
  core/src/tools/bregex.cc
  core/src/tools/bsmtp.cc
  core/src/tools/btestls.cc
  core/src/tools/bwild.cc
  core/src/tools/drivetype.cc
  core/src/tools/fstype.cc
  core/src/tools/gentestdata.cc
  core/src/tools/testfind.cc
  core/src/tools/testfind_fd.cc
  debian/bareos-director.service.in
  debian/bareos-filedaemon.service.in
  debian/bareos-storage.service.in
Labels: requires backport to 22

#1506 filed: fix possible data-loss when excluding hardlinks
  CHANGELOG.md
  core/src/filed/backup.cc
  core/src/filed/fd_plugins.cc
  core/src/findlib/CMakeLists.txt
  core/src/findlib/find.h
  core/src/findlib/find_one.cc
  core/src/findlib/hardlink.cc
  core/src/findlib/hardlink.h
  core/src/lib/util.h
  systemtests/tests/bareos-basic/CMakeLists.txt
  systemtests/tests/bareos-basic/etc/bareos/bareos-dir.d/fileset/HardLinks.conf.in
  systemtests/tests/bareos-basic/etc/bareos/bareos-dir.d/job/backup-some-hardlinks.conf
  systemtests/tests/bareos-basic/test-setup
  systemtests/tests/bareos-basic/testrunner-hardlinks
Labels: bugfix, requires backport to 21, requires backport to 22

#1504 utils: add a thread-safe single-producer/single-consumer queue
  CHANGELOG.md
  core/src/lib/channel.h
  core/src/lib/thread_util.h
  core/src/tests/CMakeLists.txt
  core/src/tests/channel.cc
Labels: enhancement

#1563 build: introduce fedora38
  .matrix.yml
  CHANGELOG.md
  core/src/findlib/find_one.cc
  docs/pkglists/Fedora_38.x86_64
Labels: requires backport to 22

#1564 build: introduce fedora38
  .matrix.yml
  CHANGELOG.md
  core/src/findlib/find_one.cc
  docs/pkglists/Fedora_38.x86_64
Labels: is a backport to 22

#1557 daemons: set CLI11 error exit code to `41` and bareos config parsing error exit code to `42`
  CHANGELOG.md
  core/platforms/systemd/bareos-dir.service.in
  core/platforms/systemd/bareos-fd.service.in
  core/platforms/systemd/bareos-sd.service.in
  core/src/console/console.cc
  core/src/dird/dbcheck.cc
  core/src/dird/dbcheck_utils.cc
  core/src/dird/dird.cc
  core/src/filed/filed.cc
  core/src/include/exit_codes.h
  core/src/lib/cli.cc
  core/src/lib/cli.h
  core/src/lib/daemon.cc
  core/src/lib/message.cc
  core/src/lib/message_severity.h
  core/src/lib/parse_conf.cc
  core/src/lib/parse_conf.h
  core/src/lib/signal.cc
  core/src/qt-tray-monitor/tray-monitor.cc
  core/src/stored/bcopy.cc
  core/src/stored/bextract.cc
  core/src/stored/bls.cc
  core/src/stored/bscan.cc
  core/src/stored/btape.cc
  core/src/stored/stored.cc
  core/src/tests/dlist_test.cc
  core/src/tests/sd_backend_tests.h
  core/src/tests/sd_reservation.cc
  core/src/tests/test_config_parser_sd.cc
  core/src/tools/bregex.cc
  core/src/tools/bsmtp.cc
  core/src/tools/btestls.cc
  core/src/tools/bwild.cc
  core/src/tools/drivetype.cc
  core/src/tools/fstype.cc
  debian/bareos-director.service.in
  debian/bareos-filedaemon.service.in
  debian/bareos-storage.service.in
  systemtests/tests/bareos-basic/testrunner-bcopy-autoxflate
Labels: is a backport to 22

#1560 tools: fix tools not starting up on windows
  CHANGELOG.md
  core/src/dird/dird.cc
  core/src/filed/filed.cc
  core/src/lib/address_conf.cc
  core/src/stored/stored.cc
Labels: is a backport to 22

#1543 doc: renew tutorial, suggest passive client, restructure heartbeat interval
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/filed/filed_conf.cc
  core/src/stored/stored_conf.cc
  docs/manuals/source/Appendix/Troubleshooting.rst
  docs/manuals/source/IntroductionAndTutorial/Tutorial.rst
  docs/manuals/source/TasksAndConcepts/NetworkSetup.rst
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-fd-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-sd-config-schema.json
  docs/manuals/source/manually_added_config_directive_descriptions/console-console-HeartbeatInterval.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/console-director-HeartbeatInterval.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-client-HeartbeatInterval.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-client-Passive.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-director-HeartbeatInterval.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-director-MaximumConcurrentJobs.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-job-RescheduleOnError.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-storage-HeartbeatInterval.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/fd-client-HeartbeatInterval.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/sd-storage-HeartbeatInterval.rst.inc
Labels: documentation
