Repository bareos/bareos, pull requests merged in 2023-05, with the labels that each got.

#1453 docs: replace GZIP compression by LZ4 and MD5/SHA1 signature by XXH128
  CHANGELOG.md
  docs/manuals/source/Configuration/Director.rst
  docs/manuals/source/DeveloperGuide/Webui.rst
  docs/manuals/source/DeveloperGuide/pluginAPI.rst
  docs/manuals/source/TasksAndConcepts/AutomatedDiskBackup.rst
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/PostgreSQLPlugin.rst.inc
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
  docs/manuals/source/TasksAndConcepts/VolumeManagement.rst
Labels: documentation, requires backport to 22

#1458 docs: replace gzip by lz4 and md5/sha1 by xxh128
  CHANGELOG.md
  docs/manuals/source/Configuration/Director.rst
  docs/manuals/source/DeveloperGuide/Webui.rst
  docs/manuals/source/DeveloperGuide/pluginAPI.rst
  docs/manuals/source/TasksAndConcepts/AutomatedDiskBackup.rst
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/PostgreSQLPlugin.rst.inc
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
  docs/manuals/source/TasksAndConcepts/VolumeManagement.rst
Labels: documentation, is a backport to 22

#1455 bsmtp bls bextract: fixes for command line parsing
  CHANGELOG.md
  core/manpages/bsmtp.1
  core/src/stored/bextract.cc
  core/src/stored/bls.cc
  core/src/tools/bsmtp.cc
  docs/manuals/source/Appendix/BareosPrograms.rst
  docs/manuals/source/include/autogenerated/usage/bsmtp.txt
Labels: bugfix, requires backport to 22

#1457 bsmtp bls bextract: fixes for command line parsing
  CHANGELOG.md
  core/manpages/bsmtp.1
  core/src/stored/bextract.cc
  core/src/stored/bls.cc
  core/src/tools/bsmtp.cc
  docs/manuals/source/Appendix/BareosPrograms.rst
  docs/manuals/source/include/autogenerated/usage/bsmtp.txt
Labels: is a backport to 22

#1454 daemons: update network handling when IP protocols unavailable
  CHANGELOG.md
  core/src/lib/address_conf.cc
  core/src/lib/address_conf.h
  core/src/lib/bnet_server_tcp.cc
  core/src/tests/CMakeLists.txt
  core/src/tests/addresses_and_ports_config.cc
  core/src/tests/addresses_and_ports_functions.cc
  core/src/tests/dlist_test.cc
  core/src/tests/test_config_parser_dir.cc
  core/src/tests/test_config_parser_fd.cc
  core/src/win32/compat/include/mingwconfig.h
Labels: bugfix, requires backport to 22

#1465 packaging: systemd unit: set a limit of restart
  CHANGELOG.md
  core/platforms/systemd/bareos-dir.service.in
  core/platforms/systemd/bareos-fd.service.in
  core/platforms/systemd/bareos-sd.service.in
  debian/bareos-director.service.in
  debian/bareos-filedaemon.service.in
  debian/bareos-storage.service.in
  pull_request_template.md
Labels: is a backport to 22

#1463 daemons: update network handling when IP protocols unavailable
  CHANGELOG.md
  core/src/lib/address_conf.cc
  core/src/lib/address_conf.h
  core/src/lib/bnet_server_tcp.cc
  core/src/tests/CMakeLists.txt
  core/src/tests/addresses_and_ports_config.cc
  core/src/tests/addresses_and_ports_functions.cc
  core/src/tests/dlist_test.cc
  core/src/tests/run_on_incoming_connect_interval.cc
  core/src/tests/scheduler.cc
  core/src/tests/test_config_parser_dir.cc
  core/src/tests/test_config_parser_fd.cc
  core/src/tests/test_setdebug.cc
  core/src/win32/compat/include/mingwconfig.h
Labels: is a backport to 22

#1459 build: fix for gcc 13.1.1
  CHANGELOG.md
Labels: requires backport to 21, requires backport to 22

#1462 build: fix for gcc 13.1.1
  CHANGELOG.md
  core/src/cats/cats.h
  core/src/console/console_conf.cc
  core/src/lib/thread_list.cc
  core/src/lib/thread_specific_data_key.h
  core/src/stored/dev.cc
  core/src/tests/dlist_test.cc
Labels: is a backport to 21

#1461 build: fix for gcc 13.1.1
  CHANGELOG.md
Labels: is a backport to 22

#1450 packaging: systemd unit: set a limit of restart
  CHANGELOG.md
  core/platforms/systemd/bareos-dir.service.in
  core/platforms/systemd/bareos-fd.service.in
  core/platforms/systemd/bareos-sd.service.in
  debian/bareos-director.service.in
  debian/bareos-filedaemon.service.in
  debian/bareos-storage.service.in
  pull_request_template.md
Labels: requires backport to 22

#1470 build: remove openSUSE 15.3 and Univention 5.0 from test matrix
  .matrix.yml
  CHANGELOG.md
Labels: is a backport to 22

#1471 build: remove EOL distros from build matrix
  .matrix.yml
  CHANGELOG.md
Labels: is a backport to 21

#1472 build: remove EOL distros from build matrix
  .matrix.yml
  .quality-gates.yml
  CHANGELOG.md
  core/src/tests/CMakeLists.txt
  core/src/tests/bsock_test_connection_setup.cc
  core/src/tests/configs/dual_stacking/default_dir_values/bareos-dir.d/director/bareos-dir.conf
  core/src/tests/configs/dual_stacking/dir_port_set/bareos-dir.d/director/bareos-dir.conf
  core/src/tests/configs/dual_stacking/dir_v4address_and_port_set/bareos-dir.d/director/bareos-dir.conf
  core/src/tests/configs/dual_stacking/dir_v4address_set/bareos-dir.d/director/bareos-dir.conf
Labels: is a backport to 20
