Repository bareos/bareos, pull requests merged in 2023-01, with the labels that each got.

#1346 cats: fix issue where `startfile` field gets wrongly updated
  CHANGELOG.md
  core/src/cats/sql_create.cc
Labels: requires backport to 22

#1347 cats: fix issue where `startfile` field gets wrongly updated
  CHANGELOG.md
  core/src/cats/sql_create.cc
Labels: is a backport to 22

#1352 VMware Plugin: introduce pyVmomi 8.x compatibility
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/BareosFdPluginVMware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: requires backport to 22

#1354 docs: release note remove warning about binaries
  CHANGELOG.md
  docs/manuals/source/Appendix/ReleaseNotes.rst
  docs/manuals/source/IntroductionAndTutorial/WhatIsBareos.rst
Labels: documentation, requires backport to 22

#1358 VMware Plugin: introduce pyVmomi 8.x compatibility
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/BareosFdPluginVMware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: is a backport to 22

#1361 build: replace sprintf by snprintf due to upgraded MacOS compiler, change linking of googletest
  CHANGELOG.md
  core/src/findlib/bfile.cc
  core/src/lib/attr.cc
  core/src/lib/res.cc
  core/src/lib/signal.cc
  core/src/lib/util.cc
  core/src/lib/var.cc
  core/src/stored/CMakeLists.txt
Labels: requires backport to 22

#1362 build: replace sprintf by snprintf due to upgraded MacOS compiler, change linking of googletest
  CHANGELOG.md
  core/src/findlib/bfile.cc
  core/src/lib/attr.cc
  core/src/lib/res.cc
  core/src/lib/signal.cc
  core/src/lib/util.cc
  core/src/lib/var.cc
  core/src/stored/CMakeLists.txt
Labels: is a backport to 22

#1360 storage daemon: fix crash on volume swap
  CHANGELOG.md
  core/src/stored/vol_mgr.cc
Labels: bugfix, is a backport to 22

#1356 storage daemon: fix crash on volume swap
  CHANGELOG.md
  core/CMakeLists.txt
  core/src/droplet/libdroplet/CMakeLists.txt
  core/src/lib/CMakeLists.txt
  core/src/stored/backends/CMakeLists.txt
  core/src/stored/backends/autochanger_test_device.cc
  core/src/stored/backends/autochanger_test_device.h
  core/src/stored/backends/generic_tape_device.h
  core/src/stored/dev.h
  core/src/stored/vol_mgr.cc
  systemtests/tests/CMakeLists.txt
  systemtests/tests/file-autochanger/CMakeLists.txt
  systemtests/tests/file-autochanger/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/file-autochanger/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/file-autochanger/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/file-autochanger/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/file-autochanger/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/file-autochanger/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/file-autochanger/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf.in
  systemtests/tests/file-autochanger/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/file-autochanger/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/file-autochanger/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/file-autochanger/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/file-autochanger/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/file-autochanger/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/file-autochanger/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/file-autochanger/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/file-autochanger/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/file-autochanger/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/file-autochanger/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/file-autochanger/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/file-autochanger/etc/bareos/bareos-sd.d/autochanger/FileStorage.conf
  systemtests/tests/file-autochanger/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/file-autochanger/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/file-autochanger/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/file-autochanger/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/file-autochanger/etc/bareos/bconsole.conf.in
  systemtests/tests/file-autochanger/mtx-changer
  systemtests/tests/file-autochanger/mtx-inventory.txt
  systemtests/tests/file-autochanger/test-setup
  systemtests/tests/file-autochanger/testrunner-swapdev
Labels: bugfix, requires backport to 22

#1011 Enable Qt6 when present
  CHANGELOG.md
  core/src/qt-tray-monitor/CMakeLists.txt
  debian/control
  debian/control.src
Labels: jenkins_repotest_nodebug
