Repository bareos/bareos, pull requests merged in 2023-07, with the labels that each got.

#1466 cats: postgresql introduce pl/sql lstat_decode() function
  CHANGELOG.md
  core/src/cats/cats.h
  core/src/cats/ddl/creates/postgresql.sql
  core/src/cats/ddl/updates/postgresql.2210_2230.sql
  core/src/cats/ddl/versions.map.in
  core/src/cats/make_bareos_tables.in
  core/src/cats/update_bareos_tables.in
  core/src/dird/query.sql
Labels: jenkins_repotest_nodebug

#1502 cats: fix creates, grants and drops postgresql
  CHANGELOG.md
  core/src/cats/ddl/creates/postgresql.sql
  core/src/cats/ddl/drops/postgresql.sql
  core/src/cats/ddl/grants/postgresql.sql
Labels: bugfix

#1507 bsmtp: make mailhost and port message info a debug message
  CHANGELOG.md
  core/src/tools/bsmtp.cc
Labels: requires backport to 22

#1509 bsmtp: make mailhost and port message info a debug message
  CHANGELOG.md
  core/src/tools/bsmtp.cc
Labels: is a backport to 22
