Repository bareos/bareos, pull requests merged in 2023-11, with the labels that each got.

#1582 build: disable building for Windows 32-bit
  .gitignore
  .matrix.yml
  CHANGELOG.md
Labels: removal

#1578 catreq.cc: suppress missing batch con warning
  CHANGELOG.md
  core/src/dird/catreq.cc
Labels: bugfix, requires backport to 22

#1585 github actions: update/fix publish to PyPI workflows
  .github/workflows/publish-python-packages-to-pypi.yml
  .github/workflows/publish_python-bareos_to_pypi.yml
  .github/workflows/publish_python-bareos_to_test-pypi.yml
  .github/workflows/publish_restapi_to_pypi.yml
  .github/workflows/publish_restapi_to_test-pypi.yml
  CHANGELOG.md
  python-bareos/setup.py
  restapi/setup.py
Labels: is a backport to 22

#1586 github actions: update/fix publish to PyPI workflows
  .github/workflows/publish-python-packages-to-pypi.yml
  .github/workflows/publish_python-bareos_to_pypi.yml
  .github/workflows/publish_python-bareos_to_test-pypi.yml
  .github/workflows/publish_restapi_to_pypi.yml
  .github/workflows/publish_restapi_to_test-pypi.yml
  CHANGELOG.md
  python-bareos/setup.py
  restapi/setup.py
Labels: is a backport to 21

#1584 catreq.cc: suppress missing batch con warning
  CHANGELOG.md
  core/src/dird/catreq.cc
Labels: bugfix, is a backport to 22

#1576 autoxflate: fix autoxflate on replication
  CHANGELOG.md
  core/src/lib/mntent_cache.cc
  core/src/plugins/stored/autoxflate/autoxflate-sd.cc
  core/src/stored/device_resource.cc
  core/src/stored/mac.cc
  systemtests/scripts/functions
  systemtests/tests/CMakeLists.txt
  systemtests/tests/always-incremental-consolidate/testrunner
  systemtests/tests/autoxflate/CMakeLists.txt
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/job/copy.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/pool/Local.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/pool/Offsite.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/autoxflate/etc/bareos/bconsole.conf.in
  systemtests/tests/autoxflate/etc/sd-1/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/autoxflate/etc/sd-1/bareos-sd.d/device/FileStorage.conf~
  systemtests/tests/autoxflate/etc/sd-1/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/autoxflate/etc/sd-1/bareos-sd.d/messages/Standard.conf
  systemtests/tests/autoxflate/etc/sd-1/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/autoxflate/etc/sd-1/bareos-sd.d/storage/bareos-sd.conf.in~
  systemtests/tests/autoxflate/test-setup
  systemtests/tests/autoxflate/testrunner-copy-to-local
  systemtests/tests/autoxflate/testrunner-copy-to-offsite
  systemtests/tests/autoxflate/testrunner-create-backup
  systemtests/tests/autoxflate/testrunner-replication-local
  systemtests/tests/autoxflate/testrunner-replication-offsite
  systemtests/tests/copy-remote-bscan/testrunner
  systemtests/tests/restore/etc/bareos/bareos-dir.d/job/copy-full.conf.in
Labels: requires backport to 21, requires backport to 22

#1594 autoxflate: fix autoxflate on replication
  CHANGELOG.md
  core/src/lib/mntent_cache.cc
  core/src/plugins/stored/autoxflate/autoxflate-sd.cc
  core/src/stored/device_resource.cc
  core/src/stored/mac.cc
  systemtests/scripts/functions
  systemtests/tests/CMakeLists.txt
  systemtests/tests/autoxflate/CMakeLists.txt
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/job/copy.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/pool/Local.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/pool/Offsite.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/autoxflate/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/autoxflate/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/autoxflate/etc/bareos/bconsole.conf.in
  systemtests/tests/autoxflate/etc/sd-1/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/autoxflate/etc/sd-1/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/autoxflate/etc/sd-1/bareos-sd.d/messages/Standard.conf
  systemtests/tests/autoxflate/etc/sd-1/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/autoxflate/test-setup
  systemtests/tests/autoxflate/testrunner-copy-to-local
  systemtests/tests/autoxflate/testrunner-copy-to-offsite
  systemtests/tests/autoxflate/testrunner-create-backup
  systemtests/tests/autoxflate/testrunner-replication-local
  systemtests/tests/autoxflate/testrunner-replication-offsite
  systemtests/tests/copy-remote-bscan/testrunner
  systemtests/tests/restore/etc/bareos/bareos-dir.d/job/copy-full.conf.in
Labels: requires backport to 21, is a backport to 22

#1591 github actions: PyPi: install setuptools
  .github/workflows/publish-python-packages-to-pypi.yml
  CHANGELOG.md
Labels: is a backport to 21

#1603 Start development of Bareos 24
  CHANGELOG.md
  SECURITY.md
  docs/manuals/source/conf.py
Labels: documentation

#1589 github actions: PyPi: install setuptools
  .github/workflows/publish-python-packages-to-pypi.yml
  CHANGELOG.md
Labels: requires backport to 21, requires backport to 22

#1606 plugins: remove old deprecated postgres plugin
  CHANGELOG.md
  core/platforms/packaging/bareos.spec
  core/src/plugins/filed/python/CMakeLists.txt
  core/src/plugins/filed/python/postgres/bareos-fd-postgres.py
  debian/bareos-filedaemon-postgresql-python-plugin.install.in
  systemtests/tests/CMakeLists.txt
  systemtests/tests/py3plug-fd-postgres/CMakeLists.txt
  systemtests/tests/py3plug-fd-postgres/database/setup_local_db.sh.in
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-dir.d/fileset/PluginTest.conf.in
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-dir.d/fileset/PluginTestNoRole.conf.in
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-dir.d/fileset/PluginTestRole.conf.in
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/py3plug-fd-postgres/etc/bareos/bconsole.conf.in
  systemtests/tests/py3plug-fd-postgres/testrunner-default
  systemtests/tests/py3plug-fd-postgres/testrunner-roles
Labels: removal
