Repository bareos/bareos, pull requests merged in 2024-01, with the labels that each got.

#1642 plugins: fix cancel handling crash
  .matrix.yml
  CHANGELOG.md
  core/scripts/btraceback.in
  core/src/filed/dir_cmd.cc
  core/src/include/jcr.h
  core/src/lib/address_conf.cc
  core/src/lib/jcr.cc
  core/src/plugins/filed/python/module/bareosfd.cc
  core/src/plugins/filed/python/plugin_private_context.h
  core/src/plugins/filed/python/python-fd.cc
  core/src/plugins/stored/python/python-sd.cc
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/CancelFileset.conf.in
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/fileset/CancelNoWaitFileset.conf
  systemtests/tests/py3plug-fd-basic/etc/bareos/bareos-dir.d/job/cancel-check.conf
  systemtests/tests/py3plug-fd-basic/python-modules/cancel-check-module.py
  systemtests/tests/py3plug-fd-basic/testrunner-cancel-check
  systemtests/tests/py3plug-fd-basic/testrunner-cancel-check-no-wait
Labels: bugfix, is a backport to 23

#1636 core: add build patch for `sprintf` in macos builds
  .matrix.yml
  AUTHORS
  CHANGELOG.md
  core/src/tests/job_control_record.cc
Labels: requires backport to 21, requires backport to 22, requires backport to 23

#1646 python-bareos: use socket.create_connection() to allow AF_INET6
  CHANGELOG.md
  python-bareos/bareos/bsock/lowlevel.py
Labels: requires backport to 23

#1650 python-bareos: use socket.create_connection() to allow AF_INET6
  CHANGELOG.md
  python-bareos/bareos/bsock/lowlevel.py
Labels: is a backport to 23

#1651 core: add build patch for `sprintf` in macos builds
  AUTHORS
  CHANGELOG.md
  core/src/tests/job_control_record.cc
Labels: is a backport to 23

#1643 Improve FreeBSD build
  CHANGELOG.md
  cmake/BareosExtractVersionInfo.cmake
  core/cmake/BareosTimeFunctions.cmake
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/BareosCommonMakefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.database-postgresql
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.director-python-plugin
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.filedaemon-python3-plugin
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.storage-python-plugin
  core/platforms/freebsd/bareos-freebsd/bareos.com-filedaemon-python-plugins-common/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-filedaemon-python3-plugin/Makefile
  core/src/lib/jcr.cc
  systemtests/CMakeLists.txt
Labels: is a backport to 23

#1656 core: sql_* add leading space to sql construct
  CHANGELOG.md
  core/src/cats/bvfs.cc
  core/src/cats/sql_create.cc
  core/src/cats/sql_get.cc
  core/src/cats/sql_list.cc
  core/src/cats/sql_update.cc
Labels: requires backport to 22, requires backport to 23

#1645 Improve FreeBSD build
  .matrix.yml
  CHANGELOG.md
  cmake/BareosExtractVersionInfo.cmake
  core/cmake/BareosTimeFunctions.cmake
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/BareosCommonMakefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.director-python-plugin
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.filedaemon-python3-plugin
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.storage-python-plugin
  core/platforms/freebsd/bareos-freebsd/bareos.com-filedaemon-python-plugins-common/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-filedaemon-python3-plugin/Makefile
  core/src/lib/jcr.cc
  systemtests/CMakeLists.txt
Labels: is a backport to 21

#1644 Improve FreeBSD build
  .clang-format
  .matrix.yml
  CHANGELOG.md
  cmake/BareosExtractVersionInfo.cmake
  core/cmake/BareosTimeFunctions.cmake
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/BareosCommonMakefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.director-python-plugin
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.filedaemon-python3-plugin
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.storage-python-plugin
  core/platforms/freebsd/bareos-freebsd/bareos.com-filedaemon-python-plugins-common/Makefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-filedaemon-python3-plugin/Makefile
  core/src/lib/jcr.cc
  systemtests/CMakeLists.txt
Labels: is a backport to 22

#1657 core: sql_* add leading space to sql construct
  CHANGELOG.md
  core/src/cats/bvfs.cc
  core/src/cats/sql_create.cc
  core/src/cats/sql_get.cc
  core/src/cats/sql_list.cc
  core/src/cats/sql_update.cc
Labels: is a backport to 23

#1658 core: sql_* add leading space to sql construct
  CHANGELOG.md
  core/src/cats/bvfs.cc
  core/src/cats/sql_create.cc
  core/src/cats/sql_get.cc
  core/src/cats/sql_list.cc
  core/src/cats/sql_update.cc
Labels: is a backport to 22

#1659 Fix bareos_tasks plugin for pgsql
  AUTHORS
  CHANGELOG.md
  contrib/fd-plugins/bareos_tasks/BareosFdTaskClass.py
  contrib/fd-plugins/bareos_tasks/pgsql/BareosFdPgSQLClass.py
  contrib/fd-plugins/bareos_tasks/pgsql/README.md
  contrib/fd-plugins/bareos_tasks/pgsql/__init__.py
  systemtests/tests/py3plug-fd-postgresql/etc/bareos/bareos-dir.d/fileset/bareos_tasks_pgsql.conf.in
  systemtests/tests/py3plug-fd-postgresql/etc/bareos/bareos-dir.d/job/backup-bareos-fd-tasks-pgsql.conf
  systemtests/tests/py3plug-fd-postgresql/testrunner-tasks-pgsql
Labels: requires backport to 23

#1660 Fix bareos_tasks plugin for pgsql
  AUTHORS
  CHANGELOG.md
  contrib/fd-plugins/bareos_tasks/BareosFdTaskClass.py
  contrib/fd-plugins/bareos_tasks/pgsql/BareosFdPgSQLClass.py
  contrib/fd-plugins/bareos_tasks/pgsql/README.md
  contrib/fd-plugins/bareos_tasks/pgsql/__init__.py
  systemtests/tests/py3plug-fd-postgresql/etc/bareos/bareos-dir.d/fileset/bareos_tasks_pgsql.conf.in
  systemtests/tests/py3plug-fd-postgresql/etc/bareos/bareos-dir.d/job/backup-bareos-fd-tasks-pgsql.conf
  systemtests/tests/py3plug-fd-postgresql/testrunner-tasks-pgsql
Labels: is a backport to 23

#1652 core: add build patch for `sprintf` in macos builds
  AUTHORS
  CHANGELOG.md
  core/src/tests/job_control_record.cc
Labels: is a backport to 22

#1653 core: add build patch for `sprintf` in macos builds
  AUTHORS
  CHANGELOG.md
  core/src/tests/job_control_record.cc
Labels: is a backport to 21

#1655 plugins: postgresql fix missing pg_backup_stop() call
  CHANGELOG.md
  core/src/plugins/filed/python/postgresql/bareos-fd-postgresql.py
  systemtests/tests/py3plug-fd-postgresql/testrunner-default
Labels: requires backport to 23

#1664 plugins: postgresql fix missing pg_backup_stop() call
  CHANGELOG.md
  core/src/plugins/filed/python/postgresql/bareos-fd-postgresql.py
  systemtests/tests/py3plug-fd-postgresql/testrunner-default
Labels: is a backport to 23

#1672 bareos-config: fix output of deploy_config
  CHANGELOG.md
  core/scripts/bareos-config-lib.sh.in
Labels: requires backport to 22, requires backport to 23

#1671 Disable automated package-tests for SLES 12
  .matrix.yml
  CHANGELOG.md
Labels: requires backport to 21, requires backport to 22, requires backport to 23

#1673 bareos-config: fix output of deploy_config
  CHANGELOG.md
  core/scripts/bareos-config-lib.sh.in
Labels: is a backport to 23

#1674 bareos-config: fix output of deploy_config
  CHANGELOG.md
  core/scripts/bareos-config-lib.sh.in
Labels: is a backport to 22

#1677 Disable automated package-tests for SLES 12
  .matrix.yml
  CHANGELOG.md
Labels: is a backport to 21

#1676 Disable automated package-tests for SLES 12
  .matrix.yml
  CHANGELOG.md
Labels: is a backport to 22

#1675 Disable automated package-tests for SLES 12
  .matrix.yml
  CHANGELOG.md
Labels: is a backport to 23

#1666 filed: fix vss during client initiated connections
  CHANGELOG.md
  core/src/dird/backup.cc
  core/src/filed/dir_cmd.cc
  core/src/lib/berrno.cc
  core/src/tests/berrno_test.cc
  core/src/win32/filed/vss_generic.cc
Labels: is a backport to 23

#1668 filed: fix vss during client initiated connections
  CHANGELOG.md
  core/src/filed/dir_cmd.cc
  core/src/lib/berrno.cc
  core/src/tests/berrno_test.cc
Labels: is a backport to 21

#1647 Make BareosDirPluginPrometheusExporter.py work with python3
  CHANGELOG.md
  contrib/dir-plugins/prometheus/BareosDirPluginPrometheusExporter.py
Labels: requires backport to 23

#1667 filed: fix vss during client initiated connections
  CHANGELOG.md
  core/src/dird/backup.cc
  core/src/filed/dir_cmd.cc
  core/src/lib/berrno.cc
  core/src/tests/berrno_test.cc
Labels: is a backport to 22

#1679 Make BareosDirPluginPrometheusExporter.py work with python3
  CHANGELOG.md
  contrib/dir-plugins/prometheus/BareosDirPluginPrometheusExporter.py
Labels: is a backport to 23

#1670 Improve FreeBSD dependencies
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/BareosCommonMakefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-database-postgresql/Makefile
Labels: requires backport to 21, requires backport to 22, requires backport to 23

#1680 Improve FreeBSD dependencies
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/BareosCommonMakefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-database-postgresql/Makefile
Labels: is a backport to 23

#1682 Improve FreeBSD dependencies
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/BareosCommonMakefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-database-postgresql/Makefile
Labels: is a backport to 21

#1681 Improve FreeBSD dependencies
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/BareosCommonMakefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-database-postgresql/Makefile
Labels: is a backport to 22

#1692 macOS build workflow
  .github/workflows/build-macos.yml
Labels: is a backport to 21

#1683 add openssl 3 ulc
  .matrix.yml
  CHANGELOG.md
  docs/pkglists/ULC_deb_OpenSSL_1.1.i586
  docs/pkglists/ULC_deb_OpenSSL_3.0.x86_64
Labels: requires backport to 23

#1694 add openssl 3 ulc
  .matrix.yml
  CHANGELOG.md
  docs/pkglists/ULC_deb_OpenSSL_1.1.i586
  docs/pkglists/ULC_deb_OpenSSL_3.0.x86_64
Labels: is a backport to 23
