Repository bareos/bareos, pull requests merged in 2024-05, with the labels that each got.

#1805 docs: improve pluginAPI docs
  CHANGELOG.md
  docs/manuals/source/DeveloperGuide/pluginAPI.rst
Labels: documentation, requires backport to 23

#1806 docs: improve pluginAPI docs
  CHANGELOG.md
  docs/manuals/source/DeveloperGuide/pluginAPI.rst
Labels: documentation, is a backport to 23

#1808 replace https://bugs.bareos.org by https://github.com/bareos/bareos/issues/
  CHANGELOG.md
  README.md
  SPONSORS.md
  core/manpages/bareos.8
  core/manpages/bscrypto.8
  core/platforms/win32/mingw-debugsrc-devel.spec
  core/src/vmware/README.md
  docs/manuals/source/DeveloperGuide/generaldevel.rst
  docs/manuals/source/DocumentationStyleGuide/BareosSpecificFormatting/Links.rst
  docs/manuals/source/DocumentationStyleGuide/example/github-issue.rst.inc
  docs/manuals/source/IntroductionAndTutorial/WhatIsBareos.rst
  docs/manuals/source/_extensions/bareos_urls.py
  docs/manuals/source/conf.py
  webui/module/Application/view/layout/layout.phtml.in
  webui/module/Application/view/layout/login.phtml.in
  webui/module/Director/view/director/director/subscription.phtml
Labels: requires backport to 22, requires backport to 23

#1813 replace https://bugs.bareos.org by https://github.com/bareos/bareos/issues/
  CHANGELOG.md
  README.md
  SPONSORS.md
  core/manpages/bareos.8
  core/manpages/bscrypto.8
  core/platforms/win32/mingw-debugsrc-devel.spec
  core/src/vmware/README.md
  docs/manuals/source/DeveloperGuide/generaldevel.rst
  docs/manuals/source/DocumentationStyleGuide/BareosSpecificFormatting/Links.rst
  docs/manuals/source/DocumentationStyleGuide/example/github-issue.rst.inc
  docs/manuals/source/IntroductionAndTutorial/WhatIsBareos.rst
  docs/manuals/source/_extensions/bareos_urls.py
  docs/manuals/source/conf.py
  webui/module/Application/view/layout/layout.phtml.in
  webui/module/Application/view/layout/login.phtml.in
  webui/module/Director/view/director/director/subscription.phtml
Labels: is a backport to 23

#1814 replace https://bugs.bareos.org by https://github.com/bareos/bareos/issues/
  CHANGELOG.md
  README.md
  SPONSORS.md
  core/manpages/bareos.8
  core/manpages/bscrypto.8
  core/platforms/win32/mingw-debugsrc-devel.spec
  core/src/vmware/README.md
  docs/manuals/source/DeveloperGuide/generaldevel.rst
  docs/manuals/source/DocumentationStyleGuide/BareosSpecificFormatting/Links.rst
  docs/manuals/source/DocumentationStyleGuide/example/github-issue.rst.inc
  docs/manuals/source/IntroductionAndTutorial/WhatIsBareos.rst
  docs/manuals/source/_extensions/bareos_urls.py
  docs/manuals/source/conf.py
  webui/module/Application/view/layout/layout.phtml.in
  webui/module/Application/view/layout/login.phtml.in
  webui/module/Director/view/director/director/subscription.phtml
Labels: is a backport to 22

#1807 Fix missing DLL in windows packaging
  CHANGELOG.md
  core/platforms/win32/winbareos.nsi
Labels: bugfix, requires backport to 21, requires backport to 22, requires backport to 23

#1818 Fix missing DLL in windows packaging
  CHANGELOG.md
  core/platforms/win32/winbareos.nsi
Labels: bugfix, is a backport to 22

#1819 Fix missing DLL in windows packaging
  CHANGELOG.md
  core/platforms/win32/winbareos.nsi
Labels: bugfix, is a backport to 21

#1654 tools: add dedup estimation tool `bdedupestimate`
  CHANGELOG.md
  core/platforms/packaging/bareos.spec
  core/src/dird/msgchan.cc
  core/src/dird/vbackup.cc
  core/src/lib/crypto.h
  core/src/lib/message.cc
  core/src/lib/message.h
  core/src/stored/block.cc
  core/src/stored/bsr.cc
  core/src/tools/CMakeLists.txt
  core/src/tools/bdedup-estimate.cc
  core/src/tools/gentestdata.cc
  debian/bareos-tools.install.in
  docs/manuals/CMakeLists.txt
  docs/manuals/source/Appendix/BareosPrograms.rst
  docs/manuals/source/include/autogenerated/usage/bdedupestimate.txt
  docs/manuals/source/man/bdedupestimate.rst
  systemtests/CMakeLists.txt
  systemtests/environment.in
  systemtests/scripts/functions
  systemtests/tests/CMakeLists.txt
  systemtests/tests/bareos-basic/test-setup
  systemtests/tests/dedupestimate/CMakeLists.txt
  systemtests/tests/dedupestimate/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/dedupestimate/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/dedupestimate/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/dedupestimate/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/dedupestimate/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/dedupestimate/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/dedupestimate/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/dedupestimate/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/dedupestimate/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/dedupestimate/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/dedupestimate/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/dedupestimate/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/dedupestimate/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/dedupestimate/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/dedupestimate/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/dedupestimate/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/dedupestimate/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/dedupestimate/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/dedupestimate/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/dedupestimate/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/dedupestimate/etc/bareos/bareos-sd.d/device/FileStorage2.conf
  systemtests/tests/dedupestimate/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/dedupestimate/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/dedupestimate/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/dedupestimate/etc/bareos/bconsole.conf.in
  systemtests/tests/dedupestimate/functions
  systemtests/tests/dedupestimate/test-setup
  systemtests/tests/dedupestimate/testrunner-create-backup
  systemtests/tests/dedupestimate/testrunner-do-estimation
Labels: enhancement

#1821 Build ULC and EL_9 for aarch64
  .matrix.yml
  CHANGELOG.md
  docs/pkglists/EL_9.aarch64
  docs/pkglists/ULC_deb_OpenSSL_1.1.aarch64
  docs/pkglists/ULC_deb_OpenSSL_3.0.aarch64
Labels: enhancement, requires backport to 23

#1817 Fix missing DLL in windows packaging
  CHANGELOG.md
  core/platforms/win32/winbareos.nsi
Labels: bugfix, is a backport to 23

#1810 VMware Plugin: Adapt to older urllib3 versions
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/bareos-fd-vmware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: bugfix, requires backport to 23

#1827 Build ULC and EL_9 for aarch64
  .matrix.yml
  CHANGELOG.md
  docs/pkglists/ULC_deb_OpenSSL_1.1.aarch64
  docs/pkglists/ULC_deb_OpenSSL_3.0.aarch64
Labels: enhancement, is a backport to 23

#1831 VMware Plugin: Adapt to older urllib3 versions
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/bareos-fd-vmware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: bugfix, is a backport to 23

#1809 webui: fix and improve update check
  CHANGELOG.md
  webui/module/Api/src/Api/Controller/ClientController.php
  webui/module/Application/Module.php
  webui/module/Application/src/Application/View/Helper/UpdateAlert.php
  webui/module/Application/view/layout/layout.phtml.in
  webui/module/Auth/src/Auth/Controller/AuthController.php
  webui/module/Auth/view/auth/auth/login.phtml
  webui/module/Director/view/director/director/index.phtml
  webui/vendor/Bareos/library/Bareos/Util.php
Labels: requires backport to 23

#1833 webui: fix and improve update check
  CHANGELOG.md
  webui/module/Api/src/Api/Controller/ClientController.php
  webui/module/Application/Module.php
  webui/module/Application/src/Application/View/Helper/UpdateAlert.php
  webui/module/Application/view/layout/layout.phtml.in
  webui/module/Auth/src/Auth/Controller/AuthController.php
  webui/module/Auth/view/auth/auth/login.phtml
  webui/module/Director/view/director/director/index.phtml
  webui/vendor/Bareos/library/Bareos/Util.php
Labels: is a backport to 23

#1723 fix various memory leaks
  CHANGELOG.md
  core/src/cats/postgresql.cc
  core/src/console/console.cc
  core/src/dird/admin.cc
  core/src/dird/archive.cc
  core/src/dird/consolidate.cc
  core/src/dird/dbcheck.cc
  core/src/dird/dbcheck_utils.cc
  core/src/dird/dbcheck_utils.h
  core/src/dird/director_jcr_impl.h
  core/src/dird/fd_cmds.cc
  core/src/dird/job.cc
  core/src/dird/ua_restore.cc
  core/src/dird/verify.cc
  core/src/filed/backup.cc
  core/src/lib/parse_conf_state_machine.cc
  core/src/lib/runscript.cc
  core/src/plugins/dird/python/python-dir.cc
  core/src/plugins/stored/python/python-sd.cc
  core/src/stored/acquire.cc
  core/src/tests/CMakeLists.txt
  core/src/tests/test_config_parser_dir.cc
  systemtests/scripts/functions
  systemtests/tests/CMakeLists.txt
  systemtests/tests/dbcheck/CMakeLists.txt
  systemtests/tests/dbcheck/test-setup
  systemtests/tests/dbcheck/testrunner-duplicate-paths
Labels: bugfix, requires backport to 23
