Repository bareos/bareos, pull requests merged in 2024-12, with the labels that each got.

#2044 stored: explicitly flush after labeling
  CHANGELOG.md
  core/src/stored/backends/chunked_device.cc
  core/src/stored/label.cc
Labels: bugfix, is a backport to 23, bug

#2008 mssql TearDownVdiDevice(): enhance error reporting
  CHANGELOG.md
  core/src/win32/plugins/filed/mssqlvdi-fd.cc
Labels: enhancement

#2023 JSON API: make sure, strings are valid UTF8
  CHANGELOG.md
  cmake/BareosCpmPackages.cmake
  cmake/Findutf8cpp.cmake
  core/src/lib/CMakeLists.txt
  core/src/lib/output_formatter.cc
  systemtests/tests/python-bareos/test_json.py
  systemtests/tests/python-bareos/test_list_command.py
Labels: is a backport to 23, bug

#2037 docs: add worm support paragraph
  CHANGELOG.md
  docs/manuals/source/DeveloperGuide/mediaformat.rst
  docs/manuals/source/IntroductionAndTutorial/Tutorial.rst
  docs/manuals/source/TasksAndConcepts/AutochangerSupport.rst
  docs/manuals/source/TasksAndConcepts/NdmpBackupsWithBareos.rst
  docs/manuals/source/TasksAndConcepts/TheWindowsVersionOfBareos.rst
Labels: documentation, requires backport to 23

#2054 docs: add worm support paragraph
  CHANGELOG.md
  docs/manuals/source/DeveloperGuide/mediaformat.rst
  docs/manuals/source/IntroductionAndTutorial/Tutorial.rst
  docs/manuals/source/TasksAndConcepts/AutochangerSupport.rst
  docs/manuals/source/TasksAndConcepts/NdmpBackupsWithBareos.rst
  docs/manuals/source/TasksAndConcepts/TheWindowsVersionOfBareos.rst
Labels: documentation, is a backport to 23

#1862 NDMP_NATIVE: enable full restore, eject tape before unload, enable update of NDMP environment
  CHANGELOG.md
  core/src/cats/sql_create.cc
  core/src/dird/ndmp_dma_backup_NDMP_NATIVE.cc
  core/src/dird/ndmp_dma_generic.cc
  core/src/dird/ndmp_dma_restore_NDMP_NATIVE.cc
  core/src/dird/ndmp_dma_storage.cc
  core/src/ndmp/ndma_cops_backreco.c
  systemtests/tests/CMakeLists.txt
  systemtests/tests/ndmp-bareos/CMakeLists.txt
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/client/isilon.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/fileset/isilon-fileset.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/job/NDMPRestoreDump.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/job/isilondump.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/job/ndmp-copy-isilon.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/jobdefs/DefaultNDMPJob.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/jobdefs/DefaultNDMPRestoreJob.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/pool/isilon-copy.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/pool/isilon.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/storage/ndmp.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-sd.d/device/FileStorage2.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-sd.d/ndmp/ndmp.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bconsole.conf.in
  systemtests/tests/ndmp-bareos/testrunner
Labels: requires backport to 23

#2006 lib: add source_location; fix test crash
  CHANGELOG.md
  core/CMakeLists.txt
  core/cmake/BareosCheckFunctions.cmake
  core/src/cats/bvfs.cc
  core/src/cats/cats.h
  core/src/cats/postgresql.cc
  core/src/cats/sql.cc
  core/src/cats/sql_create.cc
  core/src/cats/sql_delete.cc
  core/src/cats/sql_find.cc
  core/src/cats/sql_get.cc
  core/src/cats/sql_list.cc
  core/src/cats/sql_update.cc
  core/src/dird/msgchan.cc
  core/src/dird/restore.cc
  core/src/include/config.h.in
  core/src/lib/rwlock.cc
  core/src/lib/rwlock.h
  core/src/lib/source_location.h
  core/src/tests/wrap.cc
Labels: bugfix, bug

#2057 Required changes for major release after branching bareos-24
  CHANGELOG.md
  SECURITY.md
  docs/manuals/source/conf.py
Labels: nobuild

#2058 readme.md: switch to anniversary banner
  README.md
  bareos-github-banner.png
Labels: nobuild

#2065 cats: fix version.map.in
  CHANGELOG.md
  core/src/cats/ddl/versions.map.in
Labels: bugfix, is a backport to 24

#2064 cats: fix version.map.in
  CHANGELOG.md
  core/src/cats/ddl/versions.map.in
Labels: bugfix

#2069 docs: fix grpc-fd plugin call
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/GrpcPlugin.rst.inc
Labels: documentation, is a backport to 24

#2067 webui: fix for PHP < 7.3
  CHANGELOG.md
  webui/module/Restore/src/Restore/Controller/RestoreController.php
  webui/module/Restore/view/restore/restore/index.phtml
  webui/module/Restore/view/restore/restore/versions.phtml
  webui/tests/selenium/webui-selenium-test.py
Labels: bugfix, bug, requires backport to 24

#2066 plugins: Fix typo in postgresql plugin
  CHANGELOG.md
  core/src/plugins/filed/python/postgresql/bareos-fd-postgresql.py
Labels: requires backport to 24

#2071 plugins: Fix typo in postgresql plugin
  CHANGELOG.md
  core/src/plugins/filed/python/postgresql/bareos-fd-postgresql.py
Labels: is a backport to 24

#2070 webui: fix for PHP < 7.3
  CHANGELOG.md
  webui/module/Restore/src/Restore/Controller/RestoreController.php
  webui/module/Restore/view/restore/restore/index.phtml
  webui/module/Restore/view/restore/restore/versions.phtml
  webui/tests/selenium/webui-selenium-test.py
Labels: bugfix, bug, is a backport to 24

#2075 macos: update build environment
  .github/workflows/build-macos.yml
  CHANGELOG.md
Labels: is a backport to 22

#2040 cmake: fix MARIADB_MYSQL_INSTALL_DB_SCRIPT usage
  CHANGELOG.md
  core/cmake/BareosFindPrograms.cmake
  systemtests/environment.in
  systemtests/scripts/mysql.sh
  systemtests/tests/py3plug-fd-mariabackup/CMakeLists.txt
  systemtests/tests/py3plug-fd-mariabackup/testrunner-default
Labels: bugfix, bug, requires backport to 24

#2074 macos: update build environment
  .github/workflows/build-macos.yml
  CHANGELOG.md
Labels: is a backport to 23

#2049 plugins: postgresql add support for PostgreSQL 17 + improvements
  CHANGELOG.md
  core/src/plugins/filed/python/postgresql/bareos-fd-postgresql.py
  systemtests/tests/py3plug-fd-postgresql/CMakeLists.txt
  systemtests/tests/py3plug-fd-postgresql/database/setup_local_db.sh
Labels: bugfix, is a backport to 23

#2034 dedupable device: fix example files
  CHANGELOG.md
  core/platforms/packaging/bareos.spec
  core/src/stored/backends/dedupable_device.d/bareos-dir.d/storage/Dedupable.conf.example.in
  core/src/stored/backends/dedupable_device.d/bareos-dir.d/storage/dedup.conf.example
  core/src/stored/backends/dedupable_device.d/bareos-sd.d/device/Dedupable.conf.example.in
  debian/bareos-storage-dedupable.install.in
Labels: is a backport to 23

#2077 cmake: fix MARIADB_MYSQL_INSTALL_DB_SCRIPT usage
  CHANGELOG.md
  core/cmake/BareosFindPrograms.cmake
  systemtests/environment.in
  systemtests/scripts/mysql.sh
  systemtests/tests/py3plug-fd-mariabackup/CMakeLists.txt
  systemtests/tests/py3plug-fd-mariabackup/testrunner-default
Labels: bugfix, bug, is a backport to 24

#2017 NDMP_NATIVE: enable full restore, eject tape before unload, enable update of NDMP environment
  CHANGELOG.md
  core/src/cats/sql_create.cc
  core/src/dird/ndmp_dma_backup_NDMP_NATIVE.cc
  core/src/dird/ndmp_dma_generic.cc
  core/src/dird/ndmp_dma_restore_NDMP_NATIVE.cc
  core/src/dird/ndmp_dma_storage.cc
  core/src/ndmp/ndma_cops_backreco.c
  core/src/stored/stored_conf.cc
  docs/manuals/source/include/autogenerated/bareos-sd-config-schema.json
  systemtests/tests/CMakeLists.txt
  systemtests/tests/ndmp-bareos/CMakeLists.txt
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/client/isilon.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/fileset/isilon-fileset.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/job/NDMPRestoreDump.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/job/isilondump.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/job/ndmp-copy-isilon.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/jobdefs/DefaultNDMPJob.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/jobdefs/DefaultNDMPRestoreJob.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/pool/isilon-copy.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/pool/isilon.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-dir.d/storage/ndmp.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-sd.d/device/FileStorage2.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-sd.d/ndmp/ndmp.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/ndmp-bareos/etc/bareos/bconsole.conf.in
  systemtests/tests/ndmp-bareos/testrunner
Labels: is a backport to 23

#2079 Fix building ndmjob program
  CHANGELOG.md
  core/src/ndmp/ndmjob_args.c
Labels: requires backport to 24

#2084 Fix building ndmjob program
  CHANGELOG.md
  core/src/ndmp/ndmjob_args.c
Labels: is a backport to 24

#2086 Sync EvpDigest between OpenSSL <1.1 and 1.1+
  CHANGELOG.md
  core/src/lib/crypto_openssl.cc
Labels: requires backport to 24

#2087 Sync EvpDigest between OpenSSL <1.1 and 1.1+
  core/src/lib/crypto_openssl.cc
Labels: is a backport to 24

#2076 winbareos-native.nsi: do not package python3 plugins
  .matrix.yml
  CHANGELOG.md
  core/CMakeLists.txt
  core/cmake/BareosFindAllLibraries.cmake
  core/cmake/BareosGetDistInfo.cmake
  core/platforms/win32/winbareos-native.nsi
  core/src/include/config.h.in
  core/src/tests/CMakeLists.txt
  core/src/win32/compat/include/mingwconfig.h
Labels: requires backport to 24
