Repository bareos/bareos, pull requests merged in 2024-04, with the labels that each got.

#1752 doc: add backtick around *.?* description
  CHANGELOG.md
  docs/manuals/scripts/generate-resource-descriptions.py
  systemtests/tests/bareos-acl/etc/bareos/bareos-dir.d/console/bareos-acl-restricted.conf.in
Labels: requires backport to 23

#1757 doc: add backtick around *.?* description
  CHANGELOG.md
  docs/manuals/scripts/generate-resource-descriptions.py
  systemtests/tests/bareos-acl/etc/bareos/bareos-dir.d/console/bareos-acl-restricted.conf.in
Labels: is a backport to 23

#1762 PR template: remove backport hints
  CHANGELOG.md
  pull_request_template.md
Labels: nobuild

#1756 python-bareos: use TLS-PSK from core ssl module (available since Python >= 3.13)
  CHANGELOG.md
  docs/manuals/source/DeveloperGuide.rst
  python-bareos/README.rst
  python-bareos/bareos/bsock/__init__.py
  python-bareos/bareos/bsock/directorconsole.py
  python-bareos/bareos/bsock/lowlevel.py
  python-bareos/bareos/bsock/protocolversions.py
  python-bareos/bareos/bsock/tlsversionparser.py
  python-bareos/bareos/util/argparse.py
  python-bareos/setup.py
Labels: enhancement, requires backport to 23

#1743 Fix warning about missing delcandidates table in director
  AUTHORS
  CHANGELOG.md
  core/src/cats/cats.h
  core/src/cats/postgresql.cc
  core/src/cats/postgresql.h
  core/src/tests/run_on_incoming_connect_interval.cc
Labels: bugfix, is a backport to 23

#1764 python-bareos: use TLS-PSK from core ssl module (available since Python >= 3.13)
  CHANGELOG.md
  docs/manuals/source/DeveloperGuide.rst
  python-bareos/README.rst
  python-bareos/bareos/bsock/__init__.py
  python-bareos/bareos/bsock/directorconsole.py
  python-bareos/bareos/bsock/lowlevel.py
  python-bareos/bareos/bsock/protocolversions.py
  python-bareos/bareos/bsock/tlsversionparser.py
  python-bareos/bareos/util/argparse.py
  python-bareos/setup.py
Labels: enhancement, is a backport to 23

#1761 docs: improve handling of ResourceItem descriptions
  CHANGELOG.md
  CMakeLists.txt
  core/src/lib/resource_item.h
  core/src/lib/tls_resource_items.h
  docs/manuals/scripts/generate-resource-descriptions.py
  docs/manuals/source/DocumentationStyleGuide/BareosSpecificFormatting/BareosConfiguration.rst
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-fd-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-sd-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-tray-monitor-config-schema.json
  docs/manuals/source/include/autogenerated/bconsole-config-schema.json
Labels: requires backport to 23

#1766 docs: improve handling of ResourceItem descriptions
  CHANGELOG.md
  CMakeLists.txt
  core/src/lib/resource_item.h
  core/src/lib/tls_resource_items.h
  docs/manuals/scripts/generate-resource-descriptions.py
  docs/manuals/source/DocumentationStyleGuide/BareosSpecificFormatting/BareosConfiguration.rst
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-fd-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-sd-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-tray-monitor-config-schema.json
  docs/manuals/source/include/autogenerated/bconsole-config-schema.json
Labels: is a backport to 23

#1771 stored: fix some sd error messages; add additional check during restore; split up always-incremental-consolidate test
  CHANGELOG.md
  core/src/stored/ansi_label.cc
  core/src/stored/mount.cc
  systemtests/environment.in
  systemtests/tests/gfapi-fd/testrunner
  systemtests/tests/py2plug-fd-percona-xtrabackup/testrunner
Labels: is a backport to 21

#1770 stored: fix some sd error messages; add additional check during restore; split up always-incremental-consolidate test
  CHANGELOG.md
  core/src/stored/ansi_label.cc
  core/src/stored/mount.cc
  systemtests/environment.in
  systemtests/tests/gfapi-fd/testrunner
  systemtests/tests/restore/CMakeLists.txt
  systemtests/tests/restore/testrunner-archive-restore-dir
  systemtests/tests/restore/testrunner-check-hints
  systemtests/tests/restore/testrunner-create-backup
  systemtests/tests/restore/testrunner-full-restore
  systemtests/tests/restore/testrunner-restore-dir
  systemtests/tests/restore/testrunner-restore-file
  systemtests/tests/restore/testrunner-restore-old-archive
Labels: is a backport to 22

#1772 Allow cross-building for Windows on newer compiler
  CHANGELOG.md
  core/src/stored/backends/win32_tape_device.cc
  core/src/win32/compat/include/compat.h
  core/src/win32/filed/vss_generic.cc
  core/src/win32/plugins/filed/mssqlvdi-fd.cc
Labels: requires backport to 21, requires backport to 22, requires backport to 23

#1776 Allow cross-building for Windows on newer compiler
  CHANGELOG.md
  core/src/stored/backends/win32_tape_device.cc
  core/src/win32/compat/include/compat.h
  core/src/win32/filed/vss_generic.cc
  core/src/win32/plugins/filed/mssqlvdi-fd.cc
Labels: is a backport to 23

#1778 Allow cross-building for Windows on newer compiler
  CHANGELOG.md
  core/src/win32/compat/include/compat.h
  core/src/win32/filed/vss_generic.cc
  core/src/win32/plugins/filed/mssqlvdi-fd.cc
  core/src/win32/stored/backends/win32_tape_device.cc
Labels: is a backport to 21

#1777 Allow cross-building for Windows on newer compiler
  CHANGELOG.md
  core/src/stored/backends/win32_tape_device.cc
  core/src/win32/compat/include/compat.h
  core/src/win32/filed/vss_generic.cc
  core/src/win32/plugins/filed/mssqlvdi-fd.cc
Labels: is a backport to 22

#1755 infra : GitHub community addition
  .github/ISSUE_TEMPLATE/config.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: nobuild, documentation

#1754 stored: fix wrong file counting in migrate and copy jobs with autoxflate
  CHANGELOG.md
  core/src/dird/msgchan.cc
  core/src/lib/jcr.cc
  core/src/stored/block.cc
  core/src/stored/mac.cc
  core/src/stored/ndmp_tape.cc
  core/src/stored/read_record.cc
  core/src/stored/read_record.h
  core/src/stored/record.cc
  core/src/stored/record.h
Labels: bugfix, is a backport to 22

#1765 Add FreeBSD 13.3 and 14.0
  .matrix.yml
  CHANGELOG.md
  core/platforms/freebsd/bareos-dir.in
  core/platforms/freebsd/bareos-fd.in
  core/platforms/freebsd/bareos-sd.in
Labels: enhancement, requires backport to 23

#1779 Add FreeBSD 13.3 and 14.0
  .matrix.yml
  CHANGELOG.md
  core/platforms/freebsd/bareos-dir.in
  core/platforms/freebsd/bareos-fd.in
  core/platforms/freebsd/bareos-sd.in
Labels: enhancement, is a backport to 23
