Repository bareos/bareos, pull requests merged in 2024-07, with the labels that each got.

#1847 Use only MinGW VSS
  CHANGELOG.md
  core/src/filed/filed.h
  core/src/win32/filed/vss_generic.cc
  core/src/win32/include/vss_client.h
Labels: enhancement

#1850 VMware Plugin: Adapt to Python 3.12
  CHANGELOG.md
  core/cmake/get_python_compile_settings.py
  core/src/plugins/filed/python/vmware/bareos-fd-vmware.py
Labels: requires backport to 23

#1879 VMware Plugin: Adapt to Python 3.12
  CHANGELOG.md
  core/cmake/get_python_compile_settings.py
  core/src/plugins/filed/python/vmware/bareos-fd-vmware.py
Labels: is a backport to 23

#1884 freebsd: fix build issues with ports tree 2024Q3
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/BareosCommonMakefile
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.common
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.database-tools
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.director
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.filedaemon
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.storage
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.storage-tape
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.tools
Labels: is a backport to 23

#1878 docs: improve Restoring a Bareos Server section
  AUTHORS
  CHANGELOG.md
  docs/manuals/source/Appendix/DisasterRecoveryUsingBareos.rst
Labels: documentation, requires backport to 23

#1869 create_bareos_database: fix `db_name` not being double quoted
  CHANGELOG.md
  core/src/cats/create_bareos_database.in
Labels: bugfix, is a backport to 23

#1857 dir: fix crash on purge with job without client
  CHANGELOG.md
  core/src/dird/ua_purge.cc
Labels: bugfix, requires backport to 23, bug

#1886 docs: improve Restoring a Bareos Server section
  AUTHORS
  CHANGELOG.md
  docs/manuals/source/Appendix/DisasterRecoveryUsingBareos.rst
Labels: documentation, is a backport to 23

#1870 create_bareos_database: fix `db_name` not being double quoted
  CHANGELOG.md
  core/src/cats/create_bareos_database.in
Labels: bugfix, is a backport to 22

#1861 dir: fix crash on purge with job without client
  CHANGELOG.md
  core/src/dird/ua_purge.cc
Labels: bugfix, is a backport to 23, bug

#1872 fix runtime status
  CHANGELOG.md
  core/src/dird/dird.h
  core/src/dird/dird_conf.cc
  core/src/dird/dird_conf.h
  core/src/dird/director_jcr_impl.h
  core/src/dird/ndmp_dma_storage.cc
  core/src/dird/storage.cc
  systemtests/tests/CMakeLists.txt
  systemtests/tests/bareos-concurrency/CMakeLists.txt
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/client/client-concurrent2.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/client/client-concurrent9.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/job/test-client-concurrency.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/job/test-job-concurrency.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/job/test-storage-concurrency.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/storage/File-Concurrent2.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/storage/File-Concurrent9.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bconsole.conf.in
  systemtests/tests/bareos-concurrency/flock-latch
  systemtests/tests/bareos-concurrency/test-concurrency-common
  systemtests/tests/bareos-concurrency/testrunner-client-concurrency
  systemtests/tests/bareos-concurrency/testrunner-job-concurrency
  systemtests/tests/bareos-concurrency/testrunner-storage-concurrency
Labels: requires backport to 23, bug

#1875 Fix multiple ACL handling bugs
  .gitignore
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/dird/ua_acl.cc
  core/src/dird/ua_cmds.cc
  core/src/dird/ua_run.cc
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  docs/manuals/source/manually_added_config_directive_descriptions/dir-console-WhereAcl.rst.inc
  python-bareos/.gitignore
  systemtests/python-modules/bareos_unittest/json.py
  systemtests/tests/CMakeLists.txt
  systemtests/tests/config-syntax-crash/CMakeLists.txt
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/config-syntax-crash/testrunner
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/console/client-bareos-fd.conf
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/console/limited-operator.conf
  systemtests/tests/python-bareos/etc/bareos/bconsole-limited-operator.conf.in
  systemtests/tests/python-bareos/list_unittests.py
  systemtests/tests/python-bareos/test_acl.py
  systemtests/tests/python-bareos/test_json_config.py
Labels: bugfix, requires backport to 21, requires backport to 22, requires backport to 23

#1871 Update ReaR documentation
  CHANGELOG.md
  contrib/misc/rear/etc/bareos/bareos-dir.d/profile/rear-client-profile.conf
  contrib/misc/rear/update-rear-rescue.sh
  docs/manuals/source/Appendix/DisasterRecoveryUsingBareos.rst
  docs/manuals/source/Configuration/Console.rst
  docs/manuals/source/DocumentationStyleGuide/CommonNames.rst
  docs/manuals/source/TasksAndConcepts/DataEncryption.rst
  docs/manuals/source/TasksAndConcepts/TransportEncryption.rst
  docs/manuals/source/include/config/rear-client-profile.conf
  python-bareos/bin/bareos-fd-connect.py
Labels: documentation, requires backport to 22, requires backport to 23

#1874 fix runtime status
  CHANGELOG.md
  core/src/dird/dird.h
  core/src/dird/dird_conf.cc
  core/src/dird/dird_conf.h
  core/src/dird/director_jcr_impl.h
  core/src/dird/ndmp_dma_storage.cc
  core/src/dird/storage.cc
  systemtests/tests/CMakeLists.txt
  systemtests/tests/bareos-concurrency/CMakeLists.txt
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/client/client-concurrent2.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/client/client-concurrent9.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/job/test-client-concurrency.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/job/test-job-concurrency.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/job/test-storage-concurrency.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/storage/File-Concurrent2.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/storage/File-Concurrent9.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/bareos-concurrency/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/bareos-concurrency/etc/bareos/bconsole.conf.in
  systemtests/tests/bareos-concurrency/flock-latch
  systemtests/tests/bareos-concurrency/test-concurrency-common
  systemtests/tests/bareos-concurrency/testrunner-client-concurrency
  systemtests/tests/bareos-concurrency/testrunner-job-concurrency
  systemtests/tests/bareos-concurrency/testrunner-storage-concurrency
Labels: is a backport to 23, bug

#1891 Fix multiple ACL handling bugs
  .gitignore
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/dird/ua_acl.cc
  core/src/dird/ua_cmds.cc
  core/src/dird/ua_run.cc
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  docs/manuals/source/manually_added_config_directive_descriptions/dir-console-WhereAcl.rst.inc
  python-bareos/.gitignore
  systemtests/python-modules/bareos_unittest/json.py
  systemtests/tests/CMakeLists.txt
  systemtests/tests/config-syntax-crash/CMakeLists.txt
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/config-syntax-crash/testrunner
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/console/client-bareos-fd.conf
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/console/limited-operator.conf
  systemtests/tests/python-bareos/etc/bareos/bconsole-limited-operator.conf.in
  systemtests/tests/python-bareos/list_unittests.py
  systemtests/tests/python-bareos/test_acl.py
  systemtests/tests/python-bareos/test_json_config.py
Labels: bugfix, is a backport to 22

#1892 Fix multiple ACL handling bugs
  .gitignore
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/dird/ua_acl.cc
  core/src/dird/ua_cmds.cc
  core/src/dird/ua_run.cc
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  docs/manuals/source/manually_added_config_directive_descriptions/dir-console-WhereAcl.rst.inc
  python-bareos/.gitignore
  systemtests/python-modules/bareos_unittest/json.py
  systemtests/tests/CMakeLists.txt
  systemtests/tests/config-syntax-crash/CMakeLists.txt
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/config-syntax-crash/testrunner
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/console/client-bareos-fd.conf
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/console/limited-operator.conf
  systemtests/tests/python-bareos/etc/bareos/bconsole-limited-operator.conf.in
  systemtests/tests/python-bareos/list_unittests.py
  systemtests/tests/python-bareos/test_acl.py
  systemtests/tests/python-bareos/test_json_config.py
  systemtests/tests/python-bareos/test_list_jobs.py
Labels: bugfix, is a backport to 21

#1890 Fix multiple ACL handling bugs
  .gitignore
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/dird/ua_acl.cc
  core/src/dird/ua_cmds.cc
  core/src/dird/ua_run.cc
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  docs/manuals/source/manually_added_config_directive_descriptions/dir-console-WhereAcl.rst.inc
  python-bareos/.gitignore
  systemtests/python-modules/bareos_unittest/json.py
  systemtests/tests/CMakeLists.txt
  systemtests/tests/config-syntax-crash/CMakeLists.txt
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/config-syntax-crash/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/config-syntax-crash/testrunner
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/console/client-bareos-fd.conf
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/console/limited-operator.conf
  systemtests/tests/python-bareos/etc/bareos/bconsole-limited-operator.conf.in
  systemtests/tests/python-bareos/list_unittests.py
  systemtests/tests/python-bareos/test_acl.py
  systemtests/tests/python-bareos/test_json_config.py
Labels: bugfix, is a backport to 23

#1894 Update ReaR documentation
  CHANGELOG.md
  contrib/misc/rear/update-rear-rescue.sh
  docs/manuals/source/Appendix/DisasterRecoveryUsingBareos.rst
  docs/manuals/source/Configuration/Console.rst
  docs/manuals/source/DocumentationStyleGuide/CommonNames.rst
  docs/manuals/source/TasksAndConcepts/DataEncryption.rst
  docs/manuals/source/TasksAndConcepts/TransportEncryption.rst
  python-bareos/bin/bareos-fd-connect.py
Labels: documentation, is a backport to 23

#1895 Update ReaR documentation
  CHANGELOG.md
  contrib/misc/rear/update-rear-rescue.sh
  docs/manuals/source/Appendix/DisasterRecoveryUsingBareos.rst
  docs/manuals/source/Configuration/Console.rst
  docs/manuals/source/DocumentationStyleGuide/CommonNames.rst
  docs/manuals/source/TasksAndConcepts/DataEncryption.rst
  python-bareos/bin/bareos-fd-connect.py
Labels: documentation, is a backport to 22

#1824 ULC: build the universal linux client also for rpm based OS.
  .matrix.yml
  CHANGELOG.md
  CMakeLists.txt
  core/manpages/CMakeLists.txt
  core/platforms/CMakeLists.txt
  core/platforms/packaging/bareos-universal-client.spec
  core/platforms/systemd/CMakeLists.txt
  core/scripts/CMakeLists.txt
  core/src/plugins/dird/CMakeLists.txt
  core/src/plugins/filed/CMakeLists.txt
  core/src/plugins/stored/CMakeLists.txt
  devtools/build-rpm.sh
  devtools/dist-tarball.sh
  docs/pkglists/ULC_rpm_OpenSSL_1.1.aarch64
  docs/pkglists/ULC_rpm_OpenSSL_1.1.x86_64
  docs/pkglists/ULC_rpm_OpenSSL_3.0.aarch64
  docs/pkglists/ULC_rpm_OpenSSL_3.0.x86_64
Labels: enhancement

#1738 dird: disallow running always incremental virtual full jobs with empty jobid list
  CHANGELOG.md
  core/src/dird/ua_output.cc
  core/src/dird/ua_run.cc
  core/src/dird/vbackup.cc
  systemtests/tests/always-incremental-consolidate/testrunner-06-rerun-ai-vf
Labels: requires backport to 23

#1876 VMware Plugin: Add option restore_allow_disks_mismatch
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/bareos-fd-vmware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: enhancement, requires backport to 23
