Repository bareos/bareos, pull requests merged in 2024-09, with the labels that each got.

#1948 systemtests: fix plugin postgresql testrunner-*, old postgres `bc` call
  CHANGELOG.md
  systemtests/tests/py3plug-fd-postgres/testrunner-default
  systemtests/tests/py3plug-fd-postgresql/database/setup_local_db.sh
  systemtests/tests/py3plug-fd-postgresql/testrunner-debian
  systemtests/tests/py3plug-fd-postgresql/testrunner-default
  systemtests/tests/py3plug-fd-postgresql/testrunner-roles
  systemtests/tests/py3plug-fd-postgresql/testrunner-tablespace
  systemtests/tests/py3plug-fd-postgresql/testrunner-tasks-pgsql
  systemtests/tests/py3plug-fd-postgresql/testrunner-walsymlink
Labels: is a backport to 23

#1933 webui: fix handling deleted clients in restore browser
  CHANGELOG.md
  core/src/dird/ua_cmds.cc
  core/src/dird/ua_output.cc
  core/src/dird/ua_run.cc
  core/src/dird/ua_select.cc
  core/src/dird/ua_select.h
  core/src/include/job_level.h
  systemtests/python-modules/bareos_unittest/base.py
  systemtests/python-modules/bareos_unittest/json.py
  systemtests/tests/heartbeat-interval/test-setup
  systemtests/tests/py3plug-fd-basic/test-setup
  systemtests/tests/python-bareos/test_acl.py
  systemtests/tests/python-bareos/test_bvfs.py
  systemtests/tests/python-bareos/test_delete.py
  systemtests/tests/python-bareos/test_list_command.py
  systemtests/tests/python-bareos/test_python_fd_plugins.py
  systemtests/tests/restore/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/restore/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/restore/functions
  webui/module/Client/src/Client/Model/ClientModel.php
  webui/module/Restore/src/Restore/Controller/RestoreController.php
  webui/module/Restore/src/Restore/Form/RestoreForm.php
  webui/module/Restore/src/Restore/Model/RestoreModel.php
  webui/module/Restore/view/restore/restore/index.phtml
  webui/module/Restore/view/restore/restore/versions.phtml
  webui/tests/selenium/README.md
  webui/vendor/Bareos/library/Bareos/BSock/BareosBSock.php
Labels: enhancement, requires no backport

#1956 deb control files: depend on python3-bareos
  CHANGELOG.md
  debian/control
  debian/control.bareos-contrib-tools
Labels: bugfix, requires backport to 22, requires backport to 23, bug
