Repository bareos/bareos, pull requests merged in 2024-08, with the labels that each got.

#1888 matrix remove obsolete SUSE
  .matrix.yml
  CHANGELOG.md
  core/CMakeLists.txt
  core/cmake/BareosFindPrograms.cmake
  core/platforms/packaging/bareos.spec
  core/scripts/mtx-changer.in
  core/src/lib/tls_openssl_private.cc
  core/src/lib/tls_openssl_private.h
  core/src/tests/bareos_test_sockets.cc
  core/src/tests/bareos_test_sockets.h
  core/src/tests/create_resource.cc
  core/src/tests/sd_reservation.cc
  core/src/tests/test_bsock.cc
  systemtests/scripts/functions
  systemtests/scripts/mysql.sh
  systemtests/tests/bscan-bextract-bls-bcopy/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/mtx-changer/test-cleanup
  systemtests/tests/mtx-changer/test-setup
  systemtests/tests/py3plug-fd-mariabackup/testrunner-default
  systemtests/tests/py3plug-fd-postgresql/database/setup_local_db.sh.in
Labels: requires backport to 22, requires backport to 23

#1889 filed: fix python plugin crash on python <3.10
  CHANGELOG.md
  core/src/plugins/filed/python/python-fd.cc
Labels: requires backport to 22, requires backport to 23, bug

#1906 matrix remove obsolete SUSE
  .matrix.yml
  CHANGELOG.md
  core/CMakeLists.txt
  core/platforms/packaging/bareos.spec
  core/scripts/mtx-changer.in
  core/src/lib/tls_openssl_private.cc
  core/src/lib/tls_openssl_private.h
  core/src/tests/bareos_test_sockets.cc
  core/src/tests/bareos_test_sockets.h
  core/src/tests/create_resource.cc
  core/src/tests/sd_reservation.cc
  core/src/tests/test_bsock.cc
  systemtests/scripts/functions
  systemtests/scripts/mysql.sh
  systemtests/tests/bscan-bextract-bls-bcopy/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/mtx-changer/test-cleanup
  systemtests/tests/mtx-changer/test-setup
  systemtests/tests/py3plug-fd-mariabackup/CMakeLists.txt
  systemtests/tests/py3plug-fd-mariabackup/testrunner
  systemtests/tests/py3plug-fd-postgresql/database/setup_local_db.sh.in
Labels: is a backport to 23

#1905 VMware Plugin: Add option restore_allow_disks_mismatch
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/bareos-fd-vmware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: enhancement, is a backport to 23

#1908 vadp-dumper: fix out of bounds read
  CHANGELOG.md
  core/src/vmware/vadp_dumper/bareos_vadp_dumper.cc
  core/src/vmware/vadp_dumper/copy_thread.cc
  systemtests/scripts/cleanup
Labels: requires backport to 23

#1896 Use only MinGW VSS
  CHANGELOG.md
  core/LICENSE
  core/src/filed/filed.h
  core/src/plugins/filed/CMakeLists.txt
  core/src/win32/filed/vss_generic.cc
  core/src/win32/include/vss_client.h
  core/src/win32/vdi/include/LICENSE.txt
  core/src/win32/vdi/include/vdi.h
  core/src/win32/vdi/include/vdierror.h
  core/src/win32/vdi/include/vdiguid.h
  debian/copyright
  debian/copyright.core_exceptions
  third-party/README.md
Labels: enhancement, is a backport to 23

#1913 filed: fix python plugin crash on python <3.10
  CHANGELOG.md
  core/src/plugins/filed/python/python-fd.cc
Labels: is a backport to 23, bug

#1918 vadp-dumper: fix out of bounds read
  CHANGELOG.md
  core/src/vmware/vadp_dumper/bareos_vadp_dumper.cc
  core/src/vmware/vadp_dumper/copy_thread.cc
Labels: is a backport to 23

#1907 matrix remove obsolete SUSE
  .matrix.yml
  CHANGELOG.md
  core/CMakeLists.txt
  core/cmake/BareosFindPrograms.cmake
  core/platforms/packaging/bareos.spec
  core/src/cats/create_bareos_database.in
  core/src/lib/tls_openssl_private.cc
  core/src/lib/tls_openssl_private.h
  core/src/tests/bareos_test_sockets.cc
  core/src/tests/bareos_test_sockets.h
  core/src/tests/create_resource.cc
  core/src/tests/sd_reservation.cc
  core/src/tests/test_bsock.cc
  systemtests/scripts/functions
  systemtests/scripts/mysql.sh
  systemtests/tests/bscan-bextract-bls-bcopy/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/py2plug-fd-mariabackup/CMakeLists.txt
  systemtests/tests/py2plug-fd-mariabackup/testrunner
  systemtests/tests/py3plug-fd-postgres/CMakeLists.txt
  systemtests/tests/py3plug-fd-postgres/database/setup_local_db.sh.in
Labels: is a backport to 22

#1901 dird: disallow running always incremental virtual full jobs with empty jobid list
  CHANGELOG.md
  core/src/dird/vbackup.cc
  systemtests/tests/always-incremental-consolidate/testrunner-06-rerun-ai-vf
Labels: is a backport to 23

#1916 filed: fix python plugin crash on python <3.10
  CHANGELOG.md
  core/src/plugins/filed/python/python-fd.cc
Labels: is a backport to 22, bug

#1897 Use only MinGW VSS
  CHANGELOG.md
  core/LICENSE
  core/src/filed/filed.h
  core/src/plugins/filed/CMakeLists.txt
  core/src/win32/filed/vss_generic.cc
  core/src/win32/include/vss_client.h
  core/src/win32/vdi/include/LICENSE.txt
  core/src/win32/vdi/include/vdi.h
  core/src/win32/vdi/include/vdierror.h
  core/src/win32/vdi/include/vdiguid.h
  debian/copyright
  debian/copyright.footer
  third-party/README.md
Labels: enhancement, is a backport to 22

#1926 cats: scripts add option --no-psqlrc to psql
  CHANGELOG.md
  core/src/cats/create_bareos_database.in
  core/src/cats/drop_bareos_database.in
  core/src/cats/drop_bareos_tables.in
  core/src/cats/grant_bareos_privileges.in
  core/src/cats/update_bareos_tables.in
Labels: is a backport to 23

#1917 python-bareos: fix backslash usage in regex
  CHANGELOG.md
  python-bareos/bareos/bsock/lowlevel.py
Labels: requires backport to 21, requires backport to 22, requires backport to 23

#1931 python-bareos: fix backslash usage in regex
  CHANGELOG.md
  python-bareos/bareos/bsock/lowlevel.py
Labels: is a backport to 22

#1930 python-bareos: fix backslash usage in regex
  CHANGELOG.md
  python-bareos/bareos/bsock/lowlevel.py
Labels: is a backport to 23

#1932 python-bareos: fix backslash usage in regex
  CHANGELOG.md
  python-bareos/bareos/bsock/lowlevel.py
  systemtests/tests/py2plug-fd-mariabackup/CMakeLists.txt
Labels: is a backport to 21

#1927 cats: scripts add option --no-psqlrc to psql
  CHANGELOG.md
  core/src/cats/create_bareos_database.in
  core/src/cats/drop_bareos_database.in
  core/src/cats/drop_bareos_tables.in
  core/src/cats/grant_bareos_privileges.in
  core/src/cats/update_bareos_tables.in
Labels: is a backport to 22

#1904 msgchan: fix deadlock
  CHANGELOG.md
  core/src/dird/job.cc
  core/src/dird/job.h
  core/src/dird/msgchan.cc
Labels: is a backport to 23, bug

#1936 webui: properly set focus to input box after each command
  CHANGELOG.md
  webui/module/Console/view/console/console/index.phtml
Labels: requires backport to 23

#1940 webui: properly set focus to input box after each command
  CHANGELOG.md
  webui/module/Console/view/console/console/index.phtml
Labels: is a backport to 23
