Repository bareos/bareos, pull requests merged in 2024-02, with the labels that each got.

#1696 webui: Backup Unit Report fixes
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/BareosConsole.rst
  webui/module/Director/src/Director/Controller/DirectorController.php
  webui/module/Director/view/director/director/subscription.phtml
Labels: requires backport to 22, requires backport to 23

#1698 webui: Backup Unit Report fixes
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/BareosConsole.rst
  webui/module/Director/src/Director/Controller/DirectorController.php
  webui/module/Director/view/director/director/subscription.phtml
Labels: is a backport to 23

#1699 webui: Backup Unit Report fixes
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/BareosConsole.rst
  webui/module/Director/src/Director/Controller/DirectorController.php
  webui/module/Director/view/director/director/subscription.phtml
Labels: is a backport to 22

#1704 windows: fix calculation of "job_metadata.xml" object size
  CHANGELOG.md
  core/src/filed/backup.cc
  core/src/win32/compat/glob.cc
Labels: is a backport to 22

#1703 windows: fix calculation of "job_metadata.xml" object size
  CHANGELOG.md
  core/src/filed/backup.cc
  core/src/win32/compat/glob.cc
Labels: is a backport to 23

#1695 windows: fix calculation of "job_metadata.xml" object size
  CHANGELOG.md
  core/src/filed/backup.cc
  core/src/win32/compat/glob.cc
Labels: requires backport to 21, requires backport to 22, requires backport to 23

#1701 stored: fix storage daemon crash if passive client is unreachable, create better session keys
  CHANGELOG.md
  core/src/lib/util.cc
  core/src/lib/util.h
  core/src/stored/dir_cmd.cc
  core/src/stored/job.cc
  systemtests/tests/passive/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/passive/testrunner
Labels: is a backport to 22

#1688 stored: fix storage daemon crash if passive client is unreachable, create better session keys
  CHANGELOG.md
  core/src/lib/util.cc
  core/src/lib/util.h
  core/src/stored/dir_cmd.cc
  core/src/stored/job.cc
  systemtests/tests/passive/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/passive/testrunner
Labels: requires backport to 21, requires backport to 22, requires backport to 23

#1702 stored: fix storage daemon crash if passive client is unreachable, create better session keys
  CHANGELOG.md
  core/src/lib/util.cc
  core/src/lib/util.h
  core/src/stored/dir_cmd.cc
  core/src/stored/job.cc
  systemtests/tests/passive/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/passive/testrunner
Labels: is a backport to 21

#1708 bareos-triggerjob: fix parameter handling
  CHANGELOG.md
  contrib/misc/triggerjob/bareos-triggerjob.py
  python-bareos/bareos/bsock/directorconsole.py
Labels: requires backport to 23

#1705 windows: fix calculation of "job_metadata.xml" object size
  CHANGELOG.md
  core/src/filed/backup.cc
  core/src/win32/compat/glob.cc
Labels: is a backport to 21

#1662 fvec: add mmap based vector
  CHANGELOG.md
  core/src/lib/channel.h
  core/src/lib/edit.h
  core/src/stored/append.cc
  core/src/stored/backends/dedup/fvec.h
  core/src/tests/CMakeLists.txt
  core/src/tests/fvec.cc
  systemtests/tests/restore/testrunner-full-restore
Labels: requires backport to 23

#1700 stored: fix storage daemon crash if passive client is unreachable, create better session keys
  CHANGELOG.md
  core/src/lib/util.cc
  core/src/lib/util.h
  core/src/stored/dir_cmd.cc
  core/src/stored/job.cc
  systemtests/tests/passive/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/passive/testrunner
Labels: is a backport to 23

#1685 core: fix various data races (connection_pool/heartbeat_thread)
  CHANGELOG.md
  core/src/dird/fd_cmds.cc
  core/src/dird/fd_cmds.h
  core/src/dird/job.cc
  core/src/dird/socket_server.cc
  core/src/dird/ua_status.cc
  core/src/filed/heartbeat.cc
  core/src/lib/connection_pool.cc
  core/src/lib/connection_pool.h
  core/src/lib/thread_util.h
  core/src/plugins/filed/CMakeLists.txt
  core/src/plugins/filed/spam/spam.cc
  systemtests/tests/CMakeLists.txt
  systemtests/tests/heartbeat-interval/CMakeLists.txt
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-dir.d/fileset/PluginTest.conf.in
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/heartbeat-interval/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/heartbeat-interval/etc/bareos/bconsole.conf.in
  systemtests/tests/heartbeat-interval/functions
  systemtests/tests/heartbeat-interval/test-setup
  systemtests/tests/heartbeat-interval/testrunner-check
Labels: requires backport to 22, requires backport to 23

#1709 bareos-triggerjob: fix parameter handling
  CHANGELOG.md
  contrib/misc/triggerjob/bareos-triggerjob.py
  python-bareos/bareos/bsock/directorconsole.py
Labels: is a backport to 23

#1687 core: Fix compile errors on GCC 14
  CHANGELOG.md
  core/src/cats/sql_get.cc
  core/src/dird/ua_prune.cc
  core/src/stored/append.cc
  core/src/tests/addresses_and_ports_config.cc
Labels: bugfix, requires backport to 22, requires backport to 23

#1693 core: Fix compile errors on GCC 14
  CHANGELOG.md
  core/src/cats/sql_get.cc
  core/src/dird/ua_prune.cc
  core/src/stored/append.cc
  core/src/tests/addresses_and_ports_config.cc
Labels: bugfix, is a backport to 23

#1706 fvec: add mmap based vector
  CHANGELOG.md
  core/src/lib/channel.h
  core/src/lib/edit.h
  core/src/stored/append.cc
  core/src/stored/backends/dedup/fvec.h
  core/src/tests/CMakeLists.txt
  core/src/tests/fvec.cc
  systemtests/tests/restore/testrunner-full-restore
Labels: is a backport to 23

#1711 core: fix various data races (connection_pool/heartbeat_thread)
  CHANGELOG.md
  core/src/dird/fd_cmds.cc
  core/src/dird/fd_cmds.h
  core/src/dird/job.cc
  core/src/dird/socket_server.cc
  core/src/dird/ua_status.cc
  core/src/filed/heartbeat.cc
  core/src/lib/connection_pool.cc
  core/src/lib/connection_pool.h
  core/src/lib/thread_util.h
Labels: is a backport to 23

#1712 core: fix various data races (connection_pool/heartbeat_thread)
  CHANGELOG.md
  core/scripts/btraceback.in
  core/src/dird/fd_cmds.cc
  core/src/dird/fd_cmds.h
  core/src/dird/job.cc
  core/src/dird/socket_server.cc
  core/src/dird/ua_status.cc
  core/src/filed/heartbeat.cc
  core/src/lib/connection_pool.cc
  core/src/lib/connection_pool.h
  core/src/lib/thread_util.h
Labels: is a backport to 22
