Repository bareos/bareos, pull requests merged in 2024-10, with the labels that each got.

#1972 fix include-ordering on FreeBSD that could cause build issues
  CHANGELOG.md
  core/CMakeLists.txt
  core/src/stored/CMakeLists.txt
Labels: bugfix, requires backport to 22, requires backport to 23, bug

#1966 github actions python-bareos: add workflow_dispatch
  .github/workflows/publish-python-packages-to-pypi.yml
  CHANGELOG.md
Labels: enhancement

#1973 fix include-ordering on FreeBSD that could cause build issues
  CHANGELOG.md
  core/CMakeLists.txt
  core/src/stored/CMakeLists.txt
  core/src/tests/test_bsock.cc
Labels: bugfix, is a backport to 23, bug

#1961 FreeBSD: fix sed inplace usage, use bin/sh as shebang for script, pkg make director dependent of database-postgresql
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-director/Makefile
  core/scripts/bareos-config-lib.sh.in
  core/src/cats/grant_bareos_privileges.in
  core/src/cats/make_bareos_tables.in
  core/src/cats/update_bareos_tables.in
  core/src/tests/cram_md5.cc
Labels: requires backport to 23, bug

#1964 FreeBSD: fix sed inplace usage, pkg make director dependent of database-postgresql
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-director/Makefile
  core/scripts/bareos-config-lib.sh.in
  core/src/tests/cram_md5.cc
  systemtests/tests/py3plug-fd-postgres/database/setup_local_db.sh.in
  systemtests/tests/py3plug-fd-postgres/testrunner-default
  systemtests/tests/py3plug-fd-postgres/testrunner-roles
Labels: is a backport to 23, bug

#1953 dir: fix DbLocker usage
  CHANGELOG.md
  core/src/dird/ua_label.cc
  core/src/dird/ua_select.cc
Labels: requires no backport

#1967 deb control files: depend on python3-bareos
  CHANGELOG.md
  debian/control
  debian/control.bareos-contrib-tools
Labels: bugfix, is a backport to 23, bug

#1958 Disable writing PRE_LABEL label-type to support WORM media
  CHANGELOG.md
  core/src/cats/sql_create.cc
  core/src/dird/ua_label.cc
  core/src/stored/dir_cmd.cc
  core/src/stored/label.cc
  core/src/stored/mount.cc
  core/src/stored/record.h
  systemtests/tests/multiplied-device/testrunner
  systemtests/tests/py3plug-sd/testrunner
Labels: enhancement, requires backport to 23

#1979 Disable writing PRE_LABEL label-type to support WORM media
  CHANGELOG.md
  core/src/cats/sql_create.cc
  core/src/dird/ua_label.cc
  core/src/stored/dir_cmd.cc
  core/src/stored/label.cc
  core/src/stored/mount.cc
  core/src/stored/record.h
  systemtests/tests/multiplied-device/testrunner
  systemtests/tests/py3plug-sd/testrunner
Labels: enhancement, is a backport to 23

#1974 fix include-ordering on FreeBSD that could cause build issues
  CHANGELOG.md
  core/CMakeLists.txt
  core/src/stored/CMakeLists.txt
Labels: bugfix, is a backport to 22, bug

#1968 deb control files: depend on python3-bareos
  CHANGELOG.md
  debian/control
  debian/control.bareos-contrib-tools
Labels: bugfix, is a backport to 22, bug

#1980 docs: improve debuginfo install description (fix issue #1943)
  CHANGELOG.md
  docs/manuals/source/Appendix/Debugging.rst
Labels: documentation, requires backport to 22, requires backport to 23

#1985 docs: improve debuginfo install description (fix issue #1943)
  CHANGELOG.md
  docs/manuals/source/Appendix/Debugging.rst
Labels: documentation, is a backport to 23

#1986 docs: improve debuginfo install description (fix issue #1943)
  CHANGELOG.md
  docs/manuals/source/Appendix/Debugging.rst
Labels: documentation, is a backport to 22

#1978 debian: fix dedupable backend names
  CHANGELOG.md
  core/src/stored/backends/dedupable/fvec.h
  core/src/stored/backends/dedupable/volume.h
  core/src/stored/backends/dedupable_device.d/bareos-sd.d/device/dedup.conf.example
  core/src/stored/reserve.cc
  core/src/tests/configs/sd_reservation/bareos-sd.d/storage/myself.conf.in
  core/src/tools/CMakeLists.txt
  core/src/tools/dedup_conf.cc
  debian/control.bareos-storage
  docs/manuals/source/DeveloperGuide.rst
  docs/manuals/source/DeveloperGuide/dedupable.rst
  docs/manuals/source/DeveloperGuide/dedupable/parsing.puml
  docs/manuals/source/DeveloperGuide/mediaformat.rst
  docs/manuals/source/DeveloperGuide/reservation.rst
  docs/manuals/source/TasksAndConcepts/StorageBackends.rst
  docs/manuals/source/include/config/SdDeviceDeviceOptionsDedupable.conf
  docs/manuals/source/manually_added_config_directive_descriptions/sd-storage-JustInTimeReservation.rst.inc
  systemtests/tests/bareos-basic/testrunner-test-make-catalog-backup
  systemtests/tests/parallel-jobs/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
Labels: is a backport to 23

#1990 scripts: remove unmaintained bareos-explorer
  CHANGELOG.md
  LICENSE.txt
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.common
  core/platforms/packaging/bareos.spec
  core/scripts/CMakeLists.txt
  core/scripts/bareos-explorer.in
  debian/bareos-common.install.in
Labels: enhancement, requires no backport
