Repository bareos/bareos, pull requests merged in 2024-06, with the labels that each got.

#1840 python-bareos: fix description
  CHANGELOG.md
  python-bareos/setup.py
Labels: requires backport to 23

#1725 fix sql error on bad virtualfull; detect parsing errors with strtod
  CHANGELOG.md
  core/src/dird/bsr.cc
  core/src/dird/consolidate.cc
  core/src/dird/dird_conf.cc
  core/src/dird/director_jcr_impl.h
  core/src/dird/fd_cmds.cc
  core/src/dird/fd_cmds.h
  core/src/dird/job.cc
  core/src/dird/job.h
  core/src/dird/migrate.cc
  core/src/dird/vbackup.cc
  core/src/dird/verify.cc
  core/src/include/baconfig.h
  core/src/lib/edit.cc
  core/src/lib/edit.h
  core/src/lib/scan.cc
  core/src/tests/test_edit.cc
Labels: bugfix, requires backport to 23

#1834 Fix mistake in VolumeManagement.rst
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/VolumeManagement.rst
Labels: documentation, is a backport to 23

#1828 fix various memory leaks
  CHANGELOG.md
  core/src/cats/postgresql.cc
  core/src/console/console.cc
  core/src/dird/admin.cc
  core/src/dird/archive.cc
  core/src/dird/consolidate.cc
  core/src/dird/dbcheck.cc
  core/src/dird/dbcheck_utils.cc
  core/src/dird/dbcheck_utils.h
  core/src/dird/director_jcr_impl.h
  core/src/dird/fd_cmds.cc
  core/src/dird/job.cc
  core/src/dird/ua_restore.cc
  core/src/dird/verify.cc
  core/src/filed/backup.cc
  core/src/lib/parse_conf_state_machine.cc
  core/src/lib/runscript.cc
  core/src/plugins/dird/python/python-dir.cc
  core/src/plugins/stored/python/python-sd.cc
  core/src/stored/acquire.cc
  core/src/tests/CMakeLists.txt
  core/src/tests/test_config_parser_dir.cc
  systemtests/scripts/functions
  systemtests/tests/CMakeLists.txt
  systemtests/tests/dbcheck/CMakeLists.txt
  systemtests/tests/dbcheck/test-setup
  systemtests/tests/dbcheck/testrunner-duplicate-paths
Labels: bugfix, is a backport to 23

#1841 python-bareos: fix description
  CHANGELOG.md
  python-bareos/setup.py
Labels: is a backport to 23

#1849 python-bareos: add missing `dirname` variable
  CHANGELOG.md
  python-bareos/bareos/bsock/filedaemon.py
Labels: is a backport to 21

#1848 python-bareos: add missing `dirname` variable
  CHANGELOG.md
  python-bareos/bareos/bsock/filedaemon.py
Labels: is a backport to 22

#1842 fix sql error on bad virtualfull; detect parsing errors with strtod
  CHANGELOG.md
  core/src/dird/bsr.cc
  core/src/dird/consolidate.cc
  core/src/dird/dird_conf.cc
  core/src/dird/director_jcr_impl.h
  core/src/dird/fd_cmds.cc
  core/src/dird/fd_cmds.h
  core/src/dird/job.cc
  core/src/dird/job.h
  core/src/dird/migrate.cc
  core/src/dird/vbackup.cc
  core/src/dird/verify.cc
Labels: bugfix, is a backport to 23

#1865 create_bareos_database: fix `db_name` not being double quoted
  CHANGELOG.md
  core/src/cats/create_bareos_database.in
Labels: bugfix, requires backport to 22, requires backport to 23
