Repository bareos/bareos, pull requests merged in 2024-03, with the labels that each got.

#1639 Add backport tool
  CHANGELOG.md
  devtools/pip-tools/.gitignore
  devtools/pip-tools/Pipfile
  devtools/pip-tools/Pipfile.lock
  devtools/pip-tools/check_sources.egg-info/PKG-INFO
  devtools/pip-tools/check_sources.egg-info/SOURCES.txt
  devtools/pip-tools/check_sources.egg-info/dependency_links.txt
  devtools/pip-tools/check_sources.egg-info/entry_points.txt
  devtools/pip-tools/check_sources.egg-info/top_level.txt
  devtools/pip-tools/pr_tool/backport.py
  devtools/pip-tools/pr_tool/backport_pr_template.md
  devtools/pip-tools/pr_tool/github.py
  devtools/pip-tools/pr_tool/main.py
Labels: enhancement

#1718 crypto_wrap: replace aes wrap with openssl aes wrap algorithm
  CHANGELOG.md
  core/src/dird/ua_label.cc
  core/src/lib/crypto_wrap.cc
  core/src/lib/crypto_wrap.h
  core/src/plugins/stored/scsicrypto/scsicrypto-sd.cc
  core/src/stored/askdir.cc
  core/src/tests/CMakeLists.txt
  core/src/tests/wrap.cc
  core/src/tools/bscrypto.cc
Labels: requires backport to 23

#1710 dbcheck: fix dbcheck crash if password is not set in catalog resource
  CHANGELOG.md
  core/src/dird/dbcheck.cc
  core/src/lib/bnet_server_tcp.cc
  core/src/lib/bsock_tcp.cc
  core/src/lib/thread_pool.h
  systemtests/data/weird-files.tar.gz
  systemtests/tests/py3plug-fd-libcloud/test-setup
  systemtests/tests/testfind/testrunner
  systemtests/tests/virtualfull-basic/testrunner
Labels: requires backport to 22, requires backport to 23

#1719 Require python3 explicit
  CHANGELOG.md
  contrib/misc/bsmc/bin/bsmc
  contrib/misc/triggerjob/bareos-triggerjob.py
Labels: requires backport to 23

#1726 filed: skip stripped top level directories
  CHANGELOG.md
  core/src/dird/ndmp_dma_backup_NDMP_BAREOS.cc
  core/src/dird/vbackup.cc
  core/src/dird/verify.cc
  core/src/filed/backup.cc
  core/src/filed/verify.cc
  systemtests/tests/CMakeLists.txt
  systemtests/tests/strippath/CMakeLists.txt
  systemtests/tests/strippath/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/strippath/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/strippath/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/strippath/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/strippath/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/strippath/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf.in
  systemtests/tests/strippath/etc/bareos/bareos-dir.d/job/verify-catalog-bareos-fd.conf.in
  systemtests/tests/strippath/etc/bareos/bareos-dir.d/job/verify-disktocatalog-bareos-fd.conf.in
  systemtests/tests/strippath/etc/bareos/bareos-dir.d/job/verify-initcatalog-bareos-fd.conf.in
  systemtests/tests/strippath/etc/bareos/bareos-dir.d/job/verify-volumetocatalog-bareos-fd.conf.in
  systemtests/tests/strippath/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/strippath/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/strippath/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/strippath/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/strippath/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/strippath/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/strippath/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/strippath/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/strippath/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/strippath/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/strippath/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/strippath/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/strippath/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/strippath/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/strippath/etc/bareos/bconsole.conf.in
  systemtests/tests/strippath/test-setup
  systemtests/tests/strippath/testrunner-01-backup
  systemtests/tests/strippath/testrunner-02-restore
  systemtests/tests/strippath/testrunner-03-verify
Labels: is a backport to 23

#1729 Require python3 explicit
  CHANGELOG.md
  contrib/misc/bsmc/bin/bsmc
  contrib/misc/triggerjob/bareos-triggerjob.py
Labels: is a backport to 23

#1731 dbcheck: fix dbcheck crash if password is not set in catalog resource
  CHANGELOG.md
  core/src/dird/dbcheck.cc
Labels: is a backport to 22

#1730 dbcheck: fix dbcheck crash if password is not set in catalog resource
  CHANGELOG.md
  core/src/dird/dbcheck.cc
  core/src/lib/bnet_server_tcp.cc
  core/src/lib/bsock_tcp.cc
  core/src/lib/thread_pool.h
  systemtests/data/weird-files.tar.gz
  systemtests/tests/py3plug-fd-libcloud/testrunner
  systemtests/tests/testfind/testrunner
  systemtests/tests/virtualfull-basic/testrunner
Labels: is a backport to 23

#1720 Bugfix: Clean up error handling in LDAP plugin, fix dependencies
  CHANGELOG.md
  core/src/plugins/filed/python/ldap/bareos-fd-ldap.py
  debian/control
  debian/control.bareos-filedaemon-python-plugins-common
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/LDAPPlugin.rst.inc
  systemtests/tests/py3plug-fd-ldap/CMakeLists.txt
  systemtests/tests/py3plug-fd-ldap/etc/bareos/bareos-dir.d/fileset/PluginFailingTest.conf.in
  systemtests/tests/py3plug-fd-ldap/etc/bareos/bareos-dir.d/fileset/PluginTest.conf.in
  systemtests/tests/py3plug-fd-ldap/testrunner-backup
  systemtests/tests/py3plug-fd-ldap/testrunner-wrong_credentials
Labels: is a backport to 23

#1735 docs: fix Pool explanation for migration jobs
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/MigrationAndCopy.rst
  docs/manuals/source/include/config/DirSelectionPatterns-sql1.conf
  docs/manuals/source/manually_added_config_directive_descriptions/dir-job-Pool.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/dir-job-SelectionPattern.rst.inc
Labels: documentation, is a backport to 23

#1732 stored: fix authentication race condition / deadlock
  CHANGELOG.md
  core/scripts/bareos-ctl-dir.in
  core/scripts/bareos-ctl-fd.in
  core/scripts/bareos-ctl-sd.in
  core/src/dird/director_jcr_impl.h
  core/src/dird/job.cc
  core/src/dird/jobq.cc
  core/src/dird/msgchan.cc
  core/src/dird/ndmp_fhdb_common.cc
  core/src/dird/ndmp_fhdb_lmdb.cc
  core/src/dird/ndmp_fhdb_mem.cc
  core/src/dird/next_vol.cc
  core/src/filed/backup.cc
  core/src/filed/dir_cmd.cc
  core/src/filed/restore.cc
  core/src/filed/status.cc
  core/src/filed/verify.cc
  core/src/filed/verify_vol.cc
  core/src/include/jcr.h
  core/src/lib/jcr.cc
  core/src/lib/thread_util.h
  core/src/stored/dir_cmd.cc
  core/src/stored/fd_cmds.cc
  core/src/stored/job.cc
  core/src/stored/ndmp_tape.cc
  core/src/stored/reserve.cc
  core/src/stored/sd_cmds.cc
  core/src/stored/status.cc
  core/src/stored/stored.cc
  core/src/stored/stored_jcr_impl.h
  systemtests/scripts/cleanup
  systemtests/scripts/functions
  systemtests/tests/parallel-jobs/CMakeLists.txt
Labels: bugfix, requires backport to 21, requires backport to 22, requires backport to 23

#1737 stored: fix authentication race condition / deadlock
  CHANGELOG.md
  core/scripts/bareos-ctl-dir.in
  core/scripts/bareos-ctl-fd.in
  core/scripts/bareos-ctl-sd.in
  core/src/dird/director_jcr_impl.h
  core/src/dird/job.cc
  core/src/dird/jobq.cc
  core/src/dird/msgchan.cc
  core/src/dird/ndmp_fhdb_common.cc
  core/src/dird/ndmp_fhdb_lmdb.cc
  core/src/dird/ndmp_fhdb_mem.cc
  core/src/dird/next_vol.cc
  core/src/filed/backup.cc
  core/src/filed/dir_cmd.cc
  core/src/filed/restore.cc
  core/src/filed/status.cc
  core/src/filed/verify.cc
  core/src/filed/verify_vol.cc
  core/src/include/jcr.h
  core/src/lib/jcr.cc
  core/src/lib/thread_util.h
  core/src/stored/dir_cmd.cc
  core/src/stored/fd_cmds.cc
  core/src/stored/job.cc
  core/src/stored/ndmp_tape.cc
  core/src/stored/reserve.cc
  core/src/stored/sd_cmds.cc
  core/src/stored/status.cc
  core/src/stored/stored.cc
  core/src/stored/stored_jcr_impl.h
  systemtests/scripts/cleanup
  systemtests/scripts/functions
  systemtests/tests/parallel-jobs/CMakeLists.txt
Labels: bugfix, is a backport to 23

#1742 stored: fix authentication race condition / deadlock
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/BareosCommonMakefile
  core/src/include/jcr.h
  core/src/stored/fd_cmds.cc
  core/src/stored/jcr_private.h
  core/src/stored/ndmp_tape.cc
  core/src/stored/sd_cmds.cc
Labels: bugfix, is a backport to 21

#1721 Fix warning about missing delcandidates table in director
  AUTHORS
  CHANGELOG.md
  core/src/cats/cats.h
  core/src/cats/postgresql.cc
  core/src/cats/postgresql.h
  core/src/tests/run_on_incoming_connect_interval.cc
Labels: bugfix, requires backport to 23

#1716 github: introduce template for issues
  .github/ISSUE_TEMPLATE/10-issue_report.yaml
  .github/ISSUE_TEMPLATE/20-feature_request.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/no-response.yaml
  CHANGELOG.md
  docs/manuals/source/DeveloperGuide/developerFAQ.rst
  docs/manuals/source/DeveloperGuide/generaldevel.rst
  docs/manuals/source/DeveloperGuide/gitworkflow.rst
  docs/manuals/source/TasksAndConcepts/NdmpBackupsWithBareos.rst
Labels: documentation

#1727 VMware Plugin: Backup and Restore NVRAM
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/bareos-fd-vmware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: requires backport to 23

#1745 stored: fix not counting files correctly in mac jobs when autoxflate is enabled
  CHANGELOG.md
  core/src/dird/msgchan.cc
  core/src/lib/jcr.cc
  core/src/stored/block.cc
  core/src/stored/mac.cc
  core/src/stored/ndmp_tape.cc
  core/src/stored/read_record.cc
  core/src/stored/read_record.h
  core/src/stored/record.cc
  core/src/stored/record.h
Labels: bugfix, requires backport to 22, requires backport to 23

#1736 stored: fix authentication race condition / deadlock
  CHANGELOG.md
  core/scripts/bareos-ctl-dir.in
  core/scripts/bareos-ctl-fd.in
  core/scripts/bareos-ctl-sd.in
  core/src/dird/director_jcr_impl.h
  core/src/dird/job.cc
  core/src/dird/jobq.cc
  core/src/dird/msgchan.cc
  core/src/dird/ndmp_fhdb_common.cc
  core/src/dird/ndmp_fhdb_lmdb.cc
  core/src/dird/ndmp_fhdb_mem.cc
  core/src/dird/next_vol.cc
  core/src/filed/backup.cc
  core/src/filed/dir_cmd.cc
  core/src/filed/restore.cc
  core/src/filed/status.cc
  core/src/filed/verify.cc
  core/src/filed/verify_vol.cc
  core/src/include/jcr.h
  core/src/lib/jcr.cc
  core/src/lib/thread_util.h
  core/src/stored/dir_cmd.cc
  core/src/stored/fd_cmds.cc
  core/src/stored/job.cc
  core/src/stored/ndmp_tape.cc
  core/src/stored/reserve.cc
  core/src/stored/sd_cmds.cc
  core/src/stored/status.cc
  core/src/stored/stored.cc
  core/src/stored/stored_jcr_impl.h
  systemtests/scripts/cleanup
  systemtests/scripts/functions
  systemtests/tests/parallel-jobs/CMakeLists.txt
Labels: bugfix, is a backport to 22

#1746 cats: fixes BigSqlQuery header fetching
  CHANGELOG.md
  core/src/cats/postgresql.cc
  core/src/cats/postgresql.h
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/fileset/NumberedFiles.conf.in
  systemtests/tests/python-bareos/test-setup
  systemtests/tests/python-bareos/test_list_command.py
Labels: bugfix, requires backport to 21, requires backport to 22, requires backport to 23

#1748 stored: fix not counting files correctly in mac jobs when autoxflate is enabled
  CHANGELOG.md
  core/src/dird/msgchan.cc
  core/src/lib/jcr.cc
  core/src/stored/block.cc
  core/src/stored/mac.cc
  core/src/stored/ndmp_tape.cc
  core/src/stored/read_record.cc
  core/src/stored/read_record.h
  core/src/stored/record.cc
  core/src/stored/record.h
Labels: bugfix, is a backport to 23

#1733 VMware Plugin: Backup and Restore NVRAM
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/bareos-fd-vmware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: is a backport to 23

#1747 systemtests: backport `wait for jobs to terminate` function
  CHANGELOG.md
  systemtests/scripts/check_for_zombie_jobs
  systemtests/scripts/cleanup
  systemtests/scripts/functions
  systemtests/scripts/setup
  systemtests/tests/bconsole-pam/bin/check_pam_exec_available.sh
  systemtests/tests/filesets/etc/bareos/command.sh.in
  systemtests/tests/python-bareos/write.sh
  systemtests/tests/python-pam/bin/check_pam_exec_available.sh
  systemtests/tests/python-pam/bin/pam_exec_check.sh
  systemtests/tests/webui-common/webui.in
Labels: is a backport to 21

#1749 cats: fixes BigSqlQuery header fetching
  CHANGELOG.md
  core/src/cats/postgresql.cc
  core/src/cats/postgresql.h
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/fileset/NumberedFiles.conf.in
  systemtests/tests/python-bareos/test-setup
  systemtests/tests/python-bareos/test_list_command.py
Labels: bugfix, is a backport to 23

#1750 cats: fixes BigSqlQuery header fetching
  CHANGELOG.md
  core/src/cats/bdb_postgresql.h
  core/src/cats/bdb_priv.h
  core/src/cats/postgresql.cc
  systemtests/tests/python-bareos/etc/bareos/bareos-dir.d/fileset/NumberedFiles.conf.in
  systemtests/tests/python-bareos/test-setup
  systemtests/tests/python-bareos/test_list_command.py
Labels: bugfix, is a backport to 22

#1751 cats: fixes BigSqlQuery header fetching
  CHANGELOG.md
  core/src/cats/bdb_postgresql.h
  core/src/cats/bdb_priv.h
  core/src/cats/postgresql.cc
Labels: bugfix, is a backport to 21
