Repository bareos/bareos, pull requests merged in 2024-11, with the labels that each got.

#1998 docs: add debian howto start daemons instructions
  CHANGELOG.md
  docs/manuals/source/IntroductionAndTutorial/InstallingBareos.rst
  docs/manuals/source/IntroductionAndTutorial/Tutorial.rst
Labels: documentation, requires backport to 23

#1999 docs: add debian howto start daemons instructions
  CHANGELOG.md
  docs/manuals/source/IntroductionAndTutorial/InstallingBareos.rst
  docs/manuals/source/IntroductionAndTutorial/Tutorial.rst
Labels: documentation, is a backport to 23

#1992 stored: fix volume size mismatch
  CHANGELOG.md
  core/src/include/version_hex.h
  core/src/plugins/filed/python/python-fd.cc
  core/src/stored/mount.cc
Labels: requires backport to 23, bug

#1994 add Honor No Dump Flag to config output
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/dird/inc_conf.cc
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  systemtests/tests/config-dump/etc/bareos/bareos-dir-full.conf.in
Labels: bugfix, requires backport to 23, bug

#1989 docs: move bareos-devel to github discussion
  CHANGELOG.md
  docs/manuals/source/DeveloperGuide/Webui.rst
  docs/manuals/source/DeveloperGuide/generaldevel.rst
  docs/manuals/source/DocumentationStyleGuide/CommonNames.rst
  docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
  docs/manuals/source/TasksAndConcepts/TheWindowsVersionOfBareos.rst
  docs/manuals/source/conf.py
Labels: documentation, requires backport to 23

#2010 docs: move bareos-devel to github discussion
  CHANGELOG.md
  docs/manuals/source/DeveloperGuide/Webui.rst
  docs/manuals/source/DeveloperGuide/generaldevel.rst
  docs/manuals/source/DocumentationStyleGuide/CommonNames.rst
  docs/manuals/source/TasksAndConcepts/BareosSecurityIssues.rst
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
  docs/manuals/source/TasksAndConcepts/TheWindowsVersionOfBareos.rst
  docs/manuals/source/conf.py
Labels: documentation, is a backport to 23

#2007 add Honor No Dump Flag to config output
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/dird/inc_conf.cc
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  systemtests/tests/config-dump/etc/bareos/bareos-dir-full.conf.in
Labels: bugfix, is a backport to 23, bug

#2012 backport configuration parser fixes
  .gitignore
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/lib/parse_conf_init_resource.cc
Labels: bugfix, is a backport to 23, bug

#1996 build: add support for Fedora 41
  .matrix.yml
  CHANGELOG.md
  core/CMakeLists.txt
  core/src/findlib/xattr.cc
  core/src/lib/crypto_openssl.cc
  docs/pkglists/Fedora_39.x86_64
  docs/pkglists/Fedora_41.x86_64
Labels: enhancement

#1969 dird: remove BaseJob directives
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/dird/inc_conf.cc
  core/src/filed/dir_cmd.cc
  core/src/filed/fileset.cc
  core/src/findlib/find.cc
  core/src/findlib/find.h
  core/src/tests/configs/bareos-configparser-tests/bareos-dir-CFG_TYPE_ALIST_RES.conf
  core/src/tests/test_config_parser_dir.cc
  docs/manuals/source/Configuration/Director.rst
  docs/manuals/source/TasksAndConcepts.rst
  docs/manuals/source/TasksAndConcepts/FileDeduplicationUsingBaseJobs.rst
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  systemtests/tests/config-dump/etc/bareos/bareos-dir-full.conf.in
Labels: removal

#1984 Update project Readme file
  AUTHORS
  README.md
  bareos-github-banner.png
Labels: enhancement, nobuild, documentation

#1922 JSON API: make sure, strings are valid UTF8
  CHANGELOG.md
  LICENSE.txt
  cmake/BareosCpmPackages.cmake
  cmake/Findutf8cpp.cmake
  core/src/lib/CMakeLists.txt
  core/src/lib/output_formatter.cc
  systemtests/tests/python-bareos/test_json.py
  systemtests/tests/python-bareos/test_list_command.py
Labels: bug

#1952 filed: detect integer overflow during backup
  CHANGELOG.md
  core/src/filed/CMakeLists.txt
  core/src/filed/backup.cc
  core/src/filed/backup.h
  systemtests/CMakeLists.txt
  systemtests/tests/CMakeLists.txt
  systemtests/tests/fileindex-overflow/CMakeLists.txt
  systemtests/tests/fileindex-overflow/environment.local
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bconsole.conf.in
  systemtests/tests/fileindex-overflow/functions
  systemtests/tests/fileindex-overflow/test-setup
  systemtests/tests/fileindex-overflow/testrunner-create-backup
Labels: requires backport to 23

#2027 docs: fixed typo in the filedaemon service name
  CHANGELOG.md
  docs/manuals/source/IntroductionAndTutorial/InstallingBareos.rst
Labels: documentation, requires backport to 23

#2021 core: add support for Fedora 41
  CHANGELOG.md
  core/src/findlib/xattr.cc
  core/src/lib/crypto_openssl.cc
Labels: enhancement, is a backport to 23

#2029 dedupable device: fix example files
  CHANGELOG.md
  core/platforms/packaging/bareos.spec
  core/src/stored/backends/dedupable_device.d/bareos-dir.d/storage/Dedupable.conf.example.in
  core/src/stored/backends/dedupable_device.d/bareos-dir.d/storage/dedup.conf.example
  core/src/stored/backends/dedupable_device.d/bareos-sd.d/device/Dedupable.conf.example.in
  debian/bareos-storage-dedupable.install.in
Labels: requires backport to 23

#2032 bareosfd_test.py: allow a delta of 1.1
  CHANGELOG.md
  core/src/plugins/filed/python/test/bareosfd_test.py
Labels: is a backport to 23

#2033 bareosfd_test.py: allow a delta of 1.1
  CHANGELOG.md
  core/src/plugins/filed/python/test/bareosfd_test.py
Labels: is a backport to 22

#2024 filed: detect integer overflow during backup
  CHANGELOG.md
  core/src/filed/CMakeLists.txt
  core/src/filed/backup.cc
  core/src/filed/backup.h
  systemtests/CMakeLists.txt
  systemtests/environment.in
  systemtests/tests/CMakeLists.txt
  systemtests/tests/fileindex-overflow/CMakeLists.txt
  systemtests/tests/fileindex-overflow/environment.local
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bconsole.conf.in
  systemtests/tests/fileindex-overflow/functions
  systemtests/tests/fileindex-overflow/test-setup
  systemtests/tests/fileindex-overflow/testrunner-create-backup
Labels: is a backport to 23

#2022 stored: explicitly flush after labeling
  CHANGELOG.md
  core/src/stored/backends/chunked_device.cc
  core/src/stored/label.cc
Labels: bugfix, requires backport to 23, bug
