Repository bareos/bareos, pull requests merged in 2025-04, with the labels that each got.

#2225 fix MaximumConcurrentJobs in docs and defaultsconfig
  CHANGELOG.md
  core/src/defaultconfigs/bareos-fd.d/client/myself.conf.in
  core/src/defaultconfigs/bareos-sd.d/device/FileStorage.conf.in
  core/src/defaultconfigs/bareos-sd.d/storage/bareos-sd.conf.in
  core/src/stored/device_resource.cc
  docs/manuals/source/Appendix/Troubleshooting.rst
  docs/manuals/source/Configuration/Director.rst
  docs/manuals/source/Configuration/StorageDaemon.rst
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/fd-client-MaximumConcurrentJobs.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/sd-storage-MaximumConcurrentJobs.rst.inc
Labels: requires backport to 24

#2238 fix MaximumConcurrentJobs in docs and defaultsconfig
  CHANGELOG.md
  core/src/defaultconfigs/bareos-fd.d/client/myself.conf.in
  core/src/defaultconfigs/bareos-sd.d/device/FileStorage.conf.in
  core/src/defaultconfigs/bareos-sd.d/storage/bareos-sd.conf.in
  core/src/stored/device_resource.cc
  docs/manuals/source/Appendix/Troubleshooting.rst
  docs/manuals/source/Configuration/Director.rst
  docs/manuals/source/Configuration/StorageDaemon.rst
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/fd-client-MaximumConcurrentJobs.rst.inc
  docs/manuals/source/manually_added_config_directive_descriptions/sd-storage-MaximumConcurrentJobs.rst.inc
Labels: is a backport to 24

#2241 cli-test: fix test on freebsd
  CHANGELOG.md
  core/src/stored/append.cc
  core/src/stored/checkpoint_handler.cc
  core/src/stored/checkpoint_handler.h
  core/src/tests/cli_test.cc
Labels: bug, requires backport to 24

#2242 cli-test: fix test on freebsd
  CHANGELOG.md
  core/src/stored/append.cc
  core/src/stored/checkpoint_handler.cc
  core/src/stored/checkpoint_handler.h
  core/src/tests/cli_test.cc
Labels: bug, is a backport to 24

#2222 core: refactor config parser; fix ktls configuration; fix crashes/ub
  CHANGELOG.md
  core/src/console/console_conf.cc
  core/src/dird/authenticate.cc
  core/src/dird/dird.cc
  core/src/dird/dird_conf.cc
  core/src/dird/dird_conf.h
  core/src/dird/inc_conf.cc
  core/src/dird/jcr_util.cc
  core/src/dird/reload.cc
  core/src/dird/run_conf.cc
  core/src/dird/sd_cmds.cc
  core/src/dird/ua_cmds.cc
  core/src/dird/ua_configure.cc
  core/src/filed/dir_cmd.cc
  core/src/filed/filed_conf.cc
  core/src/filed/filed_conf.h
  core/src/lib/address_conf.cc
  core/src/lib/address_conf.h
  core/src/lib/bareos_resource.h
  core/src/lib/bnet_server_tcp.cc
  core/src/lib/bsock.cc
  core/src/lib/bsock.h
  core/src/lib/bsock_tcp.cc
  core/src/lib/messages_resource_items.h
  core/src/lib/output_formatter.h
  core/src/lib/parse_conf.cc
  core/src/lib/parse_conf.h
  core/src/lib/parse_conf_callbacks.h
  core/src/lib/parse_conf_init_resource.cc
  core/src/lib/parse_conf_state_machine.cc
  core/src/lib/parse_conf_state_machine.h
  core/src/lib/res.cc
  core/src/lib/resource_item.h
  core/src/lib/tls_conf.h
  core/src/lib/tls_resource_items.h
  core/src/qt-tray-monitor/tray_conf.cc
  core/src/stored/CMakeLists.txt
  core/src/stored/dir_cmd.cc
  core/src/stored/ndmp_tape.cc
  core/src/stored/stored_conf.cc
  core/src/stored/stored_conf.h
  core/src/tests/alist_test.cc
  core/src/tests/bsock_constructor_test.cc
  core/src/tests/dlist_test.cc
  docs/manuals/source/DeveloperGuide/configparser/sd_resources_class_model.puml
  docs/manuals/source/DeveloperGuide/configparser/sd_resources_class_model_outdated.puml
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-fd-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-sd-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-tray-monitor-config-schema.json
  docs/manuals/source/include/autogenerated/bconsole-config-schema.json
  systemtests/scripts/check_for_zombie_jobs
  systemtests/tests/config-dump/etc/bareos/bareos-dir-full.conf.in
  systemtests/tests/python-bareos/test_bvfs.py
Labels: enhancement, bug, requires backport to 24

#2246 core: fix ktls configuration; fix crashes/ub
  CHANGELOG.md
  core/src/dird/authenticate.cc
  core/src/dird/dird_conf.cc
  core/src/dird/dird_conf.h
  core/src/dird/inc_conf.cc
  core/src/dird/jcr_util.cc
  core/src/dird/reload.cc
  core/src/dird/sd_cmds.cc
  core/src/dird/ua_cmds.cc
  core/src/filed/dir_cmd.cc
  core/src/filed/filed_conf.cc
  core/src/filed/filed_conf.h
  core/src/lib/address_conf.cc
  core/src/lib/address_conf.h
  core/src/lib/bnet_server_tcp.cc
  core/src/lib/bsock.cc
  core/src/lib/bsock.h
  core/src/lib/bsock_tcp.cc
  core/src/lib/parse_conf.cc
  core/src/lib/parse_conf.h
  core/src/lib/parse_conf_state_machine.cc
  core/src/lib/tls_conf.h
  core/src/lib/tls_resource_items.h
  core/src/stored/CMakeLists.txt
  core/src/stored/dir_cmd.cc
  core/src/stored/ndmp_tape.cc
  core/src/stored/stored_conf.cc
  core/src/stored/stored_conf.h
  core/src/tests/alist_test.cc
  core/src/tests/bsock_constructor_test.cc
  core/src/tests/dlist_test.cc
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-fd-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-sd-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-tray-monitor-config-schema.json
  docs/manuals/source/include/autogenerated/bconsole-config-schema.json
  systemtests/scripts/check_for_zombie_jobs
  systemtests/tests/config-dump/etc/bareos/bareos-dir-full.conf.in
  systemtests/tests/python-bareos/test_bvfs.py
Labels: bug, is a backport to 24

#2252 mariabackup: reset self.mycnf to string type
  CHANGELOG.md
  core/src/plugins/filed/python/mariabackup/bareos-fd-mariabackup.py
Labels: bugfix, bug, requires backport to 24

#2254 mariabackup: reset self.mycnf to string type
  CHANGELOG.md
  core/src/plugins/filed/python/mariabackup/bareos-fd-mariabackup.py
Labels: bugfix, bug, is a backport to 24
