Repository bareos/bareos, pull requests merged in 2025-01, with the labels that each got.

#2085 winbareos-native.nsi: do not package python3 plugins
  CHANGELOG.md
  LICENSE.txt
  core/CMakeLists.txt
  core/cmake/BareosGetDistInfo.cmake
  core/platforms/win32/winbareos-native.nsi
  core/platforms/win32/winbareos.nsi
  core/src/include/config.h.in
Labels: is a backport to 24

#2109 cmake: add cmake check whether tirpc is installed
  CHANGELOG.md
  core/CMakeLists.txt
  core/cmake/BareosFindAllLibraries.cmake
  core/src/ndmp/CMakeLists.txt
Labels: dependencies

#2111 bareos-config-libs: double quote dbconfig values
  CHANGELOG.md
  core/scripts/bareos-config-lib.sh.in
Labels: requires backport to 23, bug, requires backport to 24

#2102 freebsd: automate creation of pkg-plist.database-postgresql
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.database-postgresql
  docs/manuals/CMakeLists.txt
Labels: bugfix, requires backport to 24

#2103 freebsd: automate creation of pkg-plist.database-postgresql
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.database-postgresql
  docs/manuals/CMakeLists.txt
Labels: bugfix, is a backport to 24

#2132 plugin: postgresql use integer for savepkt.object_index
  CHANGELOG.md
  core/src/plugins/filed/python/postgresql/bareos-fd-postgresql.py
  systemtests/tests/py3plug-fd-postgresql/testrunner-default
Labels: bugfix, requires backport to 24

#2105 bconsole: enable app icon on windows
  .quality-gates.yml
  CHANGELOG.md
  core/src/console/CMakeLists.txt
  core/src/dird/CMakeLists.txt
  core/src/qt-tray-monitor/images/W.png
  core/src/qt-tray-monitor/images/bareos_1.png
  core/src/qt-tray-monitor/images/bareos_2.png
  core/src/qt-tray-monitor/images/bareos_3.png
  core/src/qt-tray-monitor/images/f.png
  core/src/qt-tray-monitor/main.qrc
  core/src/qt-tray-monitor/mainwindow.cc
  core/src/qt-tray-monitor/tray-monitor.cc
  core/src/stored/CMakeLists.txt
  core/src/tests/addresses_and_ports_config.cc
  core/src/tests/configs/addresses-and-ports/old-style/dir-v4port-and-address-set/bareos-dir.d/director/bareos-dir.conf
  core/src/win32/console/consoleres.rc.in
  core/src/win32/dird/dbcheckres.rc.in
  core/src/win32/dird/dirdres.rc.in
  core/src/win32/filed/filedres.rc.in
  core/src/win32/qt-tray-monitor/traymon.rc.in
  core/src/win32/stored/bextractres.rc.in
  core/src/win32/stored/blsres.rc.in
  core/src/win32/stored/bscanres.rc.in
  core/src/win32/stored/btaperes.rc.in
  core/src/win32/stored/storedres.rc.in
  core/src/win32/tools/bregexres.rc.in
  core/src/win32/tools/bsmtpres.rc.in
  core/src/win32/tools/bwildres.rc.in
  webui/tests/selenium/webui-selenium-test.py
Labels: bugfix, bug, requires backport to 24

#2135 plugin: postgresql use integer for savepkt.object_index
  CHANGELOG.md
  core/src/plugins/filed/python/postgresql/bareos-fd-postgresql.py
  systemtests/tests/py3plug-fd-postgresql/testrunner-default
Labels: bugfix, is a backport to 24

#2133 bareos-config-libs: double quote dbconfig values
  CHANGELOG.md
  core/scripts/bareos-config-lib.sh.in
Labels: bug, is a backport to 24

#2134 bareos-config-libs: double quote dbconfig values
  .matrix.yml
  CHANGELOG.md
  core/scripts/bareos-config-lib.sh.in
Labels: is a backport to 23, bug

#2078 openssl: unify ssl error logging
  CHANGELOG.md
  core/src/lib/crypto_openssl.cc
  core/src/lib/crypto_openssl.h
  core/src/lib/tls_openssl.cc
  core/src/lib/tls_openssl_private.cc
  core/src/tests/test_bpipe.cc
Labels: enhancement
