Repository bareos/bareos, pull requests merged in 2025-08, with the labels that each got.

#2341 VMware Plugin: Adapt to pyVmomi 9
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/bareos-fd-vmware.py
Labels: bugfix, requires backport to 24

#2344 VMWare Plugin: Fix VirtualSerialPort, NVRAM timeouts configurable
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/bareos-fd-vmware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: bugfix, requires backport to 24

#2345 VMWare Plugin: Fix VirtualSerialPort, NVRAM timeouts configurable
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/bareos-fd-vmware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: bugfix, is a backport to 24

#2329 systemtest: always incremental add one job with one removed file
  CHANGELOG.md
  systemtests/tests/always-incremental-consolidate/CMakeLists.txt
  systemtests/tests/always-incremental-consolidate/testrunner-04-virtualfull
  systemtests/tests/always-incremental-consolidate/testrunner-05-consolidate-deleted-file
  systemtests/tests/always-incremental-consolidate/testrunner-06-priority
  systemtests/tests/always-incremental-consolidate/testrunner-07-consolidate-duplicates
  systemtests/tests/always-incremental-consolidate/testrunner-08-rerun-ai-vf
Labels: enhancement

#2351 webui: add summary subscription report
  CHANGELOG.md
  webui/module/Director/src/Director/Controller/DirectorController.php
  webui/module/Director/view/director/director/subscription.phtml
Labels: enhancement, is a backport to 24
