Repository bareos/bareos, pull requests merged in 2025-09, with the labels that each got.

#2279 fix next-pool overrides by job
  CHANGELOG.md
  core/src/dird/ua_run.cc
  docs/manuals/source/TasksAndConcepts/BareosConsole.rst
  docs/manuals/source/manually_added_config_directive_descriptions/dir-job-NextPool.rst.inc
  systemtests/tests/copy-migrate/etc/bareos/bareos-dir.d/job/copy-with-next-pool-override.conf
  systemtests/tests/copy-migrate/etc/bareos/bareos-dir.d/pool/AnotherFullCopy.conf
  systemtests/tests/copy-migrate/testrunner-02-copy
Labels: bug

#2359 stored: fix race condition
  CHANGELOG.md
  core/src/stored/vol_mgr.cc
Labels: bugfix, requires backport to 23, bug, requires backport to 24

#2371 grpc: fix missing some early events
  CHANGELOG.md
  contrib/fd-plugins/bareos_mysql_dump/BareosFdMySQLclass.py
  contrib/fd-plugins/bareos_tasks/BareosFdTaskClass.py
  contrib/fd-plugins/openvz7/BareosFdPluginVz7CtFs.py
  core/src/filed/fd_plugins.h
  core/src/lib/res.cc
  core/src/plugins/filed/grpc/bridge_module/bridge_module.cc
  core/src/plugins/filed/grpc/bridge_module/plugin_service.cc
  core/src/plugins/filed/grpc/bridge_module/plugin_service.h
  core/src/plugins/filed/grpc/grpc.cc
  core/src/plugins/filed/grpc/grpc_impl.cc
  core/src/plugins/filed/grpc/grpc_impl.h
  core/src/plugins/filed/grpc/proto/common.proto
  core/src/plugins/filed/python/module/bareosfd.cc
  core/src/plugins/filed/python/module/bareosfd.h
  core/src/plugins/filed/python/postgresql/bareos-fd-postgresql.py
  core/src/plugins/filed/python/pyfiles/BareosFdPluginBaseclass.py
  core/src/plugins/filed/python/pyfiles/BareosFdPluginLocalFilesBaseclass.py
  systemtests/tests/py3plug-fd-local-fileset-restoreobject/python-modules/BareosFdPluginLocalFilesetWithRestoreObjects.py
Labels: bug, is a backport to 24

#2366 systemtest: speed up always-incremental with sleep 0.25
  CHANGELOG.md
  systemtests/tests/always-incremental-consolidate/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf.in
  systemtests/tests/always-incremental-consolidate/testrunner-06-consolidate-duplicates
  systemtests/tests/always-incremental-consolidate/testrunner-07-rerun-ai-vf
Labels: enhancement, is a backport to 24

#2374 packaging: add setcap/getcap requirements
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.common
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.storage
  core/platforms/packaging/bareos.spec
  debian/bareos-common.install.in
  debian/bareos-storage.install.in
  debian/control.bareos-common
Labels: bugfix, dependencies, is a backport to 24
