Repository bareos/bareos, pull requests merged in 2025-05, with the labels that each got.

#2260 dird: fix bugs in DateTime
  CHANGELOG.md
  core/src/dird/date_time.cc
  core/src/dird/date_time.h
Labels: bug

#2259 config: fix Director -> Director resource
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-fd-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-sd-config-schema.json
Labels: bug, requires backport to 24

#2256 mtx-changer: make mandatory test mt-st versus cpio-mt
  CHANGELOG.md
  core/scripts/mtx-changer.conf
Labels: bug, requires backport to 24

#2274 config: fix Director -> Director resource
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-fd-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-sd-config-schema.json
Labels: bug, is a backport to 24

#2264 stored: fix sd volume limit
  CHANGELOG.md
  core/src/cats/cats.h
  core/src/cats/postgresql.cc
  core/src/cats/postgresql.h
  core/src/cats/sql_pooling.cc
  core/src/dird/check_catalog.cc
  core/src/dird/dbcheck.cc
  core/src/stored/askdir.cc
  core/src/stored/bscan.cc
  core/src/tests/run_on_incoming_connect_interval.cc
  systemtests/tests/CMakeLists.txt
  systemtests/tests/bareos-basic/testrunner-test-make-catalog-backup
  systemtests/tests/sd-volume-limit/CMakeLists.txt
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/sd-volume-limit/etc/bareos/bconsole.conf.in
  systemtests/tests/sd-volume-limit/slow-read.sh
  systemtests/tests/sd-volume-limit/test-setup
  systemtests/tests/sd-volume-limit/testrunner-check-volume-creation
Labels: requires backport to 24

#2268 packaging: set all `*.conf.examples` as %config(noreplace)
  CHANGELOG.md
  core/platforms/packaging/bareos.spec
  systemtests/tests/sd-volume-limit/etc/bareos/bareos-fd.d/client/myself.conf.in
Labels: bug, requires backport to 24

#2277 various cmake improvements (partial)
  CHANGELOG.md
  core/CMakeLists.txt
  core/CTestScript.cmake.in
  systemtests/tests/sd-volume-limit/CMakeLists.txt
Labels: is a backport to 24

#2271 packaging: set all `*.conf.examples` as %config(noreplace)
  CHANGELOG.md
  core/platforms/packaging/bareos.spec
Labels: bug, is a backport to 24

#2278 disable bareosfd-python3-module-test on FreeBSD
  CHANGELOG.md
  core/src/plugins/filed/python/CMakeLists.txt
Labels: bug, requires backport to 24

#2280 disable bareosfd-python3-module-test on FreeBSD
  CHANGELOG.md
  core/src/plugins/filed/python/CMakeLists.txt
Labels: bug, is a backport to 24

#2275 packaging: use GCC 14 for RHEL 8/9
  .matrix.yml
  CHANGELOG.md
  core/platforms/packaging/bareos-universal-client.spec
  core/platforms/packaging/bareos.spec
Labels: enhancement

#2270 setgid on configdirs
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.bconsole
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.common
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.filedaemon
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.storage
  core/platforms/packaging/bareos.spec
  core/scripts/bareos-config-lib.sh.in
  debian/bareos-director.postinst.in
Labels: requires no backport
