Repository bareos/bareos, pull requests merged in 2025-03, with the labels that each got.

#2192 reduce test-matrix
  .matrix.yml
  CHANGELOG.md
Labels: requires backport to 24

#2199 reduce test-matrix
  .matrix.yml
  CHANGELOG.md
Labels: is a backport to 24

#2180 Make tests optional
  CHANGELOG.md
  CMakeLists.txt
  core/CMakeLists.txt
Labels: enhancement

#2202 cleanup: fix multi-config tests
  CHANGELOG.md
  systemtests/scripts/cleanup
  systemtests/tests/just-in-time-reservation/test-setup
Labels: requires backport to 23, bug, requires backport to 24

#2203 cleanup: fix multi-config tests
  CHANGELOG.md
  systemtests/scripts/cleanup
  systemtests/tests/just-in-time-reservation/test-setup
Labels: bug, is a backport to 24

#2170 Fix btape fill-test problem
  CHANGELOG.md
  core/src/dird/run_conf.cc
  core/src/stored/btape.cc
Labels: bugfix, bug, is a backport to 24

#2220 docs rear: update to rear >= 2.8
  CHANGELOG.md
  docs/manuals/source/Appendix/DisasterRecoveryUsingBareos.rst
Labels: documentation, requires backport to 24

#2201 webui: use WEB_UI path in apache bareos-webui.conf file
  .gitignore
  CHANGELOG.md
  webui/CMakeLists.txt
  webui/install/apache/bareos-webui.conf
  webui/install/apache/bareos-webui.conf.in
Labels: enhancement, requires backport to 24

#2223 webui: use WEB_UI path in apache bareos-webui.conf file
  .gitignore
  CHANGELOG.md
  webui/CMakeLists.txt
  webui/install/apache/bareos-webui.conf
  webui/install/apache/bareos-webui.conf.in
Labels: enhancement, is a backport to 24

#2227 mssqlvdi-fd: add support for filestream backups
  CHANGELOG.md
  core/src/filed/verify.cc
  core/src/win32/plugins/filed/mssqlvdi-fd.cc
  core/src/win32/vdi/include/vdi.h
Labels: is a backport to 23, bug

#2190 alist: fix race condition while iterating
  CHANGELOG.md
  core/src/cats/cats_backends.cc
  core/src/dird/backup.cc
  core/src/dird/dir_plugins.cc
  core/src/dird/dird_conf.cc
  core/src/dird/fd_cmds.cc
  core/src/dird/job.cc
  core/src/dird/msgchan.cc
  core/src/dird/ndmp_dma_generic.cc
  core/src/dird/ndmp_dma_storage.cc
  core/src/dird/sd_cmds.cc
  core/src/dird/storage.cc
  core/src/dird/ua_acl.cc
  core/src/dird/ua_audit.cc
  core/src/dird/ua_cmds.cc
  core/src/dird/ua_dotcmds.cc
  core/src/dird/ua_select.cc
  core/src/filed/crypto.cc
  core/src/filed/dir_cmd.cc
  core/src/filed/fd_plugins.cc
  core/src/filed/filed.cc
  core/src/filed/filed_conf.cc
  core/src/filed/filed_utils.cc
  core/src/filed/restore.cc
  core/src/findlib/xattr.cc
  core/src/lib/alist.h
  core/src/lib/bnet_server_tcp.cc
  core/src/lib/breg.cc
  core/src/lib/crypto_openssl.cc
  core/src/lib/output_formatter.cc
  core/src/lib/output_formatter_resource.cc
  core/src/lib/plugins.cc
  core/src/lib/runscript.cc
  core/src/stored/autochanger.cc
  core/src/stored/autochanger_resource.cc
  core/src/stored/backends/chunked_device.cc
  core/src/stored/bextract.cc
  core/src/stored/dir_cmd.cc
  core/src/stored/job.cc
  core/src/stored/reserve.cc
  core/src/stored/sd_plugins.cc
  core/src/stored/status.cc
  core/src/stored/stored_conf.cc
  core/src/tests/alist_test.cc
  core/src/tests/multiplied_device_test.cc
  core/src/tests/test_config_parser_dir.cc
Labels: bugfix, is a backport to 22, bug

#2232 cmake: fix not including BareosTargetTools in systemtests, needed for get_target_output_dir
  CHANGELOG.md
  systemtests/CMakeLists.txt
Labels: bug, requires backport to 24

#2235 cmake: fix not including BareosTargetTools in systemtests, needed for get_target_output_dir
  CHANGELOG.md
  systemtests/CMakeLists.txt
Labels: bug, is a backport to 24
