Repository bareos/bareos, pull requests merged in 2025-06, with the labels that each got.

#2288 fix problems with msvc 19.44
  CHANGELOG.md
  core/platforms/win32/winbareos-native.nsi
  core/src/dird/run_on_incoming_connect_interval.cc
  core/src/stored/checkpoint_handler.cc
  core/src/tests/test_bpipe.cc
Labels: is a backport to 24

#2291 VMware Plugin: Fix for virtual USB devices
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/bareos-fd-vmware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: is a backport to 24

#2273 plugins: fix error_string construction
  CHANGELOG.md
  core/src/plugins/include/python_plugins_common.inc
Labels: requires backport to 22, requires backport to 23, bug, requires backport to 24

#2240 dplcompat: fix unsupported size-suffixes on chunksize
  CHANGELOG.md
  CMakeLists.txt
  cmake/BareosTestCoverage.cmake
  core/CMakeLists.txt
  core/src/stored/CMakeLists.txt
  core/src/stored/backends/CMakeLists.txt
  core/src/stored/backends/chunked_device.cc
  core/src/stored/backends/crud_storage.cc
  core/src/stored/backends/dplcompat_device.cc
  core/src/stored/backends/util.h
  core/src/tests/CMakeLists.txt
Labels: bug, requires backport to 24

#2292 plugins: fix error_string construction
  CHANGELOG.md
  core/src/plugins/include/python_plugins_common.inc
Labels: bug, is a backport to 24

#2294 plugins: fix error_string construction
  CHANGELOG.md
  core/src/plugins/include/python_plugins_common.inc
  docs/manuals/source/include/autogenerated/bareos-dir-config-schema.json
  docs/manuals/source/include/autogenerated/bareos-sd-config-schema.json
  systemtests/scripts/functions
Labels: is a backport to 22, bug

#2303 python: fix traceback generation
  CHANGELOG.md
  core/src/plugins/include/python_plugins_common.inc
Labels: requires backport to 22, requires backport to 23, requires backport to 24
