Repository bareos/bareos, pull requests merged in 2025-02, with the labels that each got.

#2138 openssl: unify ssl error logging
  CHANGELOG.md
  core/src/lib/crypto_openssl.cc
  core/src/lib/crypto_openssl.h
  core/src/lib/tls_openssl.cc
  core/src/lib/tls_openssl_private.cc
  core/src/tests/test_bpipe.cc
Labels: enhancement, is a backport to 24

#2097 Inherit RunScript elements between JobDef resources
  CHANGELOG.md
  core/src/dird/dird_conf.cc
  core/src/tests/configs/runscript-inheritance.conf
  core/src/tests/test_config_parser_dir.cc
Labels: enhancement

#2131 bconsole: enable app icon on windows
  .quality-gates.yml
  CHANGELOG.md
  core/src/console/CMakeLists.txt
  core/src/dird/CMakeLists.txt
  core/src/qt-tray-monitor/images/W.png
  core/src/qt-tray-monitor/images/bareos_1.png
  core/src/qt-tray-monitor/images/bareos_2.png
  core/src/qt-tray-monitor/images/bareos_3.png
  core/src/qt-tray-monitor/images/f.png
  core/src/qt-tray-monitor/main.qrc
  core/src/qt-tray-monitor/mainwindow.cc
  core/src/qt-tray-monitor/tray-monitor.cc
  core/src/stored/CMakeLists.txt
  core/src/tests/addresses_and_ports_config.cc
  core/src/tests/configs/addresses-and-ports/old-style/dir-v4port-and-address-set/bareos-dir.d/director/bareos-dir.conf
  core/src/win32/console/consoleres.rc.in
  core/src/win32/dird/dbcheckres.rc.in
  core/src/win32/dird/dirdres.rc.in
  core/src/win32/filed/filedres.rc.in
  core/src/win32/qt-tray-monitor/traymon.rc.in
  core/src/win32/stored/bextractres.rc.in
  core/src/win32/stored/blsres.rc.in
  core/src/win32/stored/bscanres.rc.in
  core/src/win32/stored/btaperes.rc.in
  core/src/win32/stored/storedres.rc.in
  core/src/win32/tools/bregexres.rc.in
  core/src/win32/tools/bsmtpres.rc.in
  core/src/win32/tools/bwildres.rc.in
  webui/tests/selenium/webui-selenium-test.py
Labels: bugfix, bug, is a backport to 24

#2130 python-bareos: Add missing dh-python build dep
  AUTHORS
  CHANGELOG.md
  python-bareos/debian/control
Labels: requires backport to 24

#2122 stored: list all devices if device is invalid/missing
  CHANGELOG.md
  core/src/stored/bcopy.cc
  core/src/stored/bextract.cc
  core/src/stored/bls.cc
  core/src/stored/bscan.cc
  core/src/stored/btape.cc
  core/src/stored/butil.cc
  core/src/stored/butil.h
  docs/manuals/source/include/autogenerated/usage/bcopy.txt
  docs/manuals/source/include/autogenerated/usage/bextract.txt
  docs/manuals/source/include/autogenerated/usage/bls.txt
  docs/manuals/source/include/autogenerated/usage/bscan.txt
  docs/manuals/source/include/autogenerated/usage/btape.txt
  systemtests/CMakeLists.txt
  systemtests/environment.in
  systemtests/tests/CMakeLists.txt
  systemtests/tests/bscan-bextract-bls-bcopy-btape/CMakeLists.txt
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-dir.d/catalog/MyCatalog.conf.in
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-dir.d/director/bareos-dir.conf.in
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-dir.d/fileset/Catalog.conf.in
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-dir.d/fileset/SelfTest.conf.in
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-dir.d/job/RestoreFiles.conf.in
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-dir.d/job/backup-bareos-fd.conf.in
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-dir.d/jobdefs/DefaultJob.conf.in
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-dir.d/messages/Daemon.conf.in
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-dir.d/messages/Standard.conf.in
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-dir.d/pool/Differential.conf
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-dir.d/pool/Incremental.conf
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-dir.d/pool/Scratch.conf
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-dir.d/profile/operator.conf
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-dir.d/storage/File.conf.in
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-fd.d/director/bareos-dir.conf.in
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-fd.d/messages/Standard.conf
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-sd.d/device/FileStorage.conf
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-sd.d/device/FileStorage2.conf
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-sd.d/director/bareos-dir.conf.in
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-sd.d/messages/Standard.conf
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/bscan-bextract-bls-bcopy-btape/etc/bareos/bconsole.conf.in
  systemtests/tests/bscan-bextract-bls-bcopy-btape/testrunner
Labels: enhancement

#2128 debian: Add missing build dependencies
  CHANGELOG.md
  debian/control
  debian/control.src
Labels: requires backport to 24

#2162 windows: fix readlink buffer size issue
  CHANGELOG.md
  core/src/tests/test_config_parser_console.cc
  core/src/win32/compat/compat.cc
Labels: is a backport to 23, bug

#2161 windows: fix readlink buffer size issue
  CHANGELOG.md
  core/src/plugins/filed/grpc/grpc_test_module.cc
  core/src/tests/test_config_parser_console.cc
  core/src/win32/compat/compat.cc
Labels: bug, is a backport to 24

#2144 systemtests: fail if daemons have config warnings
  CHANGELOG.md
  core/scripts/bareos-ctl-dir.in
  core/scripts/bareos-ctl-fd.in
  core/scripts/bareos-ctl-funcs
  core/scripts/bareos-ctl-sd.in
  docs/manuals/source/DeveloperGuide/BuildAndTestBareos/systemtests.rst
  systemtests/cmake/BareosSystemtestFunctions.cmake
  systemtests/environment.in
  systemtests/tests/block-size/CMakeLists.txt
  systemtests/tests/config-dump/etc/bareos/bareos-dir-full.conf.in
  systemtests/tests/dplcompat/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/dplcompat/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/droplet-s3/CMakeLists.txt
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/fileindex-overflow/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/grpc-fd/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/grpc-fd/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/parallel-jobs/CMakeLists.txt
  systemtests/tests/pruning/etc/bareos/bareos-dir.d/client/bareos-fd.conf.in
  systemtests/tests/pruning/etc/bareos/bareos-dir.d/pool/Full.conf
  systemtests/tests/pruning/testrunner
Labels: enhancement

#2018 Fix btape fill-test problem
  CHANGELOG.md
  core/src/dird/run_conf.cc
  core/src/stored/btape.cc
Labels: bugfix, requires backport to 23, bug, requires backport to 24

#2147 contrib: check_chunk.py improve README.md instructions
  CHANGELOG.md
  contrib/misc/chunk_check/README.md
Labels: enhancement

#2106 build: add support for el10
  .matrix.yml
  CHANGELOG.md
  cmake/BareosCpmPackages.cmake
  core/platforms/packaging/bareos.spec
  docs/pkglists/EL_10.aarch64
  docs/pkglists/EL_10.x86_64
  systemtests/scripts/cleanup
Labels: enhancement, requires backport to 24

#2150 debian: Add missing build dependencies
  CHANGELOG.md
  debian/control
  debian/control.src
Labels: is a backport to 24

#2169 cmake: add cmake_parse_arguments policy CMP0174
  CHANGELOG.md
  CMakeLists.txt
  core/cmake/BareosCopyDllsToBinDir.cmake
Labels: bugfix, requires backport to 24

#2172 cmake: add cmake_parse_arguments policy CMP0174
  CHANGELOG.md
  CMakeLists.txt
  core/cmake/BareosCopyDllsToBinDir.cmake
Labels: bugfix, is a backport to 24

#2059 VMware plugin: fix check_mac_address() for vm.config not present
  AUTHORS
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/bareos-fd-vmware.py
Labels: bugfix, requires backport to 23, bug, requires backport to 24

#2164 build: add support for el10
  .matrix.yml
  CHANGELOG.md
  cmake/BareosCpmPackages.cmake
  core/platforms/packaging/bareos.spec
  docs/pkglists/EL_10.aarch64
  docs/pkglists/EL_10.x86_64
  systemtests/scripts/cleanup
Labels: enhancement, is a backport to 24

#2152 VMware Plugin: Fix CBT query handling
  CHANGELOG.md
  contrib/misc/reschedule_job_as_full/reschedule_job_as_full.sh
  core/src/plugins/filed/python/vmware/bareos-fd-vmware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: requires backport to 23, requires backport to 24

#2149 docs: add devtools documentation
  CHANGELOG.md
  devtools/README.md
  devtools/php-cs-fixer/README.md
  devtools/pip-tools/README.md
  docs/manuals/source/DeveloperGuide/generaldevel.rst
Labels: documentation

#2163 windows: fix readlink buffer size issue
  .quality-gates.yml
  CHANGELOG.md
  core/src/tests/test_config_parser_console.cc
  core/src/win32/compat/compat.cc
Labels: is a backport to 22, bug

#2120 scheduler: 'last' keyword doesn't allow job to be visible in status dir
  CHANGELOG.md
  core/src/dird/CMakeLists.txt
  core/src/dird/date_time.cc
  core/src/dird/date_time.h
  core/src/dird/date_time_mask.cc
  core/src/dird/date_time_mask.h
  core/src/dird/dird_conf.cc
  core/src/dird/dird_conf.h
  core/src/dird/run_conf.cc
  core/src/dird/run_hour_validator.cc
  core/src/dird/scheduler_private.cc
  core/src/dird/ua_output.cc
  core/src/dird/ua_output.h
  core/src/dird/ua_status.cc
  core/src/tests/CMakeLists.txt
  core/src/tests/scheduler_job_item_queue.cc
  core/src/tests/test_config_parser_console.cc
  core/src/tests/test_config_parser_dir.cc
  core/src/tests/test_config_parser_sd.cc
  systemtests/tests/config-dump/etc/bareos/bareos-dir-full.conf.in
  systemtests/tests/scheduler/etc/bareos/bareos-dir.d/job/LastSunday.conf
  systemtests/tests/scheduler/test-setup
  systemtests/tests/scheduler/testrunner-scheduler-last-keyword
Labels: bug

#2183 VMware Plugin: Fix CBT query handling
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/bareos-fd-vmware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: is a backport to 23

#2182 VMware Plugin: Fix CBT query handling
  CHANGELOG.md
  contrib/misc/reschedule_job_as_full/reschedule_job_as_full.sh
  core/src/plugins/filed/python/vmware/bareos-fd-vmware.py
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: is a backport to 24

#2121 fix autodeflate messages and refactor setup method
  CHANGELOG.md
  core/cmake/BareosCopyDllsToBinDir.cmake
  core/src/filed/compression.cc
  core/src/filed/dir_cmd.cc
  core/src/include/ch.h
  core/src/lib/compression.cc
  core/src/lib/compression.h
  core/src/plugins/stored/autoxflate/autoxflate-sd.cc
  systemtests/scripts/functions
Labels: bug

#2141 stored: fix crash when using jit reservation with no matching device; fix reservation error
  CHANGELOG.md
  core/src/stored/acquire.cc
  core/src/stored/append.cc
  core/src/stored/device_control_record.h
  core/src/stored/mount.cc
Labels: requires backport to 23, bug, requires backport to 24

#2178 VMware plugin: fix check_mac_address() for vm.config not present
  AUTHORS
  CHANGELOG.md
  core/src/plugins/filed/python/vmware/bareos-fd-vmware.py
Labels: bugfix, is a backport to 23, bug

#2184 stored: fix crash when using jit reservation with no matching device; fix reservation error
  CHANGELOG.md
  core/src/stored/acquire.cc
  core/src/stored/append.cc
  core/src/stored/device_control_record.h
  core/src/stored/mount.cc
Labels: bug, is a backport to 24

#2016 alist: fix race condition while iterating
  CHANGELOG.md
  core/src/dird/backup.cc
  core/src/dird/dir_plugins.cc
  core/src/dird/dird_conf.cc
  core/src/dird/fd_cmds.cc
  core/src/dird/job.cc
  core/src/dird/msgchan.cc
  core/src/dird/ndmp_dma_generic.cc
  core/src/dird/ndmp_dma_storage.cc
  core/src/dird/sd_cmds.cc
  core/src/dird/storage.cc
  core/src/dird/ua_acl.cc
  core/src/dird/ua_audit.cc
  core/src/dird/ua_cmds.cc
  core/src/dird/ua_dotcmds.cc
  core/src/dird/ua_select.cc
  core/src/filed/crypto.cc
  core/src/filed/dir_cmd.cc
  core/src/filed/fd_plugins.cc
  core/src/filed/filed_conf.cc
  core/src/filed/filed_utils.cc
  core/src/filed/restore.cc
  core/src/findlib/xattr.cc
  core/src/lib/alist.h
  core/src/lib/bnet_server_tcp.cc
  core/src/lib/breg.cc
  core/src/lib/crypto_openssl.cc
  core/src/lib/output_formatter.cc
  core/src/lib/output_formatter_resource.cc
  core/src/lib/plugins.cc
  core/src/lib/runscript.cc
  core/src/stored/autochanger.cc
  core/src/stored/autochanger_resource.cc
  core/src/stored/backends/chunked_device.cc
  core/src/stored/bextract.cc
  core/src/stored/dir_cmd.cc
  core/src/stored/reserve.cc
  core/src/stored/sd_plugins.cc
  core/src/stored/status.cc
  core/src/stored/stored_conf.cc
  core/src/tests/alist_test.cc
  core/src/tests/multiplied_device_test.cc
  core/src/tests/test_config_parser_dir.cc
Labels: requires backport to 22, is a backport to 23

#2175 Fix 32bit compilation
  CHANGELOG.md
  core/src/stored/backends/chunked_device.cc
  core/src/stored/backends/dedupable/volume.cc
Labels: enhancement

#2195 webui: use TemporaryDir as userdatadir in Selenium test
  CHANGELOG.md
  webui/tests/selenium/webui-selenium-test.py
Labels: is a backport to 24

#2196 webui: use TemporaryDir as userdatadir in Selenium test
  CHANGELOG.md
  webui/tests/selenium/webui-selenium-test.py
Labels: is a backport to 23
