Repository bareos/bareos, pull requests merged in 2025-07, with the labels that each got.

#2306 python: fix traceback generation
  CHANGELOG.md
  core/src/plugins/include/python_plugins_common.inc
Labels: is a backport to 22

#2290 build: add Debian 13
  .matrix.yml
  CHANGELOG.md
  debian/control
  debian/control.bareos-webui
  docs/pkglists/Debian_13.x86_64
Labels: requires backport to 24

#2311 build: add Debian 13
  .matrix.yml
  CHANGELOG.md
  debian/control
  debian/control.bareos-webui
  docs/pkglists/Debian_13.x86_64
Labels: is a backport to 24

#2300 truncate: fix return status bug
  CHANGELOG.md
  core/src/dird/ua_cmds.cc
  systemtests/tests/admin-job/etc/bareos/bareos-dir.d/job/admin-truncate.conf
  systemtests/tests/admin-job/etc/bareos/bareos-dir.d/pool/PurgePool.conf
  systemtests/tests/admin-job/testrunner-list-jobs
  systemtests/tests/admin-job/testrunner-truncate
Labels: requires backport to 23, bug, requires backport to 24

#2316 Build FreeBSD for major versions 14 / 13 (instead of minor releases)
  .matrix.yml
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.director-python-plugin
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.filedaemon-python3-plugin
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.storage-python-plugin
  core/src/ndmp/CMakeLists.txt
Labels: enhancement, is a backport to 24

#2315 docs: Python plugin dependencies installation
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: documentation, requires backport to 24

#2319 docs: Python plugin dependencies installation
  CHANGELOG.md
  docs/manuals/source/TasksAndConcepts/Plugins/FileDaemonPlugins/VMwarePlugin.rst.inc
Labels: documentation, is a backport to 24

#2321 matrix: test the Debian ULC packages for OpenSSL 1.1 on Debian 11 instead of Debian 10
  .matrix.yml
  CHANGELOG.md
  systemtests/tests/admin-job/testrunner-truncate
Labels: requires backport to 23, requires backport to 24

#2323 matrix: test the Debian ULC packages for OpenSSL 1.1 on Debian 11 instead of Debian 10
  .matrix.yml
  CHANGELOG.md
Labels: is a backport to 23

#2269 ndmp-bareos: Introduce incremental loop, restore 2nd file explicitly
  CHANGELOG.md
  core/src/stored/record.cc
  systemtests/tests/ndmp-bareos/CMakeLists.txt
  systemtests/tests/ndmp-bareos/testrunner
  systemtests/tests/ndmp-native/etc/bareos/bareos-fd.d/client/myself.conf.in
  systemtests/tests/ndmp-native/etc/bareos/bareos-sd.d/storage/bareos-sd.conf.in
  systemtests/tests/ndmp-native/testrunner
Labels: requires backport to 24

#2207 stored: add new volume status 'Unlabeled'
  CHANGELOG.md
  core/platforms/freebsd/bareos-freebsd/bareos.com-common/pkg-plist.database-postgresql
  core/src/cats/cats.h
  core/src/cats/ddl/creates/postgresql.sql
  core/src/cats/ddl/updates/postgresql.2240_2250.sql
  core/src/cats/ddl/versions.map.in
  core/src/cats/sql_find.cc
  core/src/dird/dird_conf.cc
  core/src/dird/next_vol.cc
  core/src/dird/ua_db.cc
  core/src/dird/ua_label.cc
  core/src/stored/askdir.cc
  core/src/stored/dir_cmd.cc
  docs/manuals/source/DeveloperGuide/catalog.rst
  docs/manuals/source/TasksAndConcepts/BareosConsole.rst
  docs/manuals/source/TasksAndConcepts/UsingTapeDrivesWithoutAutochanger.rst
  docs/manuals/source/TasksAndConcepts/VolumeManagement.rst
Labels: enhancement, bug
